### PR TITLE
New Go client library and benchmarks.

### PR DESCRIPTION
**Pull request by corylanou**
All WIP, nothing to see here.

### CODE REVIEW

**Comment by corylanou** [comment]
@otoolep this is the first "phase" of the new cli and client library.  There will be more work to come, but basic functionality here is already useful.  I suggest closing this so people can see where we are headed and I will pick it back up in a future PR.  Thoughts?

**Comment by otoolep** [comment]
But not merging, correct?

**Comment by corylanou** [comment]
@otoolep I am suggesting merging this.  Currently, the client library and cli are completely broken and useless.  This brings up a baseline cli, and baseline client library.  While we are going to be adding more functionality later, what we have here is already useful.

**Comment by otoolep** [comment]
Fine with me, since the current CLI is of very little value due to the API change, I don't think we're losing anything.

**Pull request merged**
