### PR TITLE
SHOW FIELD shouldn't expect VALUES.

### LINKED ISSUE #5176: [CLI] "show field values" not working  [0.9.5.1]
```
[ksengal@csdev-ksengal testInflux]$ influx
Visit https://enterprise.influxdata.com to register for updates, InfluxDB server management, and monitoring.
Connected to http://localhost:8086 version 0.9.5.1
InfluxDB shell 0.9.5.1
%> show databases
name: databases
---------------
name
FAKEDBNAME

%> use FAKEDBNAME
Using database FAKEDBNAME
%> show series
name: TABLENAME
---------------
_key					FAKETAG1	FAKETAG2
TABLENAME,FAKETAG1=F1,FAKETAG2=F2	F1		F2

%> show field 
ERR: error parsing query: found EOF, expected KEYS, VALUES at line 1, char 12
%> show field keys
name: TABLENAME
---------------
fieldKey
FIELD1
FIELD2

%> show field values
ERR: error parsing query: found VALUES, expected KEYS, VALUES at line 1, char 12
```

(( See right above, it says it found VALUES but expected one of KEYS or VALUES ))

### PR DESCRIPTION
**Pull request by pires**
- [ ] CHANGELOG.md updated
- [x] Rebased/mergable
- [x] Tests pass
- [x] Sign CLA (if not already signed)

Fixes #5176

### CODE REVIEW

**Comment by otoolep** [comment]
Any chance we could add a test for this? Is that possible?

**Comment by pires** [comment]
There are tests for `SHOW FIELD KEYS`. `SHOW FIELD VALUES` seems to not be valid at all, and the reason why it's there is unknown to me. I assumed it was supposed to be removed anyway.

**Comment by otoolep** [comment]
Ah, I see. I had it backwards.

**Comment by pires** [comment]
@beckettsean what do you think then about the proposed fix?

**Comment by beckettsean** [comment]
@pires looks good to me, but I'm not qualified to vet Go code.

**Comment by otoolep** [comment]
+1

@dgnorton ?

**Comment by dgnorton** [comment]
+1  Thanks, @pires !

**Pull request merged**
