### PR TITLE
Fix #4358: TSM engine breaks windows compatibility 

### LINKED ISSUE #4358: TSM engine breaks windows compatibility
```
$ GOOS=windows GOARCH=amd64 go build ./cmd/influxd
# github.com/influxdb/influxdb/tsdb/engine/tsm1
tsdb/engine/tsm1/tsm1.go:1799: undefined: syscall.Mmap
tsdb/engine/tsm1/tsm1.go:1799: undefined: syscall.PROT_READ
tsdb/engine/tsm1/tsm1.go:1799: undefined: syscall.MAP_SHARED
tsdb/engine/tsm1/tsm1.go:1836: undefined: syscall.Munmap
```

@pauldix @jwilder

### PR DESCRIPTION
**Pull request by mvadu**
Fixing https://github.com/influxdb/influxdb/issues/4358

I tried adding mmap implementation for Windows based on MapViewOfFile. Used SliceHeader trick to change the pointer returned by MapViewOfFile to a byte slice. This will not call for any change in rest of tsm.

tsm1.go was directly calling `syscall.Mmap` not the custom defined `mmap` (defined both unix and windows versions).

`mmap, err := syscall.Mmap(int(f.Fd()), 0, int(fInfo.Size()), syscall.PROT_READ, syscall.MAP_SHARED|MAP_POPULATE)`

Hence removed Syscall.Mmap  to use mmap, which should use respective plat form specific functions.

Note: This is the first time I am working on a fork repo. Please excuse me if I did some silly mistake. I am new to go, and was not able to test this PR with a Linux machine.

### CODE REVIEW

**Comment by mvadu** [comment]
@otoolep @corylanou I need some help here.. Circelci is failing 

`?   	github.com/influxdb/influxdb/tsdb/internal	[no test files]

? github.com/influxdb/influxdb/uuid [no test files] bash circle-test.sh returned exit code 1`

I have no idea why we don't have any test files, and how the tests are setup. COuld you please help me to get past the tests?

**Comment by corylanou** [comment]
The tests were failing due to a known issue, not your code.  I re-ran the tests.  We still need to compile and run the tests on a windows box as well, as these tests don't do that.  I'll do that today.

**Comment by mvadu** [comment]
@corylanou  thank you!  I have it running in my Windows 10 64bit machine, its running well so far! I changed the config file to point to tsm engine `engine = "tsm1"`

**Comment by corylanou** [comment]
@mvadu I ran the test for just the tsm1 engine on a windows machine today and experienced some failures and a deadlock.

This is the command I ran:

```sh
go test ./tsdb/engine/tsm1
```

And got these failures, plus a timeout (assuming it was a deadlock)

````
--- FAIL: TestKeyIterator_TSM_MultipleKeysDeleted (0.02s)
        compact_test.go:290: key mismatch: got cpu,host=A#!~#count, exp cpu,host=B#!~#value
key 'cpu' exceeds max index entries: 65536 > 65535
--- FAIL: TestTSMReader_MMAP_Tombstone (0.01s)
        data_file_test.go:798: unexpected error deleting: rename C:\Users\CORY~1.LAN\AppData\Local\Temp\tsm1-test572759757\tombstone125365895 C:\Users\CORY~1.LAN\AppData\Local\Temp\tsm1-test572759757
tsm1test086396872.tombstone: The process cannot access the file because it is being used by another process.
--- FAIL: TestFileStore_Open_Deleted (0.02s)
        file_store_test.go:566: unexpected error deleting: rename C:\Users\CORY~1.LAN\AppData\Local\Temp\tsm1-test968533282\tombstone264989046 C:\Users\CORY~1.LAN\AppData\Local\Temp\tsm1-test96853328
\0000001.tombstone: The process cannot access the file because it is being used by another process.
```

**Comment by corylanou** [comment]
I'm curious if we are missing some locking based on what this project has done: https://github.com/edsrzf/mmap-go/blob/master/mmap_windows.go

**Comment by mvadu** [comment]
@corylanou most likely.. I thought the lock was not needed based on Bolt's implementation. Let me take a look today, and update PR.

**Comment by benbjohnson** [comment]
@corylanou Do you have a stack trace from a SIGQUIT on the deadlock?

**Comment by corylanou** [comment]
@benbjohnson I'm assuming it was a deadlock, the test timed out.  Here is a gist, the stack trace is at the bottom: https://gist.github.com/corylanou/e5e3d04e7cb13f6a862c

**Comment by benbjohnson** [comment]
@corylanou It looks like it's reading from the file in `goroutine 224`. It seems like it's just slow. Try adding logging to `tsm1.Engine.Write()` or `convertKeysAndWriteMetadata()` or `readCompressedFile()` to see how many times it executing.

Also, check the file size of the files being read. Maybe they're just really large? That doesn't seem likely though. Assuming you're running an SSD, I'd expect 6 - 12 GBs to be read over `1m`.

**Comment by corylanou** [comment]
This is on an older windows box.  Maybe I just need to give it more time due to the slow operating system :-).  I'll let you know what I find out.

The other tests are failing for sure though that I posted above, so the `mmap` implementation for windows may be the problem, not sure though.

**Comment by mvadu** [comment]
@corylanou  The timeout is not due to your slow box. I got 10min kill even on my 8core 12 GB RAM lappy. Even implementing a lock is not helping to resolve that timeout. 

I am trying with READ|WRITE access flags. It resolved the timeout issue, but still have few fails.

    [tsm1devwal] 2015/12/06 09:16:47 tsm1dev WAL starting with 10485760 segment size
    [tsm1devwal] 2015/12/06 09:16:47 tsm1dev WAL writing to C:\Users\Ady\AppData\Local\Temp\tsm1dev846761147\wal
    [tsm1dev] 2015/12/06 09:16:47 compacting 1 WAL segments, 0 TSM files
    [tsm1dev] 2015/12/06 09:16:47 error replacing new TSM files: CreateFileMapping: Access is denied.
    [tsm1devwal] 2015/12/06 09:16:47 tsm1dev WAL starting with 10485760 segment size
    [tsm1devwal] 2015/12/06 09:16:47 tsm1dev WAL writing to C:\Users\Ady\AppData\Local\Temp\tsm1dev003923166\wal
    [tsm1dev] 2015/12/06 09:16:47 compacting 1 WAL segments, 0 TSM files
    [tsm1dev] 2015/12/06 09:16:47 error replacing new TSM files: CreateFileMapping: Access is denied.
    --- FAIL: TestMergeIterator_TSM_Single (0.00s)
    panic: new reader: CreateFileMapping: Access is denied. [recovered]
    	panic: new reader: CreateFileMapping: Access is denied.
    
    goroutine 70 [running]:
    testing.tRunner.func1(0xc082122480)
    	c:/go/src/testing/testing.go:450 +0x178
    github.com/influxdb/influxdb/tsdb/engine/tsm1_test.MustTSMReader(0xc082232580, 0x32, 0xc082240300, 0xc082127dc0)
    	E:/goProjects/src/github.com/influxdb/influxdb/tsdb/engine/tsm1/compact_test.go:1868 +0xa83
    github.com/influxdb/influxdb/tsdb/engine/tsm1_test.TestMergeIterator_TSM_Single(0xc082122480)
    	E:/goProjects/src/github.com/influxdb/influxdb/tsdb/engine/tsm1/compact_test.go:518 +0x3d0
    testing.tRunner(0xc082122480, 0xe03108)
    	c:/go/src/testing/testing.go:456 +0x9f
    created by testing.RunTests
    	c:/go/src/testing/testing.go:561 +0x874
    
    goroutine 1 [chan receive]:
    testing.RunTests(0xc13e10, 0xe02c40, 0x9b, 0x9b, 0x1)
    	c:/go/src/testing/testing.go:562 +0x8b4
    testing.(*M).Run(0xc082087ee8, 0x4108b9)
    	c:/go/src/testing/testing.go:494 +0x77
    main.main()
    	github.com/influxdb/influxdb/tsdb/engine/tsm1/_test/_testmain.go:412 +0x11d
    
    goroutine 17 [syscall]:
    os/signal.loop()
    	c:/go/src/os/signal/signal_unix.go:22 +0x1f
    created by os/signal.init.1
    	c:/go/src/os/signal/signal_unix.go:28 +0x3e
    
    goroutine 29 [sleep]:
    time.Sleep(0x3b9aca00)
    	c:/go/src/runtime/time.go:59 +0x107
    github.com/influxdb/influxdb/tsdb/engine/tsm1.(*DevEngine).compact(0xc082104d90)
    	E:/goProjects/src/github.com/influxdb/influxdb/tsdb/engine/tsm1/engine.go:258 +0x948
    created by github.com/influxdb/influxdb/tsdb/engine/tsm1.(*DevEngine).Open
    	E:/goProjects/src/github.com/influxdb/influxdb/tsdb/engine/tsm1/engine.go:110 +0x161
    
    goroutine 6 [sleep]:
    time.Sleep(0x3b9aca00)
    	c:/go/src/runtime/time.go:59 +0x107
    github.com/influxdb/influxdb/tsdb/engine/tsm1.(*DevEngine).compact(0xc082105c00)
    	E:/goProjects/src/github.com/influxdb/influxdb/tsdb/engine/tsm1/engine.go:258 +0x948
    created by github.com/influxdb/influxdb/tsdb/engine/tsm1.(*DevEngine).Open
    	E:/goProjects/src/github.com/influxdb/influxdb/tsdb/engine/tsm1/engine.go:110 +0x161
    FAIL	github.com/influxdb/influxdb/tsdb/engine/tsm1	0.402s

**Comment by mvadu** [comment]
@corylanou The timeout is not due to your slow box. I got 10min kill even on my 8core 12 GB RAM laptop. I think it was due to closing the file handle in mmap itself. Now I changed that logic to math what is done in https://github.com/edsrzf/mmap-go/blob/master/mmap_windows.go, to keep the handle open.

It resolved the timeout issue, but the other errors are still out there.

Note: The Lock and Unlock in the code you linked is using [VirtualLock] (https://msdn.microsoft.com/en-us/library/windows/desktop/aa366895(v=vs.85).aspx) Windows API, which basically move all pages into memory to avoid the page faults. Its not a traditional process level lock.

**Comment by mvadu** [comment]
@corylanou I know the problem for the failures. In windows when a normal file is memory mapped, its treated as "In Use", hence its not allowed to be renamed. The file should be opened with `FILE_SHARE_DELETE` in Syscall.Open. I am trying with opening a  new handle  with this flag and use it in the mmap.

**Comment by mvadu** [comment]
@corylanou @otoolep I learnt the hard way that implementing mmap alone will not make tsm1 work in windows. The whole renaming while file is in use (part of compact cycle) is a killer. Windows does not like it. 
For now I have submitted #5070 which will at least allow the build to go smoothly on Windows.

**Comment by mvadu** [comment]
[gotest.txt](https://github.com/influxdb/influxdb/files/57280/gotest.txt)
Todays update was done using latest head (v0.9.6 release) from master, and my changes to mmap_windows.go. Its still fails with many rename related errors. Attached is output from `go test -v ./tsdb/engine/tsm1 > %temp%\gotest.txt 2>&1`

**Comment by jwilder** [comment]
@mvadu Something is off with that output.  It has log messages for code that has been removed in 0.9.6.  Are you sure you compiled against latest master?  For example, `TestEngine_RewriteFileAndCompact` no longer exists as a test anymore, but it's showing as failed in the output.

**Comment by mvadu** [comment]
Sorry!! I think I messed up somewhere with pulls. Did a fresh start today, and now have only one failure

    --- FAIL: TestCompactor_Compact (0.00s)
    panic: create tsm file: rename C:\Users\Ady\AppData\Local\Temp\tsm1-test320137733\tsm1test055545248 C:\Users\Ady\AppData\Local\Temp\tsm1-test320137733\000000001-000000001.tsm: The process cannot access the file because it is being used by another process. [recovered]
    	panic: create tsm file: rename C:\Users\Ady\AppData\Local\Temp\tsm1-test320137733\tsm1test055545248 C:\Users\Ady\AppData\Local\Temp\tsm1-test320137733\000000001-000000001.tsm: The process cannot access the file because it is being used by another process.
    FAIL	github.com/influxdb/influxdb/tsdb/engine/tsm1	0.804s

**Comment by mvadu** [comment]
The problem is in compact_test.go, MustWriteTSM test, when rename is called its still in use, and closing it before rename makes it fail later in write TSM value stage.

    f := MustTempFile(dir)
    newName := filepath.Join(filepath.Dir(f.Name()), tsmFileName(gen))
    if err := os.Rename(f.Name(), newName); err != nil {
    	panic(fmt.Sprintf("create tsm file: %v", err))
    }

**Comment by mvadu** [comment]
@jwilder @corylanou could you please take a look at this one last failure? If that test can be changed (or ignored for now :)) we can have a Windows build.

**Comment by jwilder** [comment]
@mvadu Can you rebase after #5165 is merged? Should resolve the file rename issue you're seeing.

**Comment by jwilder** [comment]
Actually, rebasing now would be fine as well.

**Comment by jwilder** [comment]
The `influx_inspect.exe` error is because you need to use the `dumptsmdev` command w/ the updated code.

**Comment by mvadu** [comment]
@jwilder Thank you!! Finally I can continue using latest Influx code for my Windows project.. 
and sorry for bugging @pauldix on twitter ☻Trying to run tests again..

**Comment by mvadu** [comment]
Now its complaining about file already present.. something is wrong with windows.. Not sure where it is getting that file, when in theory its a new file name.

    --- FAIL: TestTSMKeyIterator_Duplicate (0.00s)
    panic: create tsm file: rename C:\Users\Ady\AppData\Local\Temp\tsm1-test675501547\tsm1test251674453 C:\Users\Ady\AppData\Local\Temp\tsm1-test675501547\000000001-000000001.tsm: Cannot create a file when that file already exists. [recovered]
    	panic: create tsm file: rename C:\Users\Ady\AppData\Local\Temp\tsm1-test675501547\tsm1test251674453 C:\Users\Ady\AppData\Local\Temp\tsm1-test675501547\000000001-000000001.tsm: Cannot create a file when that file already exists.

**Comment by jwilder** [comment]
Hmm.  Are you running tests in parallel?

**Comment by mvadu** [comment]
Nope, I just have `goProjects\src\github.com\influxdb\influxdb>go test -v ./tsdb/engine/tsm1 > %temp%\gotest.txt 2>&1`

Side note, my PR still has tsm1.go, which is no longer in master. I am trying to figure out how to get rid of it.

**Comment by mvadu** [comment]
Actually failing test is `TestTSMKeyIterator_Duplicate` and reading its description ` we replace the old TSM file with a new one and we crash just before deleting the old file.` makes me think the file may be from one of the previous tests?

**Comment by mvadu** [comment]
PR updated after re-baseline and only mmap_windows is changed from master now.

**Comment by jwilder** [comment]
@mvadu There is a bug in `TestTSMKeyIterator_Duplicate`.  Can you amend this PR with a commit with this diff:
```
diff --git a/tsdb/engine/tsm1/compact_test.go b/tsdb/engine/tsm1/compact_test.go
index 0425552..594bf2d 100644
--- a/tsdb/engine/tsm1/compact_test.go
+++ b/tsdb/engine/tsm1/compact_test.go
@@ -385,7 +385,7 @@ func TestTSMKeyIterator_Duplicate(t *testing.T) {
                "cpu,host=A#!~#value": []tsm1.Value{v2},
        }

-       r2 := MustTSMReader(dir, 1, writes2)
+       r2 := MustTSMReader(dir, 2, writes2)

        iter, err := tsm1.NewTSMKeyIterator(1, r1, r2)
        if err != nil {
```

**Comment by jwilder** [comment]
@mvadu It looks like there are other failures on windows that are more involved to fix.  I'm going to merge this PR as is since it addresses the mmap issues on windows, but it looks like TSM on windows is still not fully functional for now.

**Comment by mvadu** [comment]
Sure thing @jwilder , I will work towards new PR to address remaining quirks on Windows. Happy holidays!

**Pull request merged**
