### PR TITLE
add windows support for tsm

### PR DESCRIPTION
**Pull request by runner-mei**

### CODE REVIEW

**Comment by corylanou** [comment]
Getting an error on compact: https://gist.github.com/corylanou/db19f536fe552f56a9c2

**Comment by jwilder** [comment]
@corylanou I think PR was updated to fix the tests.  Can you take a look again?

**Comment by runner-mei** [comment]
Ooo,bug is not fix. I will fix it after tsm is stable.

**Comment by runner-mei** [comment]
#4358 is better

**Pull request closed without merging**
