### PR TITLE
Move CLI stuff out of main package for increased testability.

### PR DESCRIPTION
**Pull request by pires**
- [ ] CHANGELOG.md updated
- [x] Rebased/mergable
- [x] Tests pass
- [x] Sign CLA (if not already signed)

Refs #2313

### CODE REVIEW

**Comment by corylanou** [comment]
I think I would move even more out of the main package yet.  I would try to keep only the usage and flag parsing there: https://github.com/pires/influxdb/blob/2313-cli_refactor/cmd/influx/main.go#L41-L105

Then you may want to introduce concepts like `New` and `Run` to create a new instance of the cli and then call `Run` once you want it to kick off.

This will allow for even more testing, as well as refactoring in the future.  Currently, the main is resonsible for way to many things.

Thoughts?

**Comment by pires** [comment]
I tried to keep it simple by moving only what is being tested right now. I can however follow your idea if otherwise means this won't get merged as is.

**Comment by corylanou** [comment]
I'm fine with incremental progress.  We can open another issue to have someone refactor even further.  Thanks! +1

**Comment by pires** [comment]
@corynalou I'd make it part of the CLI refactoring.

**Comment by pires** [comment]
@corylanou I'd make it part of the CLI refactoring. Can you create an issue for that please? I'll link all the related issues, PRs and notes related to it.

**Comment by pires** [comment]
@corylanou I've addressed your comments above and adopted `New` and `Run`. Also, rebased to latest `master`. Care to review?

**Comment by corylanou** [comment]
Looks like your build failed.  Can you fix and push back up before I review?  Thanks!

**Comment by pires** [comment]
@corylanou can't see what the error is exactly.

```
go test ./cmd/influx/cli
ok  	github.com/influxdb/influxdb/cmd/influx/cli	0.014s
```

There are no pending pushes.

**Comment by corylanou** [comment]
```
cmd/influx/main_test.go:16: undefined: main.CommandLine
cmd/influx/main_test.go:50: undefined: main.CommandLine
cmd/influx/main_test.go:73: undefined: main.CommandLine
cmd/influx/main_test.go:89: undefined: main.CommandLine
cmd/influx/main_test.go:108: undefined: main.CommandLine
cmd/influx/main_test.go:133: undefined: main.CommandLine
cmd/influx/main_test.go:171: undefined: main.CommandLine
cmd/influx/main_test.go:208: undefined: main.CommandLine
cmd/influx/main_test.go:260: undefined: main.CommandLine
```

Perhaps a file didn't get checked in?

**Comment by pires** [comment]
@corylanou nevermind, `cmd/influx/main_test.go` was not deleted and CCI was trying to run it. Pushed fix.

**Comment by pires** [comment]
@corylanou all green now.

**Comment by corylanou** [comment]
Looks great.  This should allow a lot more testing/refactoring going forward.  Thanks! +1

**Comment by otoolep** [comment]
+1

Merging now.

**Comment by otoolep** [comment]
Thanks @pires

**Comment by pires** [comment]
Thank you! Will look for a CLI refactoring plan and nag you about it soon.

**Pull request merged**
