### PR TITLE
allow specifying field name in graphite template

### PR DESCRIPTION
**Pull request by roobert**
Initial attempt at implementing this: https://github.com/influxdb/influxdb/issues/4176

I'd like some feedback on how this should be implemented, primarily:

* should multiple `field` tags be allowed, in the same way as the `measurement` tag is?
* is something like this valid: `mytag.measurement*.field`
* should `field*` be implemented

I also obviously need to add some tests but thought I'd try and get a discussion going on implementation first..

### CODE REVIEW

**Comment by otoolep** [comment]
Thanks @roobert -- test failures can be seen here:

https://circleci.com/gh/influxdb/influxdb/6023

**Comment by roobert** [comment]
@otoolep - thanks, any comments on my original post?

**Comment by roobert** [comment]
@otoolep: I think this is ready to be merged, is there anything else I need to do?

I've added tests, signed the CLA, and updated the graphite listener `README.md`.

This patch doesn't change any existing functionality and doesn't modify the default behaviour of the graphite listener.

We've been running this in production for 4 days and all seems good so far with ~40,000 points a second.

**Comment by otoolep** [comment]
cc @jwilder

**Comment by jwilder** [comment]
Looks good @roobert! :+1:

**Comment by roobert** [comment]
@otoolep @jwilder, cheers peeps, when can this be merged?

**Comment by roobert** [comment]
@sparrc - you seem to be working on the graphite parser, is this something you could look into merging?

Cheers,

**Comment by sparrc** [comment]
@roobert, looks good, thank you, I can merge this

**Comment by otoolep** [comment]
+1, thanks @roobert

**Comment by roobert** [comment]
:+1: thanks for this!

**Pull request merged**
