### PR TITLE
Disable HintedHandoff if configuration is not set. #4283

### PR DESCRIPTION
**Pull request by ch33hau**
- [x] CHANGELOG.md updated
- [x] Rebased/mergable
- [x] Tests pass
- [x] Sign [CLA](http://influxdb.com/community/cla.html) (if not already signed)

Hi, I have created a pull request for https://github.com/influxdb/influxdb/issues/4283.

### CODE REVIEW

**Comment by corylanou** [comment]
This looks good.  However, if we are changing the config here to be `disabled` by default, we need to update the `DemoConfig` to turn it on here:

https://github.com/influxdb/influxdb/blob/master/cmd/influxd/run/config.go#L101

```go
c.HintedHandoff.Enabled = true
```

**Comment by otoolep** [comment]
Not sure about this. Since HH is on by default, with no config section,
shouldn't it still be on?

**Comment by ch33hau** [comment]
@corylanou ok, sure
@otoolep Previously yes, it still cause the Dir validation failed. So after this fixes, **enabled** will be false if no config section or we set it to false.

**Comment by corylanou** [comment]
@otoolep We ship everything with a sane config, including running in demo mode with it turned on.  The only way for HH to be turned off is by the end user removing the config for it.  We have other sections that work the same way.  Thoughts?

**Comment by otoolep** [comment]
OK, I checked https://github.com/influxdb/influxdb/blob/master/etc/config.sample.toml#L99 and we have not been giving the impression that HH is on by default. So I'm OK with this change.

I was concerned that HH was documented as on by default in the sample config, and then this could be considered a breaking change. This is not the case, and I actually agree it is more natural if the section is not there, one shouldn't be surprised if HH is not on.

**Comment by otoolep** [comment]
+1 from me.

@corylanou if +1 from, please merge too.

Thanks @ch33hau

**Comment by corylanou** [comment]
+1

**Comment by ch33hau** [comment]
Thanks for review and comments @otoolep @corylanou !

**Pull request merged**
