### PR TITLE
V08.8.9 - Export Data

### PR DESCRIPTION
**Pull request by corylanou**
This PR will address issue https://github.com/influxdb/influxdb/issues/2378

## Design

This is phase 1 of 2.  This is the `export` function that users of `0.8` need to upgrade to.

Phase one exports raw data from `0.8` to a flat file in `line protocol'ish` format.  You will specify a database and shard group when you export.  This will be done from the `0.8.9` branch that users will have to upgrade to.

To list out your shards, use the following http endpoint:

`/cluster/shard_spaces`

Then, to export a database with then name "metrics" and a shard space with the name "default", issue the following curl command:

```sh
curl -o export http://username:password@http://localhost:8086/export/metrics/default
```

Compression is supported, and will result in a significantly smaller file size.  Use the following command for compression:

```sh
curl -o export.gz --compressed http://username:password@http://localhost:8086/export/metrics/default
```

## Assumptions

Schema Migration

- Database name will map directly from `0.8` to `0.9`
- Shard Space to Retention Policy mapping
    - Shard Space Duration is ignored, as in `0.9` we determine shard size
    - Regex is used to match the correct series names and only exports that data for the database
    - Duration becomes the new Retention Policy duration

- Users - Not migrating due to inability to get passwords.  Anyone using users will need to manually set these back up in `0.9`

### CODE REVIEW

**Comment by otoolep** [comment]
@corylanou -- when you say 0.8.9 will export the data, where will it write that data. How would I actually tell 0.8.9 to start the export? How will I know if it is successful?

**Comment by corylanou** [comment]
@otoolep it will export the data to a flat file.  Not sure of the format yet, but first pass is likely a compressed text.  I'm open to suggestions.  

You will start the old `0.8` daemon with an `-export` flag and likely some new arguments as well.

It will know if it's successful if it doesn't error out while exporting :-).  Short of re-reading the file and comparing it to the data that you just exported I'm not sure how else you would know it worked.  I'll have to write tests of course to make sure it does what it says it does.  Ultimately the real test will be with some large production data sets and comparing some large aggregate numbers once they are in the new system.

**Comment by corylanou** [comment]
Also, the reason for the intermediary step on transforming is so that the community can help if needed to get it tweaked just right.  This allows for contributions without the need for legacy setup.

**Comment by otoolep** [comment]
As for knowing it worked, my question was more about operationally. Log messages complaining about problems, error return codes to the user, etc. Assuming the user got none of that, then he can be sure the data is ready for import into an 0.9 system. 

My question wasn't about how you'll know the code is correct. You'll test it. :-)

I guess this is all tied up in how the user triggers the export. I'd imagine they'll want to work like this:

-- install 0.8.9.
--  bounce their nodes.
-- let everyone who is using InfluxDB continue to work as normal.
-- at a time of their choosing trigger an export. This might happen quite a bit later after installing 0.8.9. Who knows?

This is why I think an endpoint or query command might be a better approach. If it's a command-line option, when does the export take place? Immediately on start? And if it fails, how would try again without restarting InfluxDB?

**Comment by corylanou** [comment]
@otoolep Good point on the endpoint.  That may be the better approach.

**Comment by otoolep** [comment]
Also, some people (not sure how many) will be running clusters. They may do a rolling upgrade, and you can't have the export start every time a node starts. So separating the upgrade-and-restart from the export-start is probably best.

**Comment by beckettsean** [comment]
+1 for separating the upgrade/daemon bounce from the initiation of the export.

Should we add an option or a requirement to freeze writes during export? If not, how can I be certain what data is in the export and what isn't? I don't see any discussion of an incremental export, so I'm always grabbing at least an entire shard group. If that group is hot for writes that seems to lead to indeterminate behavior. 

Assuming I can't export a group that's hot for writes is this my actual upgrade path:
 - Export cold shard group data (and hope I have no historical writes happening)
 - import cold data into 0.9.0
 - redirect writes from 0.8.9 to 0.9.0
 - when 0.8.9 is no longer receiving writes, do a final export and import

We're supplying explicit timestamps with the import so duplicate points will be silently over-written, meaning there would be no data duplication.

**Comment by corylanou** [comment]
@pauldix @beckettsean brings up a good point about blocking writes.  Do you want this to be an option, or are we going to leave it to them to stop writing if they want a deterministic backup?  Or, do we want them to be able to specify a time range as well?

@beckettsean you are correct that duplicate timestamps will overwrite when importing.  I think as long as we make this clear we should be ok

**Comment by pauldix** [comment]
I think writes to the 0.8 server shouldn't be available. Basically, they
should migrate their stuff over to a new 0.9 installation, then run this to
pull all the historical data out of their old 0.8 installation and write it
into the new server.

**Comment by NickPadilla** [comment]
Hello All,

Any updates on this issue?  I'd really, really, like to upgrade to 0.9.1 - for the CQ updates.  Please advise.

**Comment by corylanou** [comment]
@NickPadilla This is my top priority right now and all of my daily efforts are on it.  I'm hoping to have some basic "dump" done in the next day or so.  I'll keep you posted.

**Comment by NickPadilla** [comment]
Hey @corylanou -- YAY! Awesome, love what you guys have going on!

**Comment by pauldix** [comment]
This shouldn't be getting merged into the 0.8.8 branch. Should go into a v0.8.9 branch. 

@corylanou I can't tell from looking at this if it streams the results out. What happens if you have a single series with many millions of points?

I also don't see the get shard spaces endpoint that you describe at the top of the PR. Changed?

**Comment by corylanou** [comment]
@pauldix Correct, I'll have to create another PR to leave it on it's own branch.  All the discussion started here after I realized I improperly created the PR.

I can have it stream like we do with chunked writer regardless of what they specify, or do you want them to explicitly specify chunked?

This is the endpoint you couldn't find: https://github.com/influxdb/influxdb/blob/v08.8.9/api/http/api.go#L159

**Comment by pauldix** [comment]
I think it should always chunk, otherwise it's almost guaranteed to fill up memory and die for any decent size db. Will curl work ok with the chunked stuff?

**Comment by corylanou** [comment]
curl will work with chunked it just doesn't update the status bar for download progress.

**Comment by corylanou** [comment]
Closing in favor of https://github.com/influxdb/influxdb/pull/3477

**Pull request closed without merging**
