### PR TITLE
Change "code.google.com/p/go.*" to "golang.org/x/*"

### PR DESCRIPTION
**Pull request by toddboom**
Cleaning up the old format for external subrepos:

https://groups.google.com/forum/#!msg/golang-nuts/eD8dh3T9yyA/l5Ail-xfMiAJ

### CODE REVIEW

**Comment by otoolep** [comment]
+1 on green build.

**Comment by corylanou** [comment]
When I search the project I come up with this:

```
  1 cmd/influxd/noprofile.go|11 col 7| log "code.google.com/p/log4go"                                                                                                                                                                                                          
  2 cmd/influxd/profile.go|22 col 7| log "code.google.com/p/log4go"                                                                                                                                                                                                            
  3 cmd/influxd/syslog.go|10 col 7| log "code.google.com/p/log4go"                                                                                                                                                                                                             
  4 httpd/handler.go|16 col 3| "code.google.com/p/go-uuid/uuid"                                                                                                                                                                                                                
  5 server.go|21 col 3| "code.google.com/p/go.crypto/bcrypt"                                                                                                                                                                                                                   
  6 server_test.go|14 col 3| "code.google.com/p/go.crypto/bcrypt"                                                                                                                                                                                                              
  7 util.go|6 col 3| "code.google.com/p/log4go"  
```

Some of those should just be replaced with the standard logger.

I couldn't get uuid to fetch from golang.org, so not sure what is going on with that.

**Comment by toddboom** [comment]
I don't think log4go is included in the same sweeping change, at least not according to the post on the mailing list. Should those all get changed as well?

**Comment by corylanou** [comment]
Changing out log4go is probably a different PR.  We don't use it (and probably shouldn't) in the 0.9.  I change it out any time I encounter a file I am working on.

**Comment by toddboom** [comment]
@corylanou If this is good to go, I'll let you have the honor of merging it in.

**Comment by toddboom** [comment]
@corylanou any reason not to merge this in now?

**Comment by corylanou** [comment]
Don't see why not.  To smoke test it you could blow away your `$GOPATH/pkg` directory, check out that branch, do a go get and make sure it still builds.  If it does we should be fine.

**Pull request merged**
