### PR TITLE
Basic instrumentation for shards

### PR DESCRIPTION
**Pull request by otoolep**
Example:
```
name: shard
tags: engine=bz1, id=2, path=/home/philip/.influxdb/data/graphite/default/2
series_create   write_points_ok write_req
-------------   --------------- ---------
1               178518          179
```

### CODE REVIEW

**Comment by otoolep** [comment]
I don't know why `statWriteBytes` is not getting set, perhaps a bug in the engine.

**Comment by otoolep** [comment]
@benbjohnson @jwilder

**Comment by otoolep** [comment]
And within the database `_internal`:
```
> select * from shard
name: shard
-----------
time                            engine  id      path                                            series_create   write_points_ok write_req
2015-09-04T22:43:45.564960647Z  bz1     2       /home/philip/.influxdb/data/graphite/default/2  1               178518          179
```

**Comment by otoolep** [comment]
@benbjohnson @jwilder

**Comment by corylanou** [comment]
+1

**Pull request merged**
