### PR TITLE
Don't panic if getting current use fails

### PR DESCRIPTION
**Pull request by otoolep**

### CODE REVIEW

**Comment by otoolep** [comment]
```
[srvr] 2015/03/20 15:20:32 No config provided, using default settings
[srvr] 2015/03/20 15:20:32 failed to generate default config: failed to determine current user for storage. Please supply an explicit configuration file
```

**Comment by otoolep** [comment]
@corylanou @dgnorton

**Comment by otoolep** [comment]
This is the best we can do. In this corner case the user must supply an explicit config.

**Comment by corylanou** [comment]
+1

**Comment by otoolep** [comment]
Thanks @corylanou -- I think this is a decent solution.

**Pull request merged**
