### PR TITLE
Enable file logging

### PR DESCRIPTION
**Pull request by otoolep**

### CODE REVIEW

**Comment by otoolep** [comment]
Still WIP, need to configure logging of lower-level packages.

**Comment by pauldix** [comment]
good enough for now. :shipit:

**Comment by otoolep** [comment]
Ready to go now.

**Comment by otoolep** [comment]
Green build, merging now.

**Comment by daviesalex** [comment]
This would appear to have been removed with the commit below. For users of systemd, the 'only log to stderr' isnt ideal, as it is fairly tedious to get this into a different file without mixing it up with other services. Could logging directly to a file be reconsidered for merge? We were about to start to patch this ourselves, but found this and thought we would ask first if there is some reason that this is a terrible idea, or if there is some approach other than that followed here that we should follow to achieve this...

commit c461c7e7b4cd5b5ed99cf06dc601e1b2453bf3ad
Author: Philip O'Toole <philip.otoole@yahoo.com>
Date:   Wed Mar 25 17:40:18 2015 -0700

    Remove logging to specific file

**Comment by otoolep** [comment]
@daviesalex -- we went back and forth on this, for some time. It turns out that most sys admins want complete control over logging, and therefore want the logs to `stderr`. This allows them to direct the logs to a place of their choosing. I presume this is why the standard target for logs in the Go standard libary is also `stderr`.

Have you see this page?

    https://influxdb.com/docs/v0.9/concepts/logs.html

By creating the right files in `/etc/influxdb` you can send the log output to whatever file you want, *without* patching the code.

**Comment by daviesalex** [comment]
@otoolep - understood, although from our perspective this means that we have to have systemd manage a shell script and that then forks influx which feels wrong... and does not work with the unit file for systemd which influx provide (which calls influxd directly).

**Pull request merged**
