### PR TITLE
fix config directory (/etc/opt/influxdb -> /etc/influxdb) & data directory (/var/opt/influxdb -> /var/lib/influxdb)

### PR DESCRIPTION
**Pull request by blufor**
This has been bugging me for some while now, here's the fix to make directory locations a bit more sane ;)

### CODE REVIEW

**Comment by otoolep** [comment]
We may revisit this paths, but if you read the *standard* you will see this paths are correct.

http://www.pathname.com/fhs/pub/fhs-2.3.pdf

**Comment by otoolep** [comment]
To be clear, we're still investigating canonical examples for how to lay out the files, but we started by following the FHS standard.

**Comment by beckettsean** [comment]
@blufor thank you for your PR, we are in the process of revisiting our packaging setup. Many users have deploy code that relies on the current settings, so we cannot simply change them out from underneath everyone without warning or mitigations. 

+ cc @rossmcdonald for context

**Comment by blufor** [comment]
@otoolep you're right, FHS really says that, but in my 10+ years of system administration, I've never seen a single occurrence of this directory ;) It might be a good idea, but it simply hasn't caught on. Actually I'd turn the current state the other way around and the final solution should place the key directories into standard paths (```/usr/bin```, ```/etc```, ```/var/lib```, ...) simply because in the end the software is installed via a system's package manager (except the .tar archive). ```/opt``` directory is usually used for software installed in some other way (although again, ```make``` is one of the exceptions).

Don't take this as me putting pressure on you, I don't mean that. It's rather my OCD regarding my systems ;)

**Pull request closed without merging**
