### PR TITLE
fix #1764: panic index out of range

### LINKED ISSUE #1764: panic 'index out of range'
This works:

```
select * from cpu.user_perc where region='dev02' and hostname='dev02-keystone-001'
```

```
name        tags    time            value
----        ----    ----            -----
cpu.user_perc        2015-02-25T19:57:07Z    17.5
cpu.user_perc        2015-02-25T19:57:08Z    508
cpu.user_perc        2015-02-25T19:57:23Z    20.3
cpu.user_perc        2015-02-25T19:57:24Z    60
cpu.user_perc        2015-02-25T19:57:39Z    22.7
cpu.user_perc        2015-02-25T19:57:40Z    44
cpu.user_perc        2015-02-25T19:57:56Z    21.6
```

But add another tag qualifier:

```
select * from cpu.user_perc where region='dev02' and tenant_id='17a5929e6f15404b83413e2a4862ba09' and hostname='dev02-monasca-001'
```

```
[srvr] 2015/02/26 20:21:26 http: panic serving 127.0.0.1:33597: runtime error: index out of range
goroutine 398432 [running]:
net/http.func·011()
        /root/.gvm/gos/go1.4/src/net/http/server.go:1130 +0xbb
github.com/influxdb/influxdb.seriesIDs.intersect(0xc208162ef0, 0x4, 0x4, 0xc20808cf80, 0x2, 0x2, 0x0, 0x0, 0x0)
        /root/.gvm/pkgsets/go1.4/global/src/github.com/influxdb/influxdb/database.go:934 +0x29a
github.com/influxdb/influxdb.(*Measurement).walkWhereForSeriesIds(0xc2080c31a0, 0x7fda4694b518, 0xc20818e9f0, 0xc20818ea50, 0x0, 0x0, 0x0, 0xd, 0x0, 0x0)
        /root/.gvm/pkgsets/go1.4/global/src/github.com/influxdb/influxdb/database.go:388 +0x330
github.com/influxdb/influxdb.(*Measurement).seriesIDsAndFilters(0xc2080c31a0, 0xc20817a750, 0x0, 0x0, 0x0, 0x416218)
        /root/.gvm/pkgsets/go1.4/global/src/github.com/influxdb/influxdb/database.go:282 +0xd5
github.com/influxdb/influxdb.(*Measurement).tagSets(0xc2080c31a0, 0xc20817a750, 0x0, 0x0, 0x0, 0x0)
        /root/.gvm/pkgsets/go1.4/global/src/github.com/influxdb/influxdb/database.go:299 +0x43
github.com/influxdb/influxdb.(*tx).CreateIterators(0xc208401620, 0xc20817a750, 0x0, 0x0, 0x0, 0x0, 0x0)
        /root/.gvm/pkgsets/go1.4/global/src/github.com/influxdb/influxdb/tx.go:136 +0xab1
github.com/influxdb/influxdb/influxql.(*Planner).planRawQuery(0xc20816fca0, 0xc20800ae60, 0xc208162e60, 0x0, 0x0, 0x0, 0x0)
        /root/.gvm/pkgsets/go1.4/global/src/github.com/influxdb/influxdb/influxql/engine.go:151 +0x9a
github.com/influxdb/influxdb/influxql.(*Planner).Plan(0xc20816fca0, 0xc20817a750, 0xc2080349c0, 0x0, 0x0)
        /root/.gvm/pkgsets/go1.4/global/src/github.com/influxdb/influxdb/influxql/engine.go:99 +0x4ab
github.com/influxdb/influxdb.(*Server).planSelectStatement(0xc2080349c0, 0xc20817a630, 0x0, 0x0, 0x0)
        /root/.gvm/pkgsets/go1.4/global/src/github.com/influxdb/influxdb/server.go:1850 +0x13a
github.com/influxdb/influxdb.(*Server).executeSelectStatement(0xc2080349c0, 0xc20817a630, 0xc20808e00e, 0x3, 0xc208175d40, 0x0)
        /root/.gvm/pkgsets/go1.4/global/src/github.com/influxdb/influxdb/server.go:1788 +0xf2
github.com/influxdb/influxdb.(*Server).ExecuteQuery(0xc2080349c0, 0xc20816fa60, 0xc20808e00e, 0x3, 0xc208175d40, 0x0, 0x0, 0x0, 0x0, 0x0)
        /root/.gvm/pkgsets/go1.4/global/src/github.com/influxdb/influxdb/server.go:1715 +0x9da
github.com/influxdb/influxdb/httpd.(*Handler).serveQuery(0xc208175f20, 0x7fda469433a0, 0xc20816f760, 0xc2081bdd40, 0xc208175d40)
        /root/.gvm/pkgsets/go1.4/global/src/github.com/influxdb/influxdb/httpd/handler.go:162 +0x36e
github.com/influxdb/influxdb/httpd.*Handler.(github.com/influxdb/influxdb/httpd.serveQuery)·fm(0x7fda469433a0, 0xc20816f760, 0xc2081bdd40, 0xc208175d40)
        /root/.gvm/pkgsets/go1.4/global/src/github.com/influxdb/influxdb/httpd/handler.go:61 +0x4f
github.com/influxdb/influxdb/httpd.func·003(0x7fda469433a0, 0xc20816f760, 0xc2081bdd40)
        /root/.gvm/pkgsets/go1.4/global/src/github.com/influxdb/influxdb/httpd/handler.go:506 +0x2a3
net/http.HandlerFunc.ServeHTTP(0xc2080b6760, 0x7fda469433a0, 0xc20816f760, 0xc2081bdd40)
        /root/.gvm/gos/go1.4/src/net/http/server.go:1265 +0x41
github.com/influxdb/influxdb/httpd.func·004(0x7fda46942410, 0xc20816f620, 0xc2081bdd40)
        /root/.gvm/pkgsets/go1.4/global/src/github.com/influxdb/influxdb/httpd/handler.go:530 +0x288
net/http.HandlerFunc.ServeHTTP(0xc20817c6e0, 0x7fda46942410, 0xc20816f620, 0xc2081bdd40)
        /root/.gvm/gos/go1.4/src/net/http/server.go:1265 +0x41
github.com/influxdb/influxdb/httpd.func·005(0x7fda46942410, 0xc20816f620, 0xc2081bdd40)
        /root/.gvm/pkgsets/go1.4/global/src/github.com/influxdb/influxdb/httpd/handler.go:539 +0xb0
net/http.HandlerFunc.ServeHTTP(0xc2080b67a0, 0x7fda46942410, 0xc20816f620, 0xc2081bdd40)
        /root/.gvm/gos/go1.4/src/net/http/server.go:1265 +0x41
github.com/influxdb/influxdb/httpd.func·006(0x7fda46942410, 0xc20816f620, 0xc2081bdd40)
        /root/.gvm/pkgsets/go1.4/global/src/github.com/influxdb/influxdb/httpd/handler.go:572 +0x31a
```

### PR DESCRIPTION
**Pull request by dgnorton**
This turned out to be a regression.  Added tests around all of the seriesIDs set methods.

### CODE REVIEW

**Comment by otoolep** [comment]
A refactor of our code a while back removed a bunch of code, including this fix, that we had already merged:

https://github.com/influxdb/influxdb/pull/1354/files

**Comment by otoolep** [comment]
+1

@dgnorton -- did you ever remove that rogue type in `server.go`? We spoke about it, if you remember. I was waiting for that to add a bunch more other tests we were inadvertently removed too.

**Comment by dgnorton** [comment]
@otoolep yes, removed the other `SeriesIDs` type in commit 9bff9cd

**Comment by pauldix** [comment]
lgtm, :shipit:

**Pull request merged**
