### PR TITLE
Explicitly install Go 1.4.2 on CircleCI

### PR DESCRIPTION
**Pull request by toddboom**

### CODE REVIEW

**Comment by otoolep** [comment]
Any particular reason?

**Comment by otoolep** [comment]
Should we update CONTRIBUTING.md?

**Comment by toddboom** [comment]
@otoolep i wasn't sure if it made a difference, but wanted to check. what do you think? i thought that maybe if we were installing 1.4.0, it might explain some inconsistencies

**Comment by toddboom** [comment]
Also, I think we can pass `--binary` at the end of the `gvm install` command to skip compilation and download the packages directly.

**Comment by marcosnils** [comment]
@toddboom @otoolep I'm wondering why you were installing 1.4 in the very beginning. Circleci containers already have golang 1.4 installed in their system. 

Why don't we ask the circleci guys if they're planning to update to 1.4.2 soon?.

**Comment by toddboom** [comment]
@marcosnils we were trying to do some build isolation by installing our own version of Go

**Comment by marcosnils** [comment]
By build isolation you refer to a script which anyone can run and it will work magically?

**Comment by otoolep** [comment]
@marcosnils -- to ensure we fully understand our CI process, we prefer to have complete control.

**Comment by otoolep** [comment]
I don't have any objection upgrading to 1.4.2. I think it'll be very helpful if we also update `CONTRIBUTING.md` to say we required 1.4.2 or greater.

**Comment by marcosnils** [comment]
@otoolep @toddboom I see . The preparing process takes only 7 seconds so I guess it's ok to stick with a fixed version. 

:+1: to the PR.

**Comment by otoolep** [comment]
+1 from me. If you merge, I will update `CONTRIBUTING.md` and `package.sh`.

**Comment by toddboom** [comment]
@otoolep merged, thanks!

**Pull request merged**
