### PR TITLE
Add tests for REGEX operators

### PR DESCRIPTION
**Pull request by marcosnils**

### CODE REVIEW

**Comment by otoolep** [comment]
Thanks @marcosnils -- have you signed the CLA?

**Comment by marcosnils** [comment]
@otoolep just signed it :smile:

**Comment by otoolep** [comment]
I will look into the `go get` failures.

**Comment by otoolep** [comment]
Build script has been fixed, please rebase so CI testing can re-run.

**Comment by otoolep** [comment]
Thanks @marcosnils

**Pull request merged**
