### PR TITLE
use nil as default return value for MapCount

### LINKED ISSUE #2271: inconsistent results for aggregate queries
```sh
yesterday=$(date -v -1d '+%FT%T.000Z')

echo "creating database"
curl -G -ipv4 http://localhost:8086/query --data-urlencode "q=CREATE DATABASE foo"

echo "inserting data"
curl -d "{\"database\" : \"foo\", \"points\": [{\"name\": \"cpu\", \"tags\": {\"region\":\"uswest\",\"host\": \"server01\"},\"timestamp\": \"$yesterday\",\"fields\": {\"value\": 100}}]}" -H "Content-Type: application/json" -ipv4 http://localhost:8086/write

sleep 1

echo "querying data"
curl -G -ipv4 http://localhost:8086/query --data-urlencode "db=foo" --data-urlencode "q=select count(value) from cpu where time > now() - 2d group by time(6h)" --data-urlencode "pretty=true"
```

for some reason, the counts switch over to be `null` when i would have expected them to be `0` to be consistent with the earlier counts.

```json
{
    "results": [
        {
            "series": [
                {
                    "name": "cpu",
                    "columns": [
                        "time",
                        "count"
                    ],
                    "values": [
                        [
                            "2015-04-11T18:00:00Z",
                            0
                        ],
                        [
                            "2015-04-12T00:00:00Z",
                            0
                        ],
                        [
                            "2015-04-12T06:00:00Z",
                            0
                        ],
                        [
                            "2015-04-12T12:00:00Z",
                            1
                        ],
                        [
                            "2015-04-12T18:00:00Z",
                            null
                        ],
                        [
                            "2015-04-13T00:00:00Z",
                            null
                        ],
                        [
                            "2015-04-13T06:00:00Z",
                            null
                        ],
                        [
                            "2015-04-13T12:00:00Z",
                            null
                        ],
                        [
                            "2015-04-13T18:00:00Z",
                            null
                        ]
                    ]
                }
            ]
        }
    ]
}
```

### PR DESCRIPTION
**Pull request by neonstalwart**
this fixes #2271 and includes #2290

if someone could direct me where to put a test i'd be glad to try to add one

### CODE REVIEW

**Comment by otoolep** [comment]
@neonstalwart -- thanks. You should add a unit test to here:

https://github.com/influxdb/influxdb/blob/master/cmd/influxd/server_integration_test.go#L888

feel free to reset the database and write a little bit of data, then query it. Let me know if you have any questions.

**Comment by otoolep** [comment]
Once a unit test is added (I can add it if necessary), I test it by hand too, then we can merge this.

**Comment by neonstalwart** [comment]
ok, i'll take a shot at adding the unit test - i think it looks like something i can manage.  if you get impatient, go ahead with it yourself - it won't hurt my feelings

**Comment by otoolep** [comment]
Re-opened at the PR below, so I can debug the test failure.

https://github.com/influxdb/influxdb/pull/2295

**Pull request closed without merging**
