### PR TITLE
Fix style issues with else

### PR DESCRIPTION
**Pull request by LK4D4**
In go it's better to just continue flow without "else", if it is return in
"if" statement.

### CODE REVIEW

**Comment by otoolep** [comment]
Thanks @LK4D4 -- have you signed the CLA?

**Comment by LK4D4** [comment]
@otoolep Yup

**Comment by otoolep** [comment]
I'd like to hold off on this for now, as I am in the middle of a large, wide-ranging, change to the code, and I don't want to deal with conflicts. Soon, though, we can merge.

**Comment by otoolep** [comment]
Thanks @LK4D4 -- could you rebase?

**Comment by LK4D4** [comment]
@otoolep Of course, in a minute

**Comment by LK4D4** [comment]
@otoolep Done

**Comment by otoolep** [comment]
+1

**Comment by corylanou** [comment]
+1

**Comment by benbjohnson** [comment]
:+1:

**Comment by otoolep** [comment]
Thanks @LK4D4

**Pull request merged**
