### PR TITLE
Added simple comment for the Service struct for precreator so we pass…

### PR DESCRIPTION
**Pull request by orthogonous**
It was supposed to be a small PR but I ended up bundling a bunch of comment fixes for golint. ref #4098

golint also found an if block that had a redundant else statement given the parent block has an explicit return so I fixed that too.

### CODE REVIEW

**Comment by orthogonous** [comment]
From what I can tell from the circleci error it failed to download collectd.org data.

**Comment by otoolep** [comment]
Thanks @orthogonous -- can you please rebase against master and squash?

**Comment by otoolep** [comment]
For golint changes, a single commit is usually better.

**Comment by viru** [comment]
Also small comment on commit messages, first line should be in preset time and should fit into 50 characters (as described in this post http://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html).

**Comment by orthogonous** [comment]
@otoolep hello, I think I've fixed it but I couldn't squash it into 1 commit as I had a conflict. 

It looks like I needed to squash my stuff into one commit and have another merge commit for the conflict. I apologize if this is in error. I can drop this PR and redo if required

**Comment by otoolep** [comment]
At this stage it might be best to just open a new PR. We can't merge this one due to the commit history.

**Comment by otoolep** [comment]
Closing, please open a new PR and I will be happy to merge it.

**Pull request closed without merging**
