### PR TITLE
Ensure collectd uses defaults with partial config

### PR DESCRIPTION
**Pull request by otoolep**

### CODE REVIEW

**Comment by otoolep** [comment]
If collectd is supplied with an only partially completed config, defaults were not applied. This ensures defaults always take effect in that case.

Follow existing pattern, already in use with Graphite and openTSDB.

**Comment by otoolep** [comment]
@dgnorton

**Comment by dgnorton** [comment]
+1

**Comment by corylanou** [comment]
I think the better way to do this is set the defaults from NewConfig and then let it load in toml as expected.  This is how we handle it everywhere else I believe.  No need for a custom set of code.

Here is a good example of our pattern: https://github.com/influxdb/influxdb/blob/master/tsdb/config.go

**Comment by otoolep** [comment]
OK @corylanou - I certainly didn't like this pattern, but didn't of any other way. If there is a better alternative, great.

**Pull request merged**
