### PR TITLE
More stats and diags

### PR DESCRIPTION
**Pull request by otoolep**

### CODE REVIEW

**Comment by otoolep** [comment]
```
$ curl -G http://localhost:8086/query?pretty=true --data-urlencode "db=internal" --data-urlencode "q=SELECT * from server LIMIT 1" 
{
    "results": [
        {
            "series": [
                {
                    "name": "server",
                    "columns": [
                        "time",
                        "batchWriteRx",
                        "broadcastMessageRx",
                        "broadcastMessageTx",
                        "pointWriteRx",
                        "queriesExecuted",
                        "queriesRx",
                        "shardsCreated",
                        "writeSeriesMessageTx"
                    ],
                    "values": [
                        [
                            "2015-03-23T23:21:47.602825778Z",
                            null,
                            2,
                            2,
                            null,
                            null,
                            null,
                            null,
                            null
                        ]
                    ]
                }
            ]
        }
    ]
}
```

**Comment by otoolep** [comment]
```
curl -G http://localhost:8086/query?pretty=true --data-urlencode "db=internal" --data-urlencode "q=SHOW TAG KEYS"
{
    "results": [
        {
            "series": [
                {
                    "name": "server",
                    "columns": [
                        "tagKey"
                    ],
                    "values": [
                        [
                            "host"
                        ],
                        [
                            "serverID"
                        ],
                        [
                            "shardID"
                        ]
                    ]
                },
                {
                    "name": "shard",
                    "columns": [
                        "tagKey"
                    ],
                    "values": [
                        [
                            "host"
                        ],
                        [
                            "serverID"
                        ],
                        [
                            "shardID"
                        ]
                    ]
                }
            ]
        }
    ]
}
$ curl -G http://localhost:8086/query?pretty=true --data-urlencode "db=internal" --data-urlencode "q=SHOW TAG VALUES WITH key=serverID"
{
    "results": [
        {
            "series": [
                {
                    "name": "serverIDTagValues",
                    "columns": [
                        "serverID"
                    ],
                    "values": [
                        [
                            "1"
                        ]
                    ]
                }
            ]
        }
    ]
}~ $ curl -G http://localhost:8086/query?pretty=true --data-urlencode "db=internal" --data-urlencode "q=SHOW TAG VALUES WITH key=host"
{
    "results": [
        {
            "series": [
                {
                    "name": "hostTagValues",
                    "columns": [
                        "host"
                    ],
                    "values": [
                        [
                            "malthus"
                        ]
                    ]
                }
            ]
        }
    ]
}
```

**Comment by 121watts** [comment]
:shipit:

**Comment by mark-rushakoff** [comment]
LGTM :+1:

**Comment by otoolep** [comment]
Thanks @121watts, @mark-rushakoff  -- one minor issue about the tags, will fix that and then merge.

**Pull request merged**
