### PR TITLE
Move stress test logic into another file

### PR DESCRIPTION
**Pull request by mjdesa**
Previously, there were to things that happened in `main`.

1. It writes batches of points to an InfluxDB instance while keeping track of the total number of points that were written `totalPoints`, a slice of response times `responseTimes`, and the time the start started at `startTime`. 
2. Print out the results of the test that just ran.

The majority of the logic around (1) was pulled out into its own function `Run()` that returns `totalPoints`, `responseTimes`, and the start/end times as `timer`.

The intention is that `Run()` will be used as the basis for building a more comprehensive stress testing suite.

### CODE REVIEW

**Comment by mjdesa** [comment]
@pauldix @toddboom can I merge this?

**Comment by pauldix** [comment]
I think it should be changed so that all files are in the `influx_stress` package. `runner` doesn't really make sense as a package name and it just adds more complication to have the source buried even deeper in the tree.

**Comment by mjdesa** [comment]
@pauldix if I package everything into `main` in `influx_stress` is there any way to import the `Run` method externally?

**Comment by pauldix** [comment]
where else do you need to import it to?

**Comment by mjdesa** [comment]
I was using it in another repo that sends a post request to my results server instead of printing the results out in shell. I suppose I could add the logic for that in `influx_stress`, but I didn't want to muddy up the `influx_stress` logic with my specific use case.

**Comment by pauldix** [comment]
ah, you could just put it in a package off the main dir. i.e. `stress` and then have only the file for the executable in `cmd/influx_stress`

**Comment by mjdesa** [comment]
any particular naming scheme for the file? Or is `stress/runner.go` fine?

**Comment by pauldix** [comment]
sure, runner is fine. Not a huge fan of that name, but I can't think of
anything better :)

**Comment by mjdesa** [comment]
@pauldix can I merge this in?

**Comment by pauldix** [comment]
+1

**Pull request merged**
