### PR TITLE
Make bz1 close the WAL before closing bolt so it can flush

### PR DESCRIPTION
**Pull request by pauldix**
/cc @otoolep

### CODE REVIEW

**Comment by otoolep** [comment]
Does what it says in the patch. :-) +1

But this is the right fix why?

**Comment by pauldix** [comment]
@otoolep you were hitting a condition where the BoltDB was closed and before it closed the WAL, it tried to flush to the Bolt index. This ensure that the WAL will be closed and no flushes will occur before the BoltDB index gets closed.

**Comment by otoolep** [comment]
Ah, great, that makes sense.

I will retest https://github.com/influxdb/influxdb/issues/3725 when this merges.

**Comment by jwilder** [comment]
I'm able to reproduce this by running `influx_stress` and dropping the `stress` database while the test is running.  

With this patch, I'm getting a new panic:
```
panic: assignment to entry in nil map

goroutine 389 [running]:
github.com/influxdb/influxdb/tsdb/engine/wal.(*Log).partition(0xc2080ac1c0, 0xc246f28000, 0x22, 0x7fe00, 0xa)
	/Users/jason/go/src/github.com/influxdb/influxdb/tsdb/engine/wal/wal.go:665 +0x28e
github.com/influxdb/influxdb/tsdb/engine/wal.(*Log).pointsToPartitions(0xc2080ac1c0, 0xc247492000, 0x1388, 0x1800, 0x9)
	/Users/jason/go/src/github.com/influxdb/influxdb/tsdb/engine/wal/wal.go:483 +0x110
```

**Comment by pauldix** [comment]
@jwilder that's actually a different issue. I have to add drop database support to the wal. Will do in another PR. This one good to merge?

**Comment by otoolep** [comment]
Not sure if it's a Circle thing, but this branch hasn't passed yet up there. Tests keep timing out in various places.

**Comment by otoolep** [comment]
https://circleci.com/gh/influxdb/influxdb/tree/pd-close-wal-before-bolt

**Comment by jwilder** [comment]
@pauldix :+1: on green build.  This PR fixes the original panic I was seeing.

**Comment by benbjohnson** [comment]
:+1:

**Comment by pauldix** [comment]
cherry picked in 0.9.3

**Pull request merged**
