### PR TITLE
Support setting openTSDB write consistency

### PR DESCRIPTION
**Pull request by otoolep**
Similar functionality exists for Graphite and has already been committed.

### CODE REVIEW

**Comment by otoolep** [comment]
@dgnorton @benbjohnson @toddboom

**Comment by toddboom** [comment]
lgtm, but seems to have failed the suite for the `opentsdb` package

**Comment by benbjohnson** [comment]
lgtm on :green_apple:

**Comment by otoolep** [comment]
Forgot a small update to an openTSDB test, it was a compile-time error.

Thanks for the review, I will merge on green.

**Pull request merged**
