### PR TITLE
Make UDP service code simpler

### PR DESCRIPTION
**Pull request by renan-**
Hi,

When I wrote this code, I was inspired from graphite and collectd endpoints. Then I noticed that Server and Service are the exact same thing ! I guess Server is the old name for Service, isn't it? So why bother making a kind of wrapper whereas it could be way simpler ?
I also removed the log each time a packet is read from UDP.
Hope this will be useful even if it's not crucial :)

### CODE REVIEW

**Comment by corylanou** [comment]
@renan- This looks good.  I agree we probably had an extra layer in there.  It came from a quick refactoring.  This is better.

The logging is something we'll likely add a configuration option for in the future for debugging, but I agree, by default, it should be off.

Next up, testing :-).

Thanks again for all your hard work!

+1

**Comment by renan-** [comment]
You're welcome, I'm glad I could help out :-)
Btw, I'm currently working on making retention policy and consistency level configurable. Would you like me to create another PR for this feature ? (I could also add these config fields to the services lacking them).
Also, my company needs to be able to have multiple UDP services to run at the same time because database and rp are now service-instance-specific. I think this would be a great addition, just like it's done with Graphite (easy enough). What's your opinion on the matter ?

**Comment by corylanou** [comment]
Let's do that in a future PR.  Also, before we allow multiple UDP ports, go ahead and actually open an issue stating your problem.  This will allow for the core team to comment on it as an ISSUE before you do work on it.  I do agree that people will likely need this feature.

**Comment by renan-** [comment]
Well that's not what I'd call an issue, it's more like a feature to me.
Currently working on configurable RP and CL, I'll open a PR when I'm done.

**Comment by corylanou** [comment]
It's an issue in as much as the current system doesn't meet your needs.  Alternatively you can start a thread on the mailing list and our support team can turn it into an issue from there, but ultimately, I suspect it will end up being an issue as that is how we manage work effort on our team.

**Comment by otoolep** [comment]
+1 from me too -- merging now.

**Pull request merged**
