### PR TITLE
allow comments in line protocol

### LINKED ISSUE #3037: Add comment character to parser to allow for comment lines in query batches
For collections of queries run as a batch it would be useful to be able to include comment lines. Simplest implementation is probably any line that starts with `#` is a comment (ignoring leading whitespace, e.g. `/^\s*#/`)

SQL-92 has multi-line comments using `/*...*/` but that feels like overkill.

### PR DESCRIPTION
**Pull request by neonstalwart**
fixes #3037

cc @beckettsean @jwilder

### CODE REVIEW

**Comment by otoolep** [comment]
@neonstalwart -- thanks for the change, but I think you have misinterpreted the requirement. Ticket #3037 is about supporting comments in queries, not writes. 

I'm closing this, but I am happy to re-open if I am mistaken.

**Comment by neonstalwart** [comment]
@otoolep oh right :open_mouth: 

well, if this is ever something someone wants, it was simple

**Comment by beckettsean** [comment]
I would actually love to have this so I can put comments directly into test data we re-use or into to more advanced tutorial or documentation examples. It wasn't enough of a current need for me to make an issue but I will request this eventually, guaranteed.

@otoolep any reason we can't merge this?

**Comment by otoolep** [comment]
No reason, I only closed it because it didn't seem to be what we asked for. I've no objection to this feature, though I find it a little strange. I can accept it would be useful.

There is one test case I'd to see in place first. Let me comment further in this PR.

**Comment by otoolep** [comment]
Actually, no need for the test case. +1 on the code.

**Comment by beckettsean** [comment]
Waiting for @jwilder to return and bless.

**Comment by jwilder** [comment]
I'm fine with this.  :+1:

**Pull request merged**
