### PR TITLE
linted service/admin

### PR DESCRIPTION
**Pull request by nii236**
Issue described [here](https://github.com/influxdb/influxdb/issues/4098)

### CODE REVIEW

**Comment by nii236** [comment]
- [ ] CHANGELOG.md updated
- [ ] Rebased/mergable
- [ ] Tests pass
- [ ] Sign [CLA](http://influxdb.com/community/cla.html) (if not already signed)

**Comment by nii236** [comment]
CircleCI blew up on folders that I did not modify. I'm going to have a look before reopening my PR.

**Comment by otoolep** [comment]
We have some known issues with Circle and some tests. If you re-open this I will merge.

**Comment by nii236** [comment]
Am I entitled to a t-shirt now? =D

I'll be linting more stuff in the future also

**Comment by otoolep** [comment]
Sure are @nii236 -- e-mail me your address.

**Comment by otoolep** [comment]
CLA confirmed signed, comment-changes only. Merging now.

**Comment by otoolep** [comment]
Thanks @nii236

**Pull request merged**
