### PR TITLE
Add Go RPC input

### PR DESCRIPTION
**Pull request by masahide**
It is a PR to add a  Go RPC input interface, which provides in unix domain socket (or TCP socket).

The purpose of this PR is the following.

* intuitive bulk data insertion from golang code.
* The speed improvement by efficient gob marshal / unmarshal process by Go RPC.
  * Go RPC is 4.5x faster than original http client. (Benchmark code: http://git.io/vLv3t)

benchmark on the aws ec2(c3.8xlarge)
```
$ go test -bench .
testing: warning: no tests to run
PASS
BenchmarkGoRPC        50          24603515 ns/op
BenchmarkClient_Write         10         112689912 ns/op
```

- [x] CHANGELOG.md updated
- [x] Rebased/mergable
- [x] Tests pass
- [x] Sign [CLA](http://influxdb.com/community/cla.html) (if not already signed)

### CODE REVIEW

**Comment by otoolep** [comment]
@masahide -- thanks for your interesting functionality. Since this exposes a Unix-domain socket, I presume this is for when client code is running on the same box as the `influxd` process, correct?

**Comment by masahide** [comment]
That is right.
This function is used to run the client on the same host .
but, it is also possible to listen on TCP in the configuration of the config.toml file.

Ex:
```
[gorpc]
  enabled = true
  auth-enabled = true
  network = "tcp"              #  "unix"
  laddr = "0.0.0.0:5555"   # "/tmp/influxdb.sock" 
```

**Comment by jwilder** [comment]
I just tried this using the unix domain socket I'm guessing you benchmarked against the JSON client.  The client has been changed to use the line protocol recently which is significantly faster.  Using the updated client, the benchmark test indicates that this GoRPC client is slower than the current client.

```
influxdb:bench jason$ go test -bench .
testing: warning: no tests to run
PASS
BenchmarkGoRPC	     100	  17421633 ns/op
BenchmarkClient_Write	     100	  11682265 ns/op
ok  	github.com/influxdb/influxdb/cmd/bench	3.139s
influxdb:bench jason$
```

**Comment by otoolep** [comment]
@masahide -- thanks for this work. As @jwilder pointed out our line protocol is much more efficient, so we don't believe we need this now. If that is not the case, please let us know.

**Pull request closed without merging**
