### PR TITLE
Move to simpler cache

### PR DESCRIPTION
**Pull request by otoolep**
This cache simply evicts as much as possible whenever a checkpoint is set. Data is organised by key, then by checkpoint. With the reduction in functionality, it's now quite simple.

The engine must combine data in the cache with any other data, such as tsm1 files, that may contain data matching a query.

```
$ go test -run=XXX -bench=Benchmark_Cache -test.benchmem
PASS
Benchmark_CacheWriteSameKeySameCheckpoint           5000            331231 ns/op          423138 B/op          0 allocs/op
Benchmark_CacheWriteSameKeyDifferentCheckpoint     10000            103946 ns/op           82019 B/op          2 allocs/op
ok      github.com/influxdb/influxdb/tsdb/engine/tsm1   2.777s
```
I need to study the benchmarks more closely, to look for improvements, but this cache should be usable now by the engine.

__Note to reviewers__: I suggest you simply look at the new files (hit the "view" button), and ignore the diff. The new code is much simpler, and probably easier to to understand that way.

### CODE REVIEW

**Comment by otoolep** [comment]
@jwilder @pauldix

**Comment by pauldix** [comment]
@otoolep looks good, but there's one thing missing that I just realized. It's not enough to have a single checkpoint value since the cache has to work for multiple shards. Assuming the checkpoint is just the number of the WAL file, they wouldn't be unique across shards. So you need the combination of the shard ID and the checkpoint.

**Comment by otoolep** [comment]
OK @pauldix -- I believe I see what you are saying. While we imagine 1 in-RAM cache for the entire system, there is a WAL per shard. And WAL segment IDs are not unique system-wide, but only per shard. 

(Shard is a logical concept in the sense it maps to multiple WAL segment files and tsm1 files).

**Comment by otoolep** [comment]
To ease development, going to merge this now and open a new PR so that the cache supports shard IDs. I believe @jwilder is already generally happy with the interface, so it just needs tweaking with IDs.

**Comment by jwilder** [comment]
We had also discussed moving to a single WAL as well.  The engine is tied to a shard and the engine is what would have the reference to the WAL and cache.  Making these components support multiple shards might not be straightforward with the other engines in place since we'd have to move the engine up to the `tsdb.Store`.

**Comment by otoolep** [comment]
@jwilder and I spoke about this, and we understand the requirement @pauldix . However, in the interest of getting to the goal of a refactored tsm1 in 0.9.6, we're going to punt on it for now. In other words the cache will operate like it does now -- on a per-shard basis. It actually requires significantly more refactoring to have a unified cache, and while we both agree it's the right thing to do, it will only get in the way right now of bringing a refactored tsm1 engine online.

**Pull request merged**
