### PR TITLE
Update functions.go

### PR DESCRIPTION
**Pull request by linfangrong**
to fix int64

- [x] CHANGELOG.md updated
- [x] Rebased/mergable
- [x] Tests pass
- [x] Sign [CLA](http://influxdb.com/community/cla.html) (if not already signed)

### CODE REVIEW

**Comment by otoolep** [comment]
thanks @linfangrong  -- have you signed the CLA?

**Comment by otoolep** [comment]
@corylanou

**Comment by corylanou** [comment]
+1, waiting on CLA confirmation.  Should also add change log.

**Comment by linfangrong** [comment]
@otoolep yeah, I just signed the CLA

**Pull request merged**
