### PR TITLE
Fix infinite recursion in DeleteStatement.String()

### LINKED ISSUE #4406: No feedback on some queries
How can I delete data of a certain timerange from InfluxDB 0.9.4 gui with a query?

When I try:
```
DELETE FROM "db_grafana01" WHERE time > '2015-01-01' and time < '2015-10-11 18:00:00'
```
I get no response at all. Also tried with single quotes and without quotes. It would be nice if at least some message was returned that I'm doing an invalid query.

### PR DESCRIPTION
**Pull request by kostya-sh**
Fixes #4406

### CODE REVIEW

**Comment by otoolep** [comment]
Good catch @kostya-sh -- thanks.

cc @dgnorton

**Comment by otoolep** [comment]
+1 from me.

**Comment by dgnorton** [comment]
+1

**Comment by kostya-sh** [comment]
Thank you for accepting my 2nd PR! I can claim my t-shirt now ;)

**Comment by willemdh** [comment]
@kostya-sh  Thank you for fixing my third issue! So will this be in the next release 0.9.4.3?

**Comment by otoolep** [comment]
This fix will ship in 0.9.5 and is also available in the nightly builds.

**Pull request merged**
