### PR TITLE
Add support for SET PASSWORD FOR user = 'PASSWORD'

### PR DESCRIPTION
**Pull request by n1tr0g**
Added support for the set password for user, so we can update user password via the new server administration commands.

Example:

curl -s -G http://localhost:8086//query?db=&q=set+password+for+dejan+%3D+%golja%27

### CODE REVIEW

**Comment by otoolep** [comment]
Thanks @n1tr0g -- have you signed the CLA? Also, does the tests suite for you? Please be sure to run it before opening a PR.

**Comment by otoolep** [comment]
This is a good idea, and we need it. I'm not sure this is quite the syntax we want however. We may want `ALTER USER`, like we have `ALTER RETENTION`.

**Comment by dgnorton** [comment]
@n1tr0g  that's awesome.  I agree with @otoolep, `ALTER USER` is more consistent with existing syntax.  Also allows other user fields to be updated in the same statement.  Can you change it to `ALTER USER` and update INFLUXQL.md?  Thanks for contributing!

**Comment by n1tr0g** [comment]
Sure I can change that to alter user, however I followed the MySQL syntax when doing that ... https://dev.mysql.com/doc/refman/5.0/en/set-password.html

About the CI failing could you guys have a look ? I am not the first one getting this error. Looks like something is missing in the repo so the tests fail.

p.s. - yes I signed the CLA

**Comment by otoolep** [comment]
@dgnorton -- would you mind offering suggestions for the `ALTER USER` syntax?

As for the CI failure, you've somehow changed the output of `SHOW USER` since the password hashes are now coming back:

```
	server_integration_test.go:1268: Test #115: "show users, 1 existing user" failed
		  exp: {"results":[{"series":[{"columns":["user","admin"],"values":[["jdoe",false]]}]}]}
		  got: {"results":[{"series":[{"columns":["user","admin"],"values":[["jdoe",false,"$2a$10$2M1xSL0kynjovZCHEwN8Q.2.5hlSQjip/JkItoCZPzrsExF/Wk/dW"]]}]}]}
	server_integration_test.go:1239: Running test 116: GRANT ALL PRIVILEGES TO jdoe
	server_integration_test.go:1239: Running test 117: show users, existing user as admin
	server_integration_test.go:1268: Test #117: "show users, existing user as admin" failed
		  exp: {"results":[{"series":[{"columns":["user","admin"],"values":[["jdoe",true]]}]}]}
		  got: {"results":[{"series":[{"columns":["user","admin"],"values":[["jdoe",true,"$2a$10$2M1xSL0kynjovZCHEwN8Q.2.5hlSQjip/JkItoCZPzrsExF/Wk/dW"]]}]}]}
```

Please run `go test` and make sure the test does not fail locally.

As for general discussions about changes, the mailing list is a good place to start.

**Comment by n1tr0g** [comment]
@otoolep tnx ... 

Hmm I did modify the output of 'SHOW USERS' when testing, but looks like I forgot to undo it before committing the PR. Should be fixed now.

**Comment by dgnorton** [comment]
@benbjohnson @pauldix  what do you guys think about `ALTER USER` vs `SET PASSWORD`?  See @n1tr0g's comments above.

**Comment by pauldix** [comment]
I'm cool with using `SET PASSWORD` or whatever. I don't have strong opinions on all the stuff related to administration. Just that everything should be possible so that people can script whatever they need through puppet, chef, ansible, etc.

**Comment by benbjohnson** [comment]
I like `SET PASSWORD` since it's such a common use case and other databases support it (e.g. MySQL). I always forget the syntax of `ALTER USER`.

**Comment by n1tr0g** [comment]
Any final decision on that ?

**Comment by pauldix** [comment]
LGTM, thanks @n1tr0g!

**Pull request merged**
