### PR TITLE
Fix shard datanodes stats getting appended too many times

### PR DESCRIPTION
**Pull request by jwilder**

### CODE REVIEW

**Comment by otoolep** [comment]
Nice, I thought I saw something funky in the output earlier this evening. :-)

**Comment by otoolep** [comment]
+1, on green build.

**Comment by otoolep** [comment]
Changelog too -- this is a bugfix to a user-visible feature.

**Comment by otoolep** [comment]
https://github.com/influxdb/influxdb/issues/2380 filed already about this failure.

**Comment by toddboom** [comment]
:+1:

**Pull request merged**
