### PR TITLE
name the FlagSet for the shell and add a version flag

### PR DESCRIPTION
**Pull request by neonstalwart**
i don't know if you want this but it took very little effort and i thought it was useful to have another way to get the version of the install
```sh
> influx -version
InfluxDB shell 0.9

> influx -h
Usage of InfluxDB REPL version 0.9:
  -database="": database to connect to the server.
  -dump=false: dump the contents of the given database to stdout
  -execute="": Execute command and quit.
  -host="localhost": influxdb host to connect to
  -output="column": format specifies the format of the server responses:  json, csv, or column
  -password="": password to connect to the server.  Leaving blank will prompt for password (--password="")
  -port=8086: influxdb port to connect to
  -username="": username to connect to the server.
  -version=false: Displays the InfluxDB version.
```

### CODE REVIEW

**Comment by otoolep** [comment]
Thanks @neonstalwart -- you know you can do `influxd version`, right?

**Comment by otoolep** [comment]
```
$ ./influxd version
[srvr] 2015/05/06 12:29:29 InfluxDB v0.9 (git: unknown)
```

**Comment by neonstalwart** [comment]
@otoolep yes, i discovered that while adding this :smile: but for some reason i couldn't find it when i wanted it before i did this

**Comment by neonstalwart** [comment]
so, the one new thing i added here is a better description for the FlagSet.  that's got to be worth something :wink:

**Comment by corylanou** [comment]
@neonstalwart the usage was recently redone to be clearer and more accurate as the basic usage that Go puts out is not accurate.

See https://github.com/influxdb/influxdb/pull/2603

Feel free to rebase and add this new flag there (or update usage to show how to use the existing option that already existed).

Thanks!

**Comment by neonstalwart** [comment]
@corylanou rebased

**Comment by corylanou** [comment]
+1

**Comment by toddboom** [comment]
+1

**Pull request merged**
