### PR TITLE
Add batching and stats to openTSDB input

### PR DESCRIPTION
**Pull request by otoolep**
This change adds batching to the openTSDB input, for all points received over the telnet protocol. It also adds stats support to the openTSDB input.

### CODE REVIEW

**Comment by otoolep** [comment]
@corylanou @dgnorton @DanielMorsing

**Comment by otoolep** [comment]
Branch is green, as can be seen on Circle here: https://circleci.com/gh/influxdb/influxdb/5676

**Comment by corylanou** [comment]
+1.  Assuming no new tests needed for the added functionality?

**Comment by otoolep** [comment]
No @corylanou -- batching should be transparent to the tests, and the fact that they still pass is good enough for me. In addition the batcher itself has been unit-tested for a while now.

**Pull request merged**
