### PR TITLE
Always append shard path in diags

### PR DESCRIPTION
**Pull request by otoolep**
This code is clearer -- simply append an empty path if the shard is not
local.

Fixes issue #2430

### CODE REVIEW

**Comment by otoolep** [comment]
Before this change the column `path` was added if the shard was local, otherwise it was not. This code had some bugs, so it's much simpler to just add the `path` to all shows and simply set the path to `""` for non-local shards.

**Comment by marcosnils** [comment]
@otoolep PR is clean and better. :+1: . I didn't want to change too much as I still don't know how internals work.

**Comment by otoolep** [comment]
@mark-rushakoff

**Comment by toddboom** [comment]
+1

**Pull request merged**
