### PR TITLE
#1683 Move BatchPoints into Client

### PR DESCRIPTION
**Pull request by d2g**
PR as requested.
#1683 Moves BatchPoints into Client.

### CODE REVIEW

**Comment by corylanou** [comment]
So I'm pretty sure this is where it was originally, then it got pulled to the top level, and now we are putting it back?

**Comment by d2g** [comment]
I'm not sure but it feels wrong.

There currently is: 
    influbdb.BatchPoints 
    influxdb.Point
    client.Write
    client.Point

From a client API point of view it would be good if I didn't have to look into the server documentation to find the write format (So +1 keeping it in Client).

However by keeping them separate we end up with issues i.e.

Currently a representation of client.Point can have a timestamp equivalent of "2006-01-02T00:00:00.000000000Z00:00" with a precision of nanoseconds. 

Where as the influxdb.Point only has a timestamp so  it would never know that "2006-01-02T00:00:00.000000000Z00:00" has a precision of nanoseconds.

Therefore if the precision is lost in the influxdb.Point should it be removed from the client.Point?

Should another package be created for shared types? Then each package embeds the shared type?

Let me know what you guys/gals decide I'll happily try and assist with any changes.

**Comment by otoolep** [comment]
We actually debated this internally quite a bit, as we wanted to avoid the same data structure in both the client package and the server. Right now I don't believe what we have ideal, and we're still trying to reach consensus (not trying that hard). We also considered a package for shared types.

I agree you've identified a construction issue with this part of the code.

**Comment by toddboom** [comment]
I don't think we're planning to merge this, so I'm going to close it out. We might revisit this later as we revise the CLI.

**Pull request closed without merging**
