### PR TITLE
update reduce func signatures to not have influxql.Call arguments

### PR DESCRIPTION
**Pull request by nathanielc**
Same thing we did for the map functions.

### CODE REVIEW

**Comment by nathanielc** [comment]
@corylanou You probably are interested in this PR.

**Comment by otoolep** [comment]
This makes it easier for you to use them @nathanielc ?

**Comment by nathanielc** [comment]
@otoolep  Yes, this way I don't have to construct a Call object just to call the functions.

**Comment by otoolep** [comment]
+1

**Pull request merged**
