### PR TITLE
Fixed some typos

### PR DESCRIPTION
**Pull request by pradeepchhetri**

### CODE REVIEW

**Comment by otoolep** [comment]
Thanks @pradeepchhetri -- have you signed the CLA?

**Comment by pradeepchhetri** [comment]
Hello @otoolep I just now signed the CLA. Thank you.

**Comment by otoolep** [comment]
Thanks @pradeepchhetri.

Comments only, merging now.

**Comment by pradeepchhetri** [comment]
Thank you @otoolep

**Pull request merged**
