### PR TITLE
fix TestCluster_OpenRaft is timeout

### LINKED ISSUE #4853: TestCluster_OpenRaft is timeout
````
=== RUN   TestCluster_OpenRaft
[metastore] 2015/11/20 22:50:53 Using data dir: C:\Users\meifakun\AppData\Local\Temp\influxdb-meta-156530767\0
[metastore] 2015/11/20 22:50:54 Node at 127.0.0.1:57193 [Follower]
[metastore] 2015/11/20 22:50:54 Node at 127.0.0.1:57193 [Leader]. peers=[]
[metastore] 2015/11/20 22:50:54 Created local node: id=1, host=127.0.0.1:57193
[metastore] 2015/11/20 22:50:54 spun up monitoring for 1
[metastore] 2015/11/20 22:50:54 Using data dir: C:\Users\meifakun\AppData\Local\Temp\influxdb-meta-156530767\1
[metastore] 2015/11/20 22:50:54 Node at 127.0.0.1:57215 [Follower]
[metastore] 2015/11/20 22:50:54 Joining cluster at: [127.0.0.1:57193]
[metastore] 2015/11/20 22:50:54 adding new raft peer: nodeId=2 addr=127.0.0.1:57215
[metastore] 2015/11/20 22:50:54 Joined remote node 127.0.0.1:57193
[metastore] 2015/11/20 22:50:54 nodeId=2 raftEnabled=true peers=[127.0.0.1:57215 127.0.0.1:57193]
[metastore] 2015/11/20 22:50:54 spun up monitoring for 2
[metastore] 2015/11/20 22:50:54 Using data dir: C:\Users\meifakun\AppData\Local\Temp\influxdb-meta-156530767\2
[metastore] 2015/11/20 22:50:54 Updated node id=2 hostname=127.0.0.1:57215
[metastore] 2015/11/20 22:50:55 Node at 127.0.0.1:57220 [Follower]
[metastore] 2015/11/20 22:50:55 Joining cluster at: [127.0.0.1:57193]
[metastore] 2015/11/20 22:50:55 adding new raft peer: nodeId=3 addr=127.0.0.1:57220
[metastore] 2015/11/20 22:50:55 Joined remote node 127.0.0.1:57193
[metastore] 2015/11/20 22:50:55 nodeId=3 raftEnabled=true peers=[127.0.0.1:57220 127.0.0.1:57193 127.0.0.1:57215]
[metastore] 2015/11/20 22:50:55 Updated node id=3 hostname=127.0.0.1:57220
[metastore] 2015/11/20 22:50:55 spun up monitoring for 3
[metastore] 2015/11/20 22:50:55 Using data dir: C:\Users\meifakun\AppData\Local\Temp\influxdb-meta-156530767\3
[metastore] 2015/11/20 22:50:55 Node at 127.0.0.1:57224 [Follower]
[metastore] 2015/11/20 22:50:55 Joining cluster at: [127.0.0.1:57193]
[metastore] 2015/11/20 22:50:55 Joined remote node 127.0.0.1:57193
[metastore] 2015/11/20 22:50:55 nodeId=4 raftEnabled=false peers=[127.0.0.1:57220 127.0.0.1:57193 127.0.0.1:57215]
[metastore] 2015/11/20 22:50:55 Switching to remote raft
[metastore] 2015/11/20 22:50:55 spun up monitoring for 4
[metastore] 2015/11/20 22:50:55 Using data dir: C:\Users\meifakun\AppData\Local\Temp\influxdb-meta-156530767\4
[metastore] 2015/11/20 22:50:55 Updating metastore to term=1 index=7
[metastore] 2015/11/20 22:50:55 Updated node id=4 hostname=127.0.0.1:57224
[metastore] 2015/11/20 22:50:55 Node at 127.0.0.1:57229 [Follower]
[metastore] 2015/11/20 22:50:55 Joining cluster at: [127.0.0.1:57193]
[metastore] 2015/11/20 22:50:55 Joined remote node 127.0.0.1:57193
[metastore] 2015/11/20 22:50:55 nodeId=5 raftEnabled=false peers=[127.0.0.1:57220 127.0.0.1:57193 127.0.0.1:57215]
[metastore] 2015/11/20 22:50:55 Switching to remote raft
[metastore] 2015/11/20 22:50:55 Updating metastore to term=1 index=8
[metastore] 2015/11/20 22:50:55 spun up monitoring for 5
[metastore] 2015/11/20 22:50:55 Updated node id=5 hostname=127.0.0.1:57229
[metastore] 2015/11/20 22:50:55 Using data dir: C:\Users\meifakun\AppData\Local\Temp\influxdb-meta-156530767\5
[metastore] 2015/11/20 22:50:55 Node at 127.0.0.1:57234 [Follower]
[metastore] 2015/11/20 22:50:55 Joining cluster at: [127.0.0.1:57193]
[metastore] 2015/11/20 22:50:55 Joined remote node 127.0.0.1:57193
[metastore] 2015/11/20 22:50:55 nodeId=6 raftEnabled=false peers=[127.0.0.1:57220 127.0.0.1:57193 127.0.0.1:57215]
[metastore] 2015/11/20 22:50:55 Switching to remote raft
[metastore] 2015/11/20 22:50:55 spun up monitoring for 6
[metastore] 2015/11/20 22:50:55 database 'db0' created
[metastore] 2015/11/20 22:50:55 database 'db1' created
[metastore] 2015/11/20 22:50:56 database 'db2' created
*** Test killed: ran too long (10m0s).
FAIL    github.com/influxdb/influxdb/meta       600.444s
````

### PR DESCRIPTION
**Pull request by runner-mei**
fix  #4853
This bug is produce by tcp buffer, must flush tcp stream after the copy L53, but Flush is not exists in the net.TcpConn struct.

### CODE REVIEW

**Comment by benbjohnson** [comment]
@runner-mei Why not use [`TCPConn.Close()`](https://golang.org/pkg/net/#TCPConn.Close) instead?

**Comment by runner-mei** [comment]
Close is better, but it will result in repeated calls to close, so errors buffer size must is 2.

**Comment by otoolep** [comment]
Thanks @runner-mei -- would you mind squashing the commits?

**Comment by otoolep** [comment]
Seems reasonable, +1 from me once squashed.

@benbjohnson ?

**Comment by benbjohnson** [comment]
:+1:

**Comment by otoolep** [comment]
Thanks @runner-mei -- hoping this clears up a bunch of testing failures.

**Pull request merged**
