### PR TITLE
Fix SHOW MEASUREMENTS across the cluster

### PR DESCRIPTION
**Pull request by li-ang**
fix `SHOW MEASUREMENTS` described by issue #4550 

`SHOW MEASUREMENTS` maybe return  `ERR: json: cannot unmarshal array into Go value of type tsdb.MapperOutputJSON` accross the cluster. 

- [ ] CHANGELOG.md updated
- [x] Rebased/mergable
- [x] Tests pass
- [x] Sign [CLA](http://influxdb.com/community/cla.html)

### CODE REVIEW

**Comment by li-ang** [comment]
#4550

**Comment by otoolep** [comment]
@dgnorton -- can you review?

**Comment by dgnorton** [comment]
+1

**Comment by otoolep** [comment]
Thanks @li-ang

**Comment by aderumier** [comment]
Hi,

I'm testing the last nightly build with this commit apply,

I have previously the same error " cannot unmarshal array",

now I'm getting a new error message "use of closed network connection"

**Comment by li-ang** [comment]
@aderumier Can you show your test log?

**Comment by aderumier** [comment]
Oh, sorry, it's working fine. 
I have make a mistake when upgrading my server, rollbacking to an old config file using old datas localtion with bz1 cluster.

**Comment by aderumier** [comment]
I don't see any special log in influxd.log. (is it possible to increase verbosity ?)

client test:

Visit https://enterprise.influxdata.com to register for updates, InfluxDB server management, and monitoring.
Connected to http://localhost:8086 version 0.9.6-nightly-3b035cc
InfluxDB shell 0.9.6-nightly-3b035cc
> use collectd
Using database collectd
> show measurements
ERR: write message type: use of closed network connection


(Note that it's still working fine with my others database, where I didn't have the unmarshal array error previously)

**Comment by li-ang** [comment]
Do you use whether InfluxDB cluster or InfluxDB single node?

**Comment by alahiff** [comment]
With 0.9.6-nightly-3b035cc I also see the same error when running "show measurements". It seems to only happen when the number of replicas is less than the number of nodes in the cluster. Previously I had the "cannot unmarshal array" error in this situation.

**Comment by li-ang** [comment]
Thanks @alahiff ! I will confirm the commit ASAP! In InfluxDB official website , there is such a description   as following `The current version of InfluxDB is 0.9.4.1. Clustering, replication and high-availability should be considered in an alpha state.` I also catch many clustering problems in the 0.9.6. I will focus on it and try to make clustering stable.

**Comment by aderumier** [comment]
I have a 3 nodes cluster,
the database "collectd" was auto-created with replica 1, 
some datas has been writen,
and after that I have change the default policy to replica 3.

name	duration	replicaN	default
default	0		3		true

I could be great to be able to have an option "replica" in [retention]  configuration,

**Comment by li-ang** [comment]
Go it! Thanks @aderumier 
As my opinion, changing `replica` is not a safe operation in current version because it can bring more problems. I suggest you create new `retention policy` with setting `replica` as 3 and then write data points.

**Comment by li-ang** [comment]
@aderumier  @alahiff  
Please refer to issue #4926  and pr #4927  Thanks!

**Pull request merged**
