### PR TITLE
Update limit and offset

### PR DESCRIPTION
**Pull request by pauldix**
This PR changes `LIMIT` and `OFFSET` to `SLIMIT` and `SOFFSET`. It also implements `LIMIT` and `OFFSET` to limit the number of data points returned per series in the result.

### CODE REVIEW

**Comment by toddboom** [comment]
This looks good. My only two questions are:

1. Should we use `SLimit` and `SOffset` instead of `Slimit` and `Soffset` for clarity?
2. Should the changes in `server_test.go` actually be duplicated/expanded so that we're testing both `LIMIT`/`OFFSET` and `SLIMIT`/`SOFFSET` or is `LIMIT`?

**Comment by pauldix** [comment]
@toddboom:  The tests for `LIMIT` and `OFFSET` are in `server_integration_test.go`, which is where these other ones should go eventually. I just didn't want to bother transferring them over in this PR.

Once the race condition stuff gets resolved so that writes don't have to wait 3 seconds in those integration tests, I'll get more aggressive about moving more of the tests in there.

Updated `Slimit` and `Soffset` to `SLimit` and `SOffset` in the code.

**Comment by toddboom** [comment]
rad, :+1:!

**Comment by duylong** [comment]
Good feature +1

Could we not set a default limit ? (for example defined in the configuration file)

**Pull request merged**
