### PR TITLE
If HH can't unmarshal a block, skip that block

### PR DESCRIPTION
**Pull request by otoolep**

### CODE REVIEW

**Comment by otoolep** [comment]
@jwilder

**Comment by otoolep** [comment]
During testing on this branch I am seeing `currentErr` go non-zero -- the system is having trouble sometimes getting the current block for a given node.

**Comment by jwilder** [comment]
Current will return an error when the queue is empty. That is how it breaks out of the loop normally. Should check for an error other than EOF (or whatever it returns)

**Comment by otoolep** [comment]
Got it @jwilder -- thanks.

**Comment by otoolep** [comment]
Need to look into this more but now seeing this during testing or bouncing nodes around the cluster during writes:
```
name: hh_processor
tags: nodeID=3
bytes_write     current_err     points_hint     points_write    unmarshal_err   write_err
-----------     -----------     -----------     ------------    -------------   ---------
111             13              2853            3               2               1
```
We are hitting unmarshalling errors.

**Comment by otoolep** [comment]
Even if the errors might be harmless e.g. EOF, this means we could go down the path that this bug is meant to fix. Perhaps the issue is more likely than we realised.

**Comment by otoolep** [comment]
@jwilder -- I'd like to get this into a nightly if possible, so the partner can try it out.

**Comment by jwilder** [comment]
:+1:

**Comment by otoolep** [comment]
Thanks @jwilder -- I will tighten up the stat count and logging and then merge.

**Pull request merged**
