### PR TITLE
Added tests for esape.Unescape

### PR DESCRIPTION
**Pull request by dhowden**

### CODE REVIEW

**Comment by dhowden** [comment]
I have signed the CLA.

**Comment by otoolep** [comment]
Thanks @dhowden -- did you see the tests in 

https://github.com/influxdb/influxdb/blob/master/models/points_test.go

Are we missing coverage? Always good to have tests closer to the code of course.

**Comment by dhowden** [comment]
Ha! I didn't see that, was using `go tool -cover` to check for coverage, which doesn't span cross-package testing.

It seems that you have all the cases covered, although spread out over many tests and quite far from the implementation (and so not at all obvious).  Does feel a bit like duplication though...!

**Comment by otoolep** [comment]
I'm OK with merging this, it's good to keep tests close to the code.

@jwilder @corylanou ?

**Comment by corylanou** [comment]
I'm fine with it.  Should make it clearer having a simpler test here as well as to what the use cases are.

**Comment by otoolep** [comment]
Thanks @dhowden

**Pull request merged**
