### PR TITLE
Updated godoc.org link to v2 docs.

### PR DESCRIPTION
**Pull request by Lanzafame**

### CODE REVIEW

**Comment by otoolep** [comment]
Thanks @Lanzafame. Can you explain why we would make this change?

**Comment by Lanzafame** [comment]
Because the install instructions and examples on the client page references v2 but it was pointing at v1 on godoc.

**Comment by otoolep** [comment]
OK, thaks @Lanzafame -- have you signed the CLA?

**Comment by Lanzafame** [comment]
No. I will do once I'm at work. ~40 mins

**Comment by Lanzafame** [comment]
Where abouts is the CLA? I can't seem to find a link.

**Comment by beckettsean** [comment]
It's hidden in the left nav bar of the docs, at the bottom. 

https://influxdb.com/community/cla.html

**Comment by Lanzafame** [comment]
Cheers :+1:

**Comment by Lanzafame** [comment]
And signed.

**Comment by otoolep** [comment]
CLA confirmed signed.

@sparrc

**Pull request merged**
