### PR TITLE
Add flag to config that disables running CQs

### PR DESCRIPTION
**Pull request by rothrock**
I sure hope I haven't screwed up anything.

### CODE REVIEW

**Comment by toddboom** [comment]
@rothrock looks good so far - now the next step is to wire it into the continuous query logic!

**Comment by otoolep** [comment]
Looks good. So, since the flag defaults to false, you might actually like to modify the test config in `config_test.go` to set it to true. Then check that the unit test picks it up as true.

**Comment by otoolep** [comment]
See line 154 on of `config_test.go` to see what I mean.

**Comment by rothrock** [comment]
@otoolep will do.

**Comment by rothrock** [comment]
@otoolep pls take a look when you get a moment. I'm sort of git-retarded, so bear with me.

**Comment by otoolep** [comment]
This will work, but will result in lots of log messages. Instead I would just disable it at the very top level of the code, logging 1 message that CQs are off.

See https://github.com/influxdb/influxdb/blob/master/cmd/influxd/run.go#L59 -- this only

**Comment by rothrock** [comment]
Verbal +1 from @otoolep

**Pull request merged**
