### PR TITLE
Data node retrieves replicated shard data from peer

### PR DESCRIPTION
**Pull request by otoolep**
When a broker responds to a topic-stream request with list of data node
URLs, the requesting data node should instead fetch the shard for that
topic from one the URLs. When this fetch completes the data node writes
the shard to disk, and then restarts streaming from the broker at a
later index, which should be serviceable by the broker.

### CODE REVIEW

**Comment by otoolep** [comment]
Initial idea to support reading shard data from peer data node.

**Comment by benbjohnson** [comment]
The approach looks good to me. The `conn` should probably close itself if it gets a redirection. Right now it tries to reconnect immediately.

**Comment by otoolep** [comment]
Completes all work for issue #1948

**Comment by otoolep** [comment]
Trying a different approach here:

https://github.com/influxdb/influxdb/pull/2477

**Comment by otoolep** [comment]
Closing for now.

**Pull request closed without merging**
