### PR TITLE
Fixes bind-address config setting.

### LINKED ISSUE #2468: bind-address parameter issue on 0.9
To issue from mailing list: https://groups.google.com/d/msgid/influxdb/455762cc-9669-4aa6-83ba-3df4e331dace%40googlegroups.com

------------
I have issue after change "bind-address" parameter from "0.0.0.0" to particular IP (not localhost). 
But unfortunatelly, influxdb can't run. 
I don't know why influxdb still contact localhost not IP from bind-address

```
[srvr] 2015/04/24 13:35:06 GOMAXPROCS set to 2
[srvr] 2015/04/24 13:35:06 using configuration at: /etc/opt/influxdb/influxdb.conf
[srvr] 2015/04/24 13:35:06 influxdb started, version 0.9.0-rc27, commit c887dfe2a86ca7dc6a06710b6a787d37734a23b4
[srvr] 2015/04/24 13:35:06 Cluster server listening on 128.199.66.29:8086
[srvr] 2015/04/24 13:35:06 broker opened at /var/opt/influxdb/raft
[raft] 2015/04/24 13:35:06 Open: fsm: index=0
[raft] 2015/04/24 13:35:06 log pending: waiting for initialization or join
[raft] 2015/04/24 13:35:06 changing term: 0 => 1
[raft] 2015/04/24 13:35:06 log state change: stopped => leader (term=1)
[raft] 2015/04/24 13:35:06 leaderLoop
[raft] 2015/04/24 13:35:06 log initialize: promoted to 'leader' with cluster ID 9198811507380792097, log ID 1, term 1
[srvr] 2015/04/24 13:35:06 initialized broker: http://localhost:8086
[srvr] 2015/04/24 13:35:06 data node(0) opened at /var/opt/influxdb/db
[messaging] 2015/04/24 13:35:06 reconnecting to broker: url={http  <nil> localhost:8086 /messaging/messages index=0&streaming=true&topicID=0 }, err=Get http://localhost:8086/messaging/messages?index=0&streaming=true&topicID=0: dial tcp 127.0.0.1:8086: connection refused
[srvr] 2015/04/24 13:35:07 join: failed to connect data node: http://localhost:8086: Post http://localhost:8086/data/data_nodes: dial tcp 127.0.0.1:8086: connection refused
[srvr] 2015/04/24 13:35:07 join: failed to connect data node to any specified server
```
Regards,
--Rizal

### PR DESCRIPTION
**Pull request by marcosnils**
To prevent breaking backwards compatibility this change `only` uses
bind-address if hostname is not specified.
Fixes #2468.

### CODE REVIEW

**Comment by otoolep** [comment]
@corylanou

**Comment by corylanou** [comment]
This looks fine.  I suspect this is going to change again once we refactor for the upcoming changes, but makes sense to put in for now.  I think if we rebase the tests should pass.

+1 after the following:

- [ ] Update CHANGELOG.md
- [ ] Sign  [CLA](http://influxdb.com/community/cla.html) (if not already signed)
- [ ] Rebase to see if tests pass

**Comment by marcosnils** [comment]
@corylanou I'll make the changes and update the PR

**Comment by marcosnils** [comment]
@corylanou seems like tests are still failing.

**Comment by corylanou** [comment]
This is what is failing:

```
=== RUN TestRestoreCommand
2015/05/28 17:45:18 influxdb started, version 0.9, commit 
2015/05/28 17:45:18 Cluster server listening on [::]:8900
2015/05/28 17:45:18 broker opened at /tmp/influxdb-181885258/broker
[raft] 2015/05/28 17:45:18 stopped[0]: log pending: waiting for initialization or join
[raft] 2015/05/28 17:45:18 stopped[1]: changing term: 0 => 1
[raft] 2015/05/28 17:45:18 leader[1]: log initialize: promoted to 'leader' with cluster ID 2060500825090121671, log ID 1, term 1
2015/05/28 17:45:18 initialized broker: http://[::]:8900
2015/05/28 17:45:18 data node(0) opened at /tmp/influxdb-181885258/data
[messaging] 2015/05/28 17:45:18 reconnecting to broker: url={http  <nil> [::]:8900 /messaging/messages index=0&streaming=true&topicID=0 }, err=Get http://[::]:8900/messaging/messages?index=0&streaming=true&topicID=0: dial tcp [::]:8900: network is unreachable
2015/05/28 17:45:19 join: failed to connect data node: http://[::]:8900: Post http://[::]:8900/data/data_nodes: dial tcp [::]:8900: network is unreachable
2015/05/28 17:45:19 join: failed to connect data node to any specified server
```

It feels like it could be related to the code you changed, but I suspect the real error is how that test is hardcoding an port instead of dynamically having a port assigned.  I can take a look at this when I get a chance as well.

**Comment by corylanou** [comment]
hit wrong button, reopening...

**Comment by marcosnils** [comment]
@corylanou I've tried running the tests in my laptop and they're all passing. Not sure why it's failing on CI

**Comment by marcosnils** [comment]
```
=== RUN TestRestoreCommand
2015/05/28 21:20:37 influxdb started, version 0.9, commit 
2015/05/28 21:20:37 Cluster server listening on [::]:8900
2015/05/28 21:20:37 broker opened at /tmp/influxdb-006247743/broker
[raft] 2015/05/28 21:20:37 stopped[0]: log pending: waiting for initialization or join
[raft] 2015/05/28 21:20:37 stopped[1]: changing term: 0 => 1
[raft] 2015/05/28 21:20:37 leader[1]: log initialize: promoted to 'leader' with cluster ID 3801361281288830076, log ID 1, term 1
2015/05/28 21:20:37 initialized broker: http://[::]:8900
2015/05/28 21:20:37 data node(0) opened at /tmp/influxdb-006247743/data
[messaging] 2015/05/28 21:20:39 connected to broker: http://[::]:8900/messaging/messages?index=0&streaming=true&topicID=0
2015/05/28 21:20:39 initialized data node: http://[::]:8900
2015/05/28 21:20:39 authentication enabled: false
2015/05/28 21:20:39 broker enforcing retention policies with check interval of 10m0s
2015/05/28 21:20:39 shard group pre-create with check interval of 45m0s
2015/05/28 21:20:39 snapshot server disabled
2015/05/28 21:20:39 API server listening on 0.0.0.0:8900
2015/05/28 21:20:39 Sending anonymous usage statistics to m.influxdb.com
2015/05/28 21:20:39 broker cq: no data nodes currently available.
[server] 2015/05/28 21:20:39 retention policy 'default' auto-created for database 'db'
[messaging] 2015/05/28 21:20:39 connected to broker: http://[::]:8900/messaging/messages?index=0&streaming=true&topicID=1
2015/05/28 21:20:39 unpacking: meta / idx=6 (45056 bytes)
2015/05/28 21:20:39 unpacking: shards/1 / idx=7 (24576 bytes)
2015/05/28 21:20:39 restore complete using /tmp/influxdb-422497682
2015/05/28 21:20:39 influxdb started, version 0.9, commit 
2015/05/28 21:20:39 Cluster server listening on [::]:8910
2015/05/28 21:20:39 broker opened at /tmp/influxdb-006247743/broker
[raft] 2015/05/28 21:20:39 stopped[1]: log open: created at /tmp/influxdb-006247743/broker/raft, with ID 1, term 1, last applied index of 7
[raft] 2015/05/28 21:20:39 log open: promoting to leader immediately
2015/05/28 21:20:39 broker already member of cluster.  Using existing state and ignoring join URLs
2015/05/28 21:20:39 Loading metadata index for db
2015/05/28 21:20:39 data node(1) opened at /tmp/influxdb-006247743/data
2015/05/28 21:20:40 data node already member of cluster. Using existing state and ignoring join URLs
2015/05/28 21:20:40 authentication enabled: false
2015/05/28 21:20:40 broker enforcing retention policies with check interval of 10m0s
2015/05/28 21:20:40 shard group pre-create with check interval of 45m0s
2015/05/28 21:20:40 snapshot server disabled
2015/05/28 21:20:40 API server listening on 0.0.0.0:8910
2015/05/28 21:20:40 Sending anonymous usage statistics to m.influxdb.com
2015/05/28 21:20:40 broker cq: no broadcast topic currently available.
[messaging] 2015/05/28 21:20:40 connected to broker: http://[::]:8910/messaging/messages?index=6&streaming=true&topicID=0
[server] 2015/05/28 21:20:40 retention policy 'default' auto-created for database 'newdb'
[messaging] 2015/05/28 21:20:40 connected to broker: http://[::]:8910/messaging/messages?index=0&streaming=true&topicID=2
--- PASS: TestRestoreCommand (3.07s)
```

**Comment by toddboom** [comment]
@marcosnils i'm not sure if this is going to be needed after RC32, and will need a rebase at a minimum. i'm going to close it for now, but let us know if you'd like it reopened.

**Comment by marcosnils** [comment]
@otoolep yeah.. seems like you've changed a lot since this PR. We can dismiss it.

**Comment by toddboom** [comment]
@marcosnils cool, thanks for all the effort!

**Pull request closed without merging**
