### PR TITLE
Check if values are numbers before mean()

### PR DESCRIPTION
**Pull request by otoolep**

### CODE REVIEW

**Comment by otoolep** [comment]
Green build.

@pauldix @benbjohnson

**Comment by otoolep** [comment]
It is possible other aggregators will need this too, depending on what we decide to do.

@corylanou

**Comment by pauldix** [comment]
This should actually be validated before a query is even run. That way the Map functions won't have to do this check every time, particularly on the inner loop.

I logged an issue with detail here: #1845

**Comment by otoolep** [comment]
Agreed, I realised that this morning! Just check the types in the Metastore.

**Pull request closed without merging**
