### PR TITLE
json.Unmarshal errors not catch in method client.Write

### PR DESCRIPTION
**Pull request by akolosov**

### CODE REVIEW

**Comment by otoolep** [comment]
Make sense to me.

**Comment by akolosov** [comment]
tests got  'unexpected end of JSON input' error, but you use Unmarshal instead Marshal... just make changes:
```
 	//b := []byte{}
 	//err := json.Unmarshal(b, &d)
	b, err := json.Marshal(d)
	if err != nil {
		return nil, err
	}
```
and tests done

**Comment by otoolep** [comment]
@corylanou -- can we merge this? Looks like the code was using the wrong function.

**Comment by corylanou** [comment]
We should open an issue to write a test around it, but other than that, looks good.

**Comment by d2g** [comment]
So #1680 is a test that covers this issue.

However also highlights the issue that the write() actually wraps the write{} in an array (not sure why) which isn't how it's expected at the server end.

**Comment by corylanou** [comment]
@d2g The write endpoint can take a single write, or multiple writes.  This allows the end user to open an http endpoint and stream multiple writes without having to close the connection.  This can cut down on the overhead of connecting/disconnecting, as that overhead is typically higher than the actual payload being sent.

**Comment by corylanou** [comment]
We should add test coverage for multiple writes at some point as well.  Looking at the test coverage, that case it not covered.  We also don't cover it in the documentation.  I'll open up 2 issues prior to closing this issue as a reminder to update both test coverage and documentation.

**Comment by corylanou** [comment]
Fixed in #1868

**Pull request closed without merging**
