### PR TITLE
Dependencies License list

### PR DESCRIPTION
**Pull request by mjdesa**
All of the licenses for our dependencies.

### CODE REVIEW

**Comment by mjdesa** [comment]
Fixes https://github.com/influxdb/influxdb/issues/3888

**Comment by beckettsean** [comment]
@pauldix @toddboom @fred-influx I think we're out of compliance with the BSD licenses. 

```
2. Redistributions in binary form must reproduce the above copyright notice,
   this list of conditions and the following disclaimer in the documentation
   and/or other materials provided with the distribution.
```

I'm pretty sure we have zero license files in our binary packages, which means we might be in violation.

Also, raft has the MPL which I don't know very well. Looks like it might have implications for our own licensing. 

Apache license has a similar requirement, but `statik` doesn't have a NOTICE file so we're good:

```
If the Work includes a "NOTICE" text file as part of its
          distribution, then any Derivative Works that You distribute must
          include a readable copy of the attribution notices contained
          within such NOTICE file, excluding those notices that do not
          pertain to any part of the Derivative Works, in at least one
          of the following places: within a NOTICE text file distributed
          as part of the Derivative Works; within the Source form or
          documentation, if provided along with the Derivative Works; or,
          within a display generated by the Derivative Works, if and
          wherever such third-party notices normally appear. The contents
          of the NOTICE file are for informational purposes only and
          do not modify the License. You may add Your own attribution
          notices within Derivative Works that You distribute, alongside
          or as an addendum to the NOTICE text from the Work, provided
          that such additional attribution notices cannot be construed
          as modifying the License.
```

**Comment by beckettsean** [comment]
And there's this on the glyphicons license page:

```
GLYPHICONS Halflings are also a part of Bootstrap from Twitter, and they are released under the same license as Bootstrap. While you are not required to include attribution on your Bootstrap-based projects, I would certainly appreciate a visible link back to GLYPHICONS.com in any place you find appropriate (footer, docs, etc).
```

**Comment by beckettsean** [comment]
@pauldix @toddboom can we merge this?

**Comment by pauldix** [comment]
Done!

**Pull request merged**
