### PR TITLE
Integration tests

### PR DESCRIPTION
**Pull request by corylanou**
This is a highly experimental branch aimed at creating integration testing without the need for a binary being compiled.

It's a lot of WIP, but it does work.  However, you can't run it more than once before it hits a real bug and fails.  You end up removing the default data/broker directories to get the test to run successfully for now.

Mostly pushing this up for @benbjohnson and I to discuss some code/package organization.

### CODE REVIEW

**Comment by corylanou** [comment]
Creating an `influxd` package has the side affect of allowing someone to `embed` our database in their own system as well.  Seems crazy though...  but now possible.

**Comment by otoolep** [comment]
Good stuff, looking forward to seeing how this goes, and what approach we decide to use.

**Comment by corylanou** [comment]
@benbjohnson @otoolep I'm good with a review on this when you get a chance.  I moved everything back to the cmd/influxd package simply to avoid any debate on it for now.  More important is bringing up real integration tests that can consistently show failure cases.

**Comment by corylanou** [comment]
I messed this pull request up with rebase and we should not merge it.  Closing as a new PR has taken its place https://github.com/influxdb/influxdb/pull/1390

**Pull request closed without merging**
