### PR TITLE
Disable problematic tests

### PR DESCRIPTION
**Pull request by otoolep**

### CODE REVIEW

**Comment by otoolep** [comment]
Disabling these 3 tests restore pass stability to Circle. To unblock other develpoment, I suggest we merge this change, and aggressively debug why these 3 tests fail on Circle.

**Comment by otoolep** [comment]
The most recent failures were in the 3-node test.

**Comment by otoolep** [comment]
This PR also fixes a previously unknown race condition in the code, as flagged here:

https://circle-artifacts.com/gh/influxdb/influxdb/2570/artifacts/1/tmp/circle-artifacts.PUqLwHW/test_logs_race.txt

**Comment by corylanou** [comment]
+1

**Comment by toddboom** [comment]
+1

**Pull request merged**
