### PR TITLE
Admin interface

### PR DESCRIPTION
**Pull request by toddboom**
Some quick stuff to make the admin interface work like it used to.

### CODE REVIEW

**Comment by otoolep** [comment]
Some of the indentation looks off, and you should be able to get the admin port from the config file. 

Otherwise makes sense. We can easily address the issues post merge if necessary.

**Comment by otoolep** [comment]
Oh, don't use "self". Not Go style. 

----------------------------------
http://www.philipotoole.com

**Comment by toddboom** [comment]
@otoolep Yeah, I mainly wanted to make sure it would come up regardless of the config for now. I'll make sure it's configurable for rc3.

**Comment by toddboom** [comment]
Everything is green, self-merging. :guitar: :dancer:

**Pull request merged**
