### PR TITLE
Fix backup and restore functionality

### LINKED ISSUE #3700: [master] Panic when trying to backup data
Hello,

Using current master (deabf8d2a8e60e701c32302b569a1006ba378ee5) I get a panic when using the command ```influxd backup mybackup```

Full output is here https://gist.github.com/papylhomme/59b2b830a6b7bb6af195

### PR DESCRIPTION
**Pull request by Pomyk**
Fixes #3700 #3923

### CODE REVIEW

**Comment by Pomyk** [comment]
- [x] CHANGELOG.md updated
- [x] Rebased/mergable
- [x] Tests pass
- [x] Sign [CLA](http://influxdb.com/community/cla.html) (if not already signed)

I didn't fix the backup/restore test.

**Comment by esecules** [comment]
will this land for 0.9.5?

**Comment by beckettsean** [comment]
@esecules 0.9.5 will not ship unless backup/restore works. No opinion on this particular PR, but @pauldix himself promised me backup would get the needed attention before 0.9.5 final is cut.

**Comment by saward** [comment]
Glad to hear that, since backup is a tad bit important ;)

**Comment by beckettsean** [comment]
@saward backups are nice, but it's the restore that counts ;)

**Comment by mjabrandao** [comment]
Hi, backups can be done to an AWS S3 bucket?

**Comment by OndroNR** [comment]
@mjabrandao we plan to do backups to S3 via s3fs mounting after the 0.9.5 is released.

**Comment by otoolep** [comment]
I actually believe we covered this in another PR.

Thanks for your contribution @Pomyk -- let us know if you do not think we're OK now.

**Comment by ORANGE-XFM** [comment]
@beckettsean Hi, I don't find this change it in Changelog, will backups be corrected with another PR ?
(I only see the #4643 restore-related bugfix).

**Comment by beckettsean** [comment]
@ORANGE-XFM there were too many issues with `tsm1` for it to be declared production ready, but there were also too many accumulated bug fixes and performance improvements to delay 0.9.5 any longer. While the intention was to only release it once `tsm1` and backups were working, that proved too optimistic.

**Comment by OndroNR** [comment]
@beckettsean So we have no working backup right now? That must be written in docs.

**Comment by ORANGE-XFM** [comment]
@beckettsean Hi Sean, in fact my point was that we shoudl state in the changelog that this issue seems to have been fixed indeed ! (communicating that backups are working in the changelog)

**Comment by OndroNR** [comment]
Has somebody verified working backups in 0.9.5 stable with same dataset (which failed on <=0.9.4)?

**Comment by ORANGE-XFM** [comment]
I succeeded backing up a DB with 0.9.5 which failed in 0.9.4.2, but that may not be a good validation for something as important as backups.

**Comment by bentimms** [comment]
The restore is still not working for me with 0.9.5 stable, as per #4806

**Comment by pauldix** [comment]
The only way to currently back up the DB is to copy the underlying files. Meaning to do it safely, it's offline only. This slipped because the new storage engine is still under development and we were going to put this there.

However, we may be able to take a look at this sooner for the older storage engines. I'll leave #4806 open and we can go from there.

**Pull request closed without merging**
