### PR TITLE
remove boring log in collectd.go

### PR DESCRIPTION
**Pull request by kylezh**
Signed-off-by: Kai Zhang <kyle@smartx.com>

### CODE REVIEW

**Comment by otoolep** [comment]
Thanks @kylezh -- have you signed the CLA?

**Comment by kylezh** [comment]
@otoolep 
Yes, I have signed that.

**Comment by otoolep** [comment]
OK, thanks.

@corylanou -- this should be merged, agreed?

**Comment by corylanou** [comment]
+1, clearly debug to begin with.

**Comment by otoolep** [comment]
Thanks @kylezh

**Pull request merged**
