### PR TITLE
Move Raft command types to own file

### PR DESCRIPTION
**Pull request by otoolep**

### CODE REVIEW

**Comment by otoolep** [comment]
Looking for comment, and approval to merge, from the team.

**Comment by benbjohnson** [comment]
I'm not sure this make it more clear. Previously the commands were next to the functions that processed them. I'll defer to @pauldix though.

**Comment by otoolep** [comment]
@benbjohnson -- you may be right. In that case, I think I need to scan through the file to make sure there is consistency, some places may not quite be adhering to that convention. If that helps, I'm up for that too. But this file is beginning to feel like a wall of source code. :-)

Definitely looking for consensus here.

**Comment by pauldix** [comment]
I think I like the idea of having the commands in their own file. Server is getting a bit unwieldy and this will help a bit. I feel like Sublime hates me when I open up a 3k line file.

**Comment by corylanou** [comment]
I'm always a fan of more files than less, so +1 from me!

**Comment by otoolep** [comment]
You missed your calling as a Java programmer then, @corylanou :-)

**Comment by otoolep** [comment]
+1 from @toddboom

**Comment by otoolep** [comment]
Closing this and will re-do.

**Pull request closed without merging**
