### PR TITLE
Use github.com/codegangsta/cli for influx cli

### PR DESCRIPTION
**Pull request by apoydence**
This will make the CLI a little cleaner.

### CODE REVIEW

**Comment by corylanou** [comment]
Sorry, didn't see you had a second one in play.  Same comments:

@apoydence Thanks for the PR. We are trying to use as few third party dependancies as we can in this project, so we purposefully didn't use a third party API.

If this becomes too unwieldy in the future, we'll likely hand roll our own encapsulation, as we don't have that heavy of a use case yet.

Additionally, I do like to use these code libraries in some of my other projects, I'm just not sure we are ready to use it here yet.

I agree it does clean up some things.

**Comment by apoydence** [comment]
Sorry, the first one had a careless mistake.  I understand not wanting
third party code. I'll keep that in mind for any future PR.

**Comment by otoolep** [comment]
Yeah, we're trying to stick with standard libs as @corylanou explained.

**Comment by toddboom** [comment]
Closing this out since we're not planning to pull in the external library.

**Pull request closed without merging**
