### PR TITLE
CLI: Add `INSERT` and `INSERT INTO` for writing points

### PR DESCRIPTION
**Pull request by gunnaraasen**

### CODE REVIEW

**Comment by jwilder** [comment]
Cool.  The `default` retention policy hard coding didn't work for me though.  

Maybe two version of the `insert` statement could be supported to work around that?

`insert cpu,host=serverA value=1.0` would not set a retention policy on the request and would use the default configured for the database.

`insert into <policy> cpu,host=serverA value=1.0` would use the retention policy `<policy>` for the write.

Could also extend that second one to include a db too with something like:

`insert into <db>.<policy> cpu,host=serverA value=1.0`

Also, might be nice to add a `measurement` keyword in there as well so the syntax would look like:
```
insert measurement cpu,host=serverA value=1.0
insert into myrp measurement cpu,host=serverA value=1.0
insert into mydb.myrp measurement cpu,host=serverA value=1.0
```

**Comment by gunnaraasen** [comment]
The `default` retention policy is not currently being created automatically. See #2791.

:+1: `INSERT INTO <db>.<rp>` I'll add that in.

I'm not sold on `measurement`. Seems like unnecessary characters since points are the only thing that can be inserted.

**Comment by gunnaraasen** [comment]
@jwilder tests added. I also cleaned up the `INTO` parsing code. It still splits strings but is hopefully easier to follow.

**Comment by pauldix** [comment]
LGTM :ship:

**Comment by jwilder** [comment]
:+1:

**Comment by toddboom** [comment]
+ :100:

**Comment by corylanou** [comment]
Awesome work!

**Pull request merged**
