### PR TITLE
Add an aggregation function for integration using Riemann sums.

### PR DESCRIPTION
**Pull request by michaelsproul**
I'd really like an integration aggregation function, so I've written one. At present it only works for `float64` values. Some help making this idiomatic Go would be appreciated. I rarely write Go and don't know all the best practices for dealing with `interface{}`.

Another thing up for discussion is how to deal with the (physical) time unit used during integration. Timestamps are stored as nanoseconds but it seems impractical to make people always deal with for example `W ns` values when integrating power (`W`) over time. For now I've just made the integration unit seconds.

Also up for discussion is what type of Riemann sum to use. At the moment this is a **left Riemann** sum, as that makes the most sense for my particular data-set. The way I see it is that the value stored at a given timestamp would generally *persist* until the next point is inserted. This makes the area of a single block:

```
A_i = v_i * (t_(i + 1) - t_i)
  for 0 <= i <= n - 2

# Or equivalently (the version used in the mapping code):
A_i' = v_(i - 1) * (t_i - t_(i - 1))
  for 1 <= i <= n - 1
```

See: https://en.wikipedia.org/wiki/Riemann_sum

Addresses #1400

Happy to sign whatever if you decide to merge this. Thanks!

### CODE REVIEW

**Comment by beckettsean** [comment]
@mjdesa can you vet the math, please?

**Comment by mjdesa** [comment]
@beckettsean all the math checks out.

My only concern is that the method uses seconds as its unit interval. Ideally the unit should be set by the user.

Any thoughts @toddboom

**Comment by michaelsproul** [comment]
I noticed another problem with my approach - cutting a large interval into chunks misses the area between the end of one chunk and the start of the next. I've fixed this in the most recent commit.

Other things I still need to do:

- [ ] Prevent panics when the type of the field being integrated over isn't numeric.
- [ ] Add a paramater to `integral` so you can do for example: `integral(field, 1s)` to integrate with seconds.

**Comment by michaelsproul** [comment]
Ok, I haven't fixed the panics for integration badly typed expressions but I suspect that should be solved in a general way (#3353).

I'm not sure why the tests are failing...

**Comment by otoolep** [comment]
@michaelsproul -- from out the test output:
```
=== RUN TestInitializeMapFuncPercentile
--- FAIL: TestInitializeMapFuncPercentile (0.00s)
panic: runtime error: index out of range [recovered]
	panic: runtime error: index out of range

goroutine 10 [running]:
testing.funcÂ·006()
	/usr/local/go/src/testing/testing.go:441 +0x249
github.com/influxdb/influxdb/influxql.InitializeMapFunc(0xc20803d3b0, 0xa25ee8, 0x0, 0x0)
	/home/ubuntu/influxdb-build/src/github.com/influxdb/influxdb/influxql/functions.go:51 +0x1797
github.com/influxdb/influxdb/influxql.TestInitializeMapFuncPercentile(0xc208032750)
	/home/ubuntu/influxdb-build/src/github.com/influxdb/influxdb/influxql/functions_test.go:80 +0x11f
testing.tRunner(0xc208032750, 0xa1cd20)
	/usr/local/go/src/testing/testing.go:447 +0x134
created by testing.RunTests
	/usr/local/go/src/testing/testing.go:555 +0xd4e

goroutine 1 [chan receive]:
testing.RunTests(0x945dd0, 0xa1ccc0, 0x2f, 0x2f, 0xa1ee01)
	/usr/local/go/src/testing/testing.go:556 +0xdc3
testing.(*M).Run(0xc20802e0f0, 0xa25940)
	/usr/local/go/src/testing/testing.go:485 +0xe1
main.main()
	github.com/influxdb/influxdb/influxql/_test/_testmain.go:152 +0x28d
FAIL	github.com/influxdb/influxdb/influxql	0.018s
=== RUN TestConfig_Parse
```

**Comment by otoolep** [comment]
https://circle-artifacts.com/gh/influxdb/influxdb/4198/artifacts/1/tmp/circle-artifacts.9dMRvTF/test_logs_race.txt for full details.

**Comment by michaelsproul** [comment]
@otoolep: So the failure is due to me removing some redundant code in `InitializeMapFunc` for checking that aggregates are given the right number of arguments. I took it out because I found the exact same logic duplicated in `validateAggregates`. The test only fails because it calls `InitializeMapFunc` directly. Would you prefer that I leave the redundant code in so that the test passes or remove the test entirely?

**Comment by michaelsproul** [comment]
I should add some tests for `integral` too...

**Comment by otoolep** [comment]
Please remove it, we don't have an objection to removing dead code.

**Comment by michaelsproul** [comment]
- [ ] CHANGELOG.md updated
- [ ] Rebased/mergable
- [ ] Tests pass
- [ ] Sign [CLA](http://influxdb.com/community/cla.html) (if not already signed)

**Comment by otoolep** [comment]
Thanks @michaelsproul -- there are no tests however. Can you add some? Otherwise we will not catch any regressions. You could add them somewhat like this:

https://github.com/influxdb/influxdb/blob/master/cmd/influxd/run/server_test.go#L1206

**Comment by otoolep** [comment]
Can you also move this CHANGELOG entry to 0.9.3? This is unlikely to ship in 0.9.2, since feature-freeze has passed for 0.9.2.

**Comment by michaelsproul** [comment]
Ah, perfect, was looking for the high-level tests. I'll add some and bump the version :smile:

**Comment by michaelsproul** [comment]
Ok, I've written some tests but I seem to be getting some really weird behaviour. In the test called `eleven point integral` (actually 10 points) the map function seems to get called with an empty iterator. I've changed the aggregate function to `count` for testing purposes and it behaves the same...

On my local machine (more clearly than in the interleaved CircleCI output), you can see there's only one empty partition for the map function to act on:

```
# This is the single point, it passes.
NEW QUERY
FIRST VALUE IS:  86400000000000 100
ONLY ONE VALUE 0 <nil>
[]interface {}{influxql.chunkIntegral{Area:0, StartTime:8.64e+13, EndTime:8.64e+13, EndValue:100}}
REDUCING 1 CHUNKS
# This is the two point, it passes.
NEW QUERY
FIRST VALUE IS:  86400000000000 100
computed the area of the first block
[]interface {}{influxql.chunkIntegral{Area:1000, StartTime:8.64e+13, EndTime:8.641e+13, EndValue:200}}
REDUCING 1 CHUNKS
# This is the "eleven" point, it fails.
NEW QUERY
MapCount called
ReduceSum called on  [<nil>]
[snapshot] 2015/07/22 17:35:14 snapshot listener closed
--- FAIL: TestServer_Query_Integral (1.12s)
	server_test.go:1324: input does not match format
	server_test.go:1327: integration test failed: eleven point integral
		expected: 10000.000000 actual: 0.000000
		query: SELECT count(value) FROM db0.rp0.power WHERE time >= 86440s AND time <= 86516s
		response: {"results":[{"series":[{"name":"power","columns":["time","count"],"values":[["1970-01-02T00:00:12Z",null]]}]}]}
```

**Comment by michaelsproul** [comment]
I thought it was possibly the retention policy, but I've tried 0 (infinite?) and very large values without it making any difference.

**Comment by michaelsproul** [comment]
@mjdesa, @beckettsean, @otoolep: Any ideas? I feel like this is so close to working that it's worth pursuing.

**Comment by beckettsean** [comment]
@mjdesa and I are on the support team, we aren't particularly qualified to review code for a PR. @otoolep is unavailable for a few weeks.

I've asked @pauldix to take a quick look, but the whole core team is heads-down on a just discovered query locking issue that's preventing us from cutting 0.9.2 final. Once that logjam is unblocked expect some attention from core devs on this PR.

**Comment by michaelsproul** [comment]
Ok great! Thanks for the update! I can sit tight for a bit, no worries :)

**Comment by pauldix** [comment]
@michaelsproul I fixed an odd bug on Friday that might have caused the problem you were seeing. Can you test again and resolve the merge conflict?

**Comment by michaelsproul** [comment]
Unfortunately the same problem remains. Although I'm glad the Iterator `Next` method now returns -1 to signal the end of the iterator.

**Comment by michaelsproul** [comment]
I'm using Postgres now instead, so I'll close this PR.

**Comment by hvries1** [comment]
Nice feature, but moving to Postgres seems to be the solution...

**Pull request closed without merging**
