### PR TITLE
Make the WAL cursor create a copy of the cache

### PR DESCRIPTION
**Pull request by pauldix**
I think this will fix the problem @jwilder and @jhorwit2 were mentioning about some inconsistent query results. Thoughts?

### CODE REVIEW

**Comment by otoolep** [comment]
@jwilder thinks it's possible this will fix https://github.com/influxdb/influxdb/issues/3725

**Comment by jhorwit2** [comment]
Should you also copy c on LOC 1303?

**Comment by pauldix** [comment]
@jhorwit2 `DedupeEntires` already does

**Comment by jhorwit2** [comment]
:+1:

**Comment by jwilder** [comment]
My counts are more stable w/ this change but still seem to be missing points until after everything is flushed.  Probably a separate issue though. :+1:

**Pull request merged**
