### PR TITLE
Disable 64bit tests properly

### LINKED ISSUE #3701: Tests failing on i386 and armhf
Hello,

The tests are failing on i386 and armhf. For the same reason.

```
=== RUN TestConfig_Parse
--- PASS: TestConfig_Parse (0.00s)
[collectd] 2015/08/11 16:32:32 collectd UDP started
[collectd] 2015/08/11 16:32:32 collectd UDP closed
--- PASS: TestService_CreatesDatabase (0.01s)
[collectd] 2015/08/11 16:32:32 collectd UDP started
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x4 pc=0x99284]

goroutine 17 [running]:
sync/atomic.addUint64(0x10764524, 0x1, 0x0, 0x1, 0x0)
	/usr/lib/go/src/sync/atomic/64bit_arm.go:31 +0x70
github.com/influxdb/influxdb/tsdb.func·002()
	/«BUILDDIR»/influxdb-0.9.2+dfsg1/obj-arm-linux-gnueabihf/src/github.com/influxdb/influxdb/tsdb/batcher.go:77 +0x1ec
created by github.com/influxdb/influxdb/tsdb.(*PointBatcher).Start
	/«BUILDDIR»/influxdb-0.9.2+dfsg1/obj-arm-linux-gnueabihf/src/github.com/influxdb/influxdb/tsdb/batcher.go:104 +0x2b8
```

Full logs are available here: https://buildd.debian.org/status/logs.php?pkg=influxdb&ver=0.9.2%2Bdfsg1-2
Related Debian bug: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=795640

Could that be related to https://github.com/influxdb/influxdb/issues/3213 ?

I'm happy to help however possible.

When this is fixed, we should enable those architectures on CircleCI. Those kind of issues are easier to fix when they are noticed early!

### PR DESCRIPTION
**Pull request by aviau**
I'll post here when I'm sure it works.

Closes  #3701

### CODE REVIEW

**Comment by otoolep** [comment]
@corylanou

**Comment by aviau** [comment]
@corylanou @otoolep 

Works for me!

I'll prepare a Debian upload for influxdb 0.9.2.1 and include that in.

**Comment by otoolep** [comment]
Tested on my amd64 machine that this test does run. +1 from me.

Nice work.

**Comment by otoolep** [comment]
Thanks again @aviau -- we actually decided to go with a simpler approach: https://github.com/influxdb/influxdb/pull/3734

But the technique you highlighted is very useful, and it's good to know it exists.

**Pull request closed without merging**
