### PR TITLE
RLock Server when checking retention policies

### PR DESCRIPTION
**Pull request by otoolep**

### CODE REVIEW

**Comment by otoolep** [comment]
Likely fixed for issue #1882 -- the change is needed in any event.

**Comment by otoolep** [comment]
Rebased and conflicts resolved.

**Comment by pauldix** [comment]
looks good. Guess it's hard to write a test for this kind of thing. :ship:

**Comment by dgnorton** [comment]
I think we need locking in the `apply*` functions while modifying the metastore.

**Comment by dgnorton** [comment]
Nevermind.  I forgot there was locking in `processor` before each apply function is called.

**Comment by otoolep** [comment]
Thanks for the review @pauldix, @dgnorton -- merging now.

**Pull request merged**
