### PR TITLE
interpret number literals compared against time as nanoseconds from epoch

### LINKED ISSUE #3719: [0.9.3 nightly] comparison operators on epoch timestamps always return true if no units supplied
There's something badly broken with comparison operators in the latest 0.9.3 nightly. 

Insert two points with small epoch timestamps (in seconds):

```
root@sean-test:~# curl -i -XPOST 'http://localhost:8086/write?db=foo&precision=s' --data-binary 'thing value=50 900'
HTTP/1.1 204 No Content
root@sean-test:~# curl -i -XPOST 'http://localhost:8086/write?db=foo&precision=s' --data-binary 'thing value=60 910'
HTTP/1.1 204 No Content
```

Select the points in the CLI:

```
> select * from thing
name: thing
-----------
time			value
1970-01-01T00:15:00Z	50
1970-01-01T00:15:10Z	60
```

Now it gets weird. This returns nothing, although it should at least return the first point

```
> select * from thing where time <= 900s
```

Now without the units, and it returns both points. Timestamp should be nanoseconds by default, but it doesn't matter what I use in the comparison, it always returns both points:

```
> select * from thing where time <= 900
name: thing
-----------
time			value
1970-01-01T00:15:00Z	50
1970-01-01T00:15:10Z	60

> select * from thing where time <= 9
name: thing
-----------
time			value
1970-01-01T00:15:00Z	50
1970-01-01T00:15:10Z	60

> select * from thing where time = 9
name: thing
-----------
time			value
1970-01-01T00:15:00Z	50
1970-01-01T00:15:10Z	60

> select * from thing where time = 9099099900999000990
name: thing
-----------
time			value
1970-01-01T00:15:00Z	50
1970-01-01T00:15:10Z	60
```

Using explicit seconds for the time behaves as expected:

```
> select * from thing where time =900s
name: thing
-----------
time			value
1970-01-01T00:15:00Z	50

> select * from thing where time = 910s
name: thing
-----------
time			value
1970-01-01T00:15:10Z	60

> select * from thing where time = 911s
> select * from thing where time >= 911s
> select * from thing where time >= 900s
name: thing
-----------
time			value
1970-01-01T00:15:00Z	50
1970-01-01T00:15:10Z	60

```

### PR DESCRIPTION
**Pull request by DanielMorsing**
fixes #3719

### CODE REVIEW

**Comment by DanielMorsing** [comment]
@beckettsean @otoolep

**Comment by otoolep** [comment]
Works for me. This warrants a CHANGELOG update IMHO.

**Comment by otoolep** [comment]
https://github.com/influxdb/influxdb.com/issues/229 to update the docs.

**Comment by otoolep** [comment]
+1 on the change.

**Pull request merged**
