### PR TITLE
Enhance openTSDB logging and stats

### PR DESCRIPTION
**Pull request by otoolep**

### CODE REVIEW

**Comment by otoolep** [comment]
Example log output:

`[opentsdb] 2015/09/09 13:17:25 TSDBServer: malformed line 'fgkjglkj' from 127.0.0.1:49102`

**Comment by otoolep** [comment]
@nathanielc @corylanou

**Comment by nathanielc** [comment]
What about the error on https://github.com/influxdb/influxdb/blob/opentsdb_bad_lines/services/opentsdb/service.go#L298 ?

Should this just be another `statTelnetBadTime` error?

**Comment by otoolep** [comment]
Missed that one @nathanielc -- I will fix that one too.

**Comment by otoolep** [comment]
@nathanielc -- I updated it. I also removed the leading `TSDBServer` in the log messages, since the logger is already configured with `opentsdb` as its prefix.

**Comment by nathanielc** [comment]
LGTM

**Comment by otoolep** [comment]
LGTM is GEFM -- merging on green.

**Pull request merged**
