### PR TITLE
Fix typos.

### PR DESCRIPTION
**Pull request by charleswhchan**
* meaining --> meaning
* communcation --> communication
* deterimine --> determine
* mistmatch --> mistmatch

### CODE REVIEW

**Comment by otoolep** [comment]
Thanks @charleswhchan -- have you signed the CLA?

**Comment by charleswhchan** [comment]
@otoolep: Thanks for the reminder. Done!

**Comment by otoolep** [comment]
CLA confirmed signed, comments only, merging now.

**Comment by charleswhchan** [comment]
Thanks. :+1:

**Pull request merged**
