### PR TITLE
wire up drop CQ statements

### LINKED ISSUE #2141: Continuous queries cannot be dropped
RC18 looks like it should have this functionality, but when I run a simple test on dropping a continuous query I get a 500 back.  I have a full shell example here:
https://gist.github.com/btashton/0ed2712c8738770238f5

### PR DESCRIPTION
**Pull request by neonstalwart**
fixes #2141

i can't say for sure if what i've wired up is doing the right thing but it appears to be working

### CODE REVIEW

**Comment by neonstalwart** [comment]
ping @toddboom

**Comment by toddboom** [comment]
@neonstalwart ha, that looks about right. nice catch! if you can sign the CLA, i'll get this merged in!
http://influxdb.com/community/cla.html

**Comment by neonstalwart** [comment]
@toddboom i signed the CLA this morning

**Comment by neonstalwart** [comment]
i signed again just in case it didn't work - let me know if there are any problems.

**Comment by toddboom** [comment]
@neonstalwart ah, sorry about that - i may have missed you on the list. merging now!

**Pull request merged**
