### PR TITLE
Fix 2599: add "epoch" URL param & return JSON time values as epoch numbers instead of date strings.

### PR DESCRIPTION
**Pull request by dgnorton**

### CODE REVIEW

**Comment by pauldix** [comment]
LGTM, :ship:

**Comment by toddboom** [comment]
+1

**Comment by neonstalwart** [comment]
why not make this symmetrical with `precision` for writing?  instead of `epoch`, call it `precision` and support `n`, `u`, `ms`, `s`, `m`, and `h` values.

**Comment by pauldix** [comment]
@neonstalwart supporting the same possible values makes sense. I wonder if precision is a little vague for this request though since what we're asking for is epochs instead of date/time strings. Precision could also be applied to the date/time strings to round them before sending the strings.

**Comment by neonstalwart** [comment]
@pauldix i think the reasons you have for not calling it `precision` are reasons why it's also not a good name when writing.  i don't hold strongly to what the name is but i think having symmetry of the name and the values for reading and writing is helpful for consumers of the API.

**Comment by neonstalwart** [comment]
in the interest of moving forward... keeping the default value consistent and values consistently named (even if you don't support all of them) would be my bottom line.  so, `us` -> `u` and seconds as the default.

**Comment by pauldix** [comment]
@neonstalwart yeah, the tricky thing about the input vs. the output is that when reading the data we can tell if it's an epoch or a date/time string. So precision applies to both. For output they have to specify what they want. We could almost split this into two params for the output: `precision` and `time_format=<epoch | RFC3339Nano>`

But I agree that having symmetry on the input/output side makes the API easier to understand.

**Comment by neonstalwart** [comment]
i don't want to hold this up from being merged.  i'm in favor of merging it as it is now and then seeing if anyone else wants to offer opinions later.

**Comment by pauldix** [comment]
At the very least we should make the units consistent. @dgnorton, can you update so that the units are the same as in the write path for precision?

**Comment by neonstalwart** [comment]
> @dgnorton, can you update so that the units are the same as in the write path for precision?

he did that already :wink:

**Comment by pauldix** [comment]
oh, haha ok then. :shipit: !

**Comment by toddboom** [comment]
+1

**Pull request merged**
