### PR TITLE
Fix a number of issues in sysV init script.

### PR DESCRIPTION
**Pull request by miguelcnf**
When using the sysV init script the service actions return codes were not being properly set.

What this means is that the init script would return successfully even when, for instance, it failed to load the configuration and the process wasn't left running.

As the influx process doesn't fork itself we're waiting for the pid file to be created and checking the status of the process afterwards.

### CODE REVIEW

**Comment by otoolep** [comment]
Thanks @miguelcnf -- we'll take a look. Have you signed the CLA?

**Comment by miguelcnf** [comment]
Hi @otoolep, I have now! :)

Also, just pushed a couple more fixes, mainly the ability to run as a non-root user.

**Comment by otoolep** [comment]
I tested this, and it looks good. +1

**Comment by otoolep** [comment]
Failure to launch looks good:
```
root@script-test:~# service influxdb start
Starting the process influxd [ OK ]
influxd process failed to start [ FAILED ]
root@script-test:~# echo $?
1
```

**Comment by jwilder** [comment]
LGTM :+1:

**Comment by otoolep** [comment]
Thanks @miguelcnf

**Comment by miguelcnf** [comment]
Thanks!

**Pull request merged**
