### PR TITLE
Use "value" as the field name also in graphite

### PR DESCRIPTION
**Pull request by cannium**
#2412 says it's fixed but actually not.

### CODE REVIEW

**Comment by liyichao** [comment]
Yeah, it's not fixed.

**Comment by otoolep** [comment]
Thanks @cannium -- the tests also need to be updated. Can you do that? If not, I will do so.

**Comment by otoolep** [comment]
Specifically:
```
--- FAIL: Test_ServerSingleGraphiteIntegration_NoDatabase (3.29s)
	server_integration_test.go:1944: Graphite Connection String: 127.0.0.1:0
	server_integration_test.go:88: Creating cluster of 1 nodes for test graphite integration
	server_integration_test.go:97: Test graphite integration: using tmp directory "/tmp/influxdb-804192646/broker-integration-test" for brokers
	server_integration_test.go:98: Test graphite integration: using tmp directory "/tmp/influxdb-804192646/data-integration-test" for data nodes
	server_integration_test.go:136: http://:37585
	server_integration_test.go:1971: Writing data
	server_integration_test.go:1986: Test "graphite integration" failed, expected: {"results":[{"series":[{"name":"cpu","columns":["time","cpu"],"values":[["2015-05-12T22:38:35Z",23.456]]}]}]}, got: {"results":[{"series":[{"name":"cpu","columns":["time","value"],"values":[["2015-05-12T22:38:35Z",23.456]]}]}]}
```
and perhaps a couple others.

**Comment by cannium** [comment]
I fixed the tests, but I seems to hit some other bug. @otoolep Any ideas?

**Comment by otoolep** [comment]
That's a known issue, we're tracking down. https://github.com/influxdb/influxdb/issues/2517

I kicked the build, let's see if it goes green.

**Comment by otoolep** [comment]
@corylanou -- can you also review?

**Comment by otoolep** [comment]
+1 from me, on green build -- thanks @cannium

**Comment by corylanou** [comment]
Looks good. +1.  Thanks!

**Comment by toddboom** [comment]
@cannium thanks!

**Pull request merged**
