### PR TITLE
Also print the broker path.

### PR DESCRIPTION
**Pull request by gst**
So to know/see where it's actually located.

### CODE REVIEW

**Comment by gst** [comment]
This had beat me (a bit) when I've updated latest commits and I forgot that by default the broker is stored in /tmp/influxdb/dev..

**Comment by otoolep** [comment]
Thanks @gst -- can you please sign the CLA?

**Comment by gst** [comment]
where is it ? :p

**Comment by gst** [comment]
> where is it ? :p

ok I found and signed it.

**Pull request merged**
