### PR TITLE
Wait for Raft leader even when cluster exists

### PR DESCRIPTION
**Pull request by otoolep**

### CODE REVIEW

**Comment by otoolep** [comment]
@benbjohnson -- how about this?

**Comment by pauldix** [comment]
good for now, :ship:

**Comment by otoolep** [comment]
@benbjohnson -- we'll need your input on this. Without it the input plugins couldn't auto-create their databases. This means there is a leader before any services are opened.

**Comment by benbjohnson** [comment]
@otoolep I think the services should not assume that there's a leader. Each one should run periodically and check if it is the leader and process if it is. You could have a 3 node cluster where it takes some one a while to get two nodes up and running.

**Comment by otoolep** [comment]
@benbjohnson -- to be clear, this is not about a specific node being leader, it's about the cluster having any leader. Certain services -- graphite for example -- cannot proceed until there is a least 1 leader.

I support an alternative approach is spin in the services, trying to perform operations like create the target database, and if no leader comes back, just retrying?

**Pull request merged**
