### PR TITLE
Fix CQ example on InfluxQL spec

### PR DESCRIPTION
**Pull request by pauldix**

### CODE REVIEW

**Comment by otoolep** [comment]
Strange test failure:
```
--- FAIL: TestHandler_RetentionPolicies (0.02s)
	handler_test.go:307: Missing retention policy: {"results":[{"series":[{"columns":["name","duration","replicaN","default"],"values":[["bar","168h0m0s",1,false],["default","0",1,true]]}]}]}
```
Kicked the build.

**Comment by otoolep** [comment]
+1 on the doc change.

**Comment by otoolep** [comment]
Hang on -- you've added a binary to the commit. Let me see if I can tweak our `.gitignore` to fix this.

**Comment by otoolep** [comment]
https://github.com/influxdb/influxdb/commit/14f768d10cc37db3f38a3a0c1553287a381d6a1b now means `influx` will be ignored.

**Comment by pauldix** [comment]
ah annoying. Heh. Good to merge?

**Comment by otoolep** [comment]
Good to merge once you remove the addition of  `cmd/influx/influx`.

**Comment by pauldix** [comment]
ugh, ok done. Don't know why it came through as a new commit. I tried to do it as an amend.

**Comment by toddboom** [comment]
I think this is good, so I'm merging.

**Pull request merged**
