### PR TITLE
Give a seed to rand to make it really random

### PR DESCRIPTION
**Pull request by cannium**

### CODE REVIEW

**Comment by otoolep** [comment]
Before this can be merged @cannium , can you sign the CLA?

http://influxdb.com/community/cla.html

**Comment by cannium** [comment]
Signed.

**Comment by otoolep** [comment]
Makes sense to me. 

@benbjohnson ?

**Comment by benbjohnson** [comment]
:+1:

**Comment by otoolep** [comment]
Thanks @cannium

**Pull request merged**
