### PR TITLE
Export functionality for 0.8 branch

### PR DESCRIPTION
**Pull request by corylanou**
This PR will address issue https://github.com/influxdb/influxdb/issues/2378

## Design

This is phase 1 of 2.  This is the `export` function that users of `0.8` need to upgrade to.

Phase one exports raw data from `0.8` to a flat file that includes two sections, `DDL` and `DML`.  You can choose to export them independently (see below).

The `DDL` section contains the sql commands to create databases and retention policies.  the `DML` section is [line protocol](https://github.com/influxdb/influxdb/blob/master/tsdb/README.md) and can be directly posted to the [http endpoint](https://influxdb.com/docs/v0.9/guides/writing_data.html) in `0.9`.  Remember that batching is important and we don't recommend batch sizes over 5k.

You will specify a database and shard group when you export.  This will be done from the `0.8.9` branch that users will have to upgrade to.

To list out your shards, use the following http endpoint:

`/cluster/shard_spaces`

example:
```sh
http://username:password@localhost:8086/cluster/shard_spaces
```

Then, to export a database with then name "metrics" and a shard space with the name "default", issue the following curl command:

```sh
curl -o export http://username:password@http://localhost:8086/export/metrics/default
```

Compression is supported, and will result in a significantly smaller file size.  Use the following command for compression:

```sh
curl -o export.gz --compressed http://username:password@http://localhost:8086/export/metrics/default
```

You can also export just the `DDL` with this option:

```sh
curl -o export.ddl http://username:password@http://localhost:8086/export/metrics/default?l=ddl
```

Or just the `DML` with this option:

```sh
curl -o export.dml.gz --compressed http://username:password@http://localhost:8086/export/metrics/default?l=dml
```

## Assumptions

- Series name mapping follows these [guidelines](https://influxdb.com/docs/v0.8/advanced_topics/schema_design.html)
- Database name will map directly from `0.8` to `0.9`
- Shard Space to Retention Policy mapping
    - Shard Space Duration is ignored, as in `0.9` we determine shard size
    - Regex is used to match the correct series names and only exports that data for the database
    - Duration becomes the new Retention Policy duration

- Users - Not migrating due to inability to get passwords.  Anyone using users will need to manually set these back up in `0.9`

This PR replaces https://github.com/influxdb/influxdb/pull/3001/

### CODE REVIEW

**Comment by pauldix** [comment]
A lot here, but based on conversations I think this is good to go. Let's get 0.8.9 cut and get everybody exporting their data!

**Comment by beckettsean** [comment]
@corylanou a few questions:

So it looks like the export stuff is a straight `curl` call, with the `-o` flag to name the file where STDOUT redirects. The basic auth stuff is standard, as is the URL and port. 

1. To use `http://username:password@localhost:8086/cluster/shard_spaces` do I hit that in a browser, or curl the URL, or do both work?
1. Are the export commands really 
`curl -o export http://username:password@http://localhost:8086/export/metrics/default`
or should it be
`curl -o export http://username:password@localhost:8086/export/metrics/default`
1. Only one shard space at a time, no regexes or wildcards allowed, I assume?
1. The endpoint is _always_ `export/<database>/<shard_space>`?
1. Presumably we URL-escape `database` and `shard_space` parameters. Is there any parser to deal with other than URL encoding/decoding?
1. DDL output will be executable queries valid for the 0.9 `/query` endpoint? 
1. If I do DDL and DML at the same time I assume the DDL commands are at the beginning of the file? 
1. If the DDL does to `/query` and the DML goes to `/write`, what's the reason I would ever run 
`curl -o myfile http://localhost:8086/export/mydb/default`
instead of 
`curl -o myfile http://localhost:8086/export/mydb/default?l=ddl`
`curl -o myfile http://localhost:8086/export/mydb/default?l=dml`
since I have to manually separate the former into files for passing to 0.9?
1. Presumably the query string parameters, ddl and dml, are case insensitive?

@toddboom can the query endpoint move in 0.8.x? Are there servers out there where 8086 is not the port in use? If so, what do we call that port?

@corylanou since the `export` endpoint is new, will it always be at 8086 for 0.8.9 upgrades or will it inherit port settings from elsewhere, if such a thing is set?

**Comment by beckettsean** [comment]
I see from the code that the answer to #9 is yes, they are case insensitive.

I notice we're also lowercasing the shard spaces when comparing. @toddboom was it legal to have `Shard_space` and `shard_Space` on the same database, or were they stored case-insensitive and would collide on creation? (I ask because in 0.9 most identifiers are case-sensitive)

**Comment by beckettsean** [comment]
@corylanou can you respond to the questions in https://github.com/influxdb/influxdb/pull/3477#issuecomment-125773274?

**Comment by beckettsean** [comment]
@corylanou had a chat yesterday with @toddboom and @pauldix about the export/import flow.

Are the points output from 0.8.9 in FIFO or LIFO? When writing them into the new 0.9.3 db most users will want the most recent points first, with the others being less relevant. We should make it easy to import the newest ones first, although in batches that are chronological not reverse chron.

**Comment by beckettsean** [comment]
@corylanou do we output all 0.8.9 values as float64? If not, does the export use the new integer line protocol format for integers?

**Comment by corylanou** [comment]
- To use `http://username:password@localhost:8086/cluster/shard_spaces` do I hit that in a browser, or curl the URL, or do both work?

> Both should work

- Are the export commands really 
`curl -o export http://username:password@http://localhost:8086/export/metrics/default`
or should it be
`curl -o export http://username:password@localhost:8086/export/metrics/default` (note the repeated `http` in the first one, which exists in all four of your examples)

> the latter ones.  The duplicate `http` is a typo.

- Only one shard space at a time, no regexes or wildcards allowed, I assume?

> Correct.  The way shard spaces worked in `0.8.x` is that they used a regex when writing to determine the proper shard space to write to.  So, the easiest way to export that data is one shard space at a time.

- The endpoint is _always_ `export/<database>/<shard_space>`?

> Correct

- Presumably we URL-escape `database` and `shard_space` parameters. Is there any parser to deal with other than URL encoding/decoding?

> No

- DDL output will be executable queries valid for the 0.9 `/query` endpoint? 

> Correct

- If I do DDL and DML at the same time I assume the DDL commands are at the beginning of the file? 

> Correct

- If the DDL goes to `/query` and the DML goes to `/write`, what's the reason I would ever run 
`curl -o myfile http://localhost:8086/export/mydb/default`
instead of 
`curl -o myfile http://localhost:8086/export/mydb/default?l=ddl`
`curl -o myfile http://localhost:8086/export/mydb/default?l=dml`
since I have to manually separate the former into files for passing to 0.9?

> There is a new import command line to take the entire combined/compressed import
` influx -import -path=metrics-default.gz -compressed`.
> Also, we are trying to offer flexibility in the import.  Many design changes have happened between `0.8.x` and `0.9.x` and as such, I don't want to force them down a specific path.  There may be scenarios where they want the DDL so that they can change the defaults for retention policy, etc. before importing.

- Presumably the query string parameters, ddl and dml, are case insensitive?

> Correct

- The `--compressed` flag is the only optional flag, `-o` is the only required flag, and both are `curl` built-ins

> None of them are required.  These are simply examples for usage with curl.  If you didn't use either you can pipe the results of curl to your own file, through your own compression, etc.  However, I'm assuming the examples I provided are the most common paths that users will take.

- since the `export` endpoint is new, will it always be at 8086 for 0.8.9 upgrades or will it inherit port settings from elsewhere, if such a thing is set?

> It uses the same config that the http api uses, so if you reconfigure the http api to use a different port, it will also move the export endpoint.

- Are the points output from 0.8.9 in FIFO or LIFO? When writing them into the new 0.9.3 db most users will want the most recent points first, with the others being less relevant. We should make it easy to import the newest ones first, although in batches that are chronological not reverse chron.

> The data will come out in chronological order from oldest to newest.  Therefore when importing the data it will start importing from the latest.  I think this is correct though for the best performance in importing.  I believe if you import in reverse order, we will take a performance hit, but not sure.  @benbjohnson would be able to answer that better as he just finished writing the compression for storage.

- do we output all 0.8.9 values as float64? If not, does the export use the new integer line protocol format for integers?

> The line protocol change came after this PR was finished.  As such, I do have to do another PR now it appears to update this properly.

**Comment by beckettsean** [comment]
@corylanou thanks for the responses. I edited your original comment to remove the spurious `http://`s from the `curl` examples.

>  I believe if you import in reverse order, we will take a performance hit

Definitely true, but what I was thinking was something of a hybrid. I think it's just a matter of explaining to users how best they should chunk up and order their writes

I am assuming our recommended upgrade path is as follows, please let me know if my assumptions are wrong:

1. set up 0.9.3 cluster
1. point new writes to the 0.9.3 cluster
1. shut down 0.8.x cluster
1. install 0.8.9 on top of existing 0.8.x
1. restart 0.8.9 cluster
1. wait for all log activity to settle down (WAL flushed, etc.)
1. run export commands
1. load exported data into 0.9.3 cluster

For the last step, users will want to see the most recent data first, so the last points written to the 0.8.x cluster are the first that should be imported to the 0.9.3 cluster. However, you are right that reverse chron writes are non-performant. So how about this:

Assume I have 50k points and will write in 5k batches. I want my most recent points to load first so they are accessible to my users again. My export file has the points in this order, higher numbers being more recent points:

```
1
2
3
...
49998
49999
50000
```

I have to manually chunk it into 5k batches for writes. I'll end up with batches like this:

batch 1 | batch 2 | batch 9 | batch 10 
---- | ---- | ---- | ----
1 | 5001 | 40000 | 45001
2 | 5002 |  40001 | 45002
3 | 5003 |  40002 | 45003
... | ... | ...  | ...
4998 | 9998 |  44998 | 49998
4999 | 9999 | 44999 | 49999
5000 | 10000 | 45000 | 50000

I then pass the batches to the importer starting with batch 10, then batch 9, then batch 8, etc. So I'm loading the batches in reverse chron, but the points in the writes are in chronological order for better write performance.

I think that's the optimal strategy and I'm wondering if there's any reason to alter the export output to make it easier. I think probably not, but maybe there's something I'm missing.

**Pull request merged**
