### PR TITLE
return no content status (204) for succesful write

### PR DESCRIPTION
**Pull request by neonstalwart**
since write returns nothing in the body of the response, return 204

related to #2266

### CODE REVIEW

**Comment by neonstalwart** [comment]
i got caught... for some reason i can't get the tests running locally :smile: (looking at it now)

**Comment by otoolep** [comment]
I suspect we'll end up soon outputting some data in response to a write, so this might be premature.

**Comment by neonstalwart** [comment]
> this might be premature.

no problem.  if determining what to provide in the response is something you think you will get around to doing later but don't have time for now, then maybe having an open issue will help make sure it doesn't get overlooked.  i had opened #2266 to try and determine what you might like to respond with because if you can give some direction, i might be able to implement it.  however, when #2266 was closed, i was left the impression that an empty response is what it will be for now so i made this PR to do the right thing for an empty response.

maybe this PR could be merged in case you don't get around to deciding what to respond with before you release 0.9.0?  maybe you don't agree with these changes for an empty response?  i don't mind closing this PR but i'd like to help on providing some kind of better response than what is currently provided.

**Comment by toddboom** [comment]
@neonstalwart would you mind rebasing this?

**Comment by neonstalwart** [comment]
@toddboom rebased.

**Comment by toddboom** [comment]
@neonstalwart awesome - thanks!

**Comment by contentfree** [comment]
This seems to now to be broken according to [RFC7320](http://tools.ietf.org/html/rfc7230#section-3.3.1)

> A server MUST NOT send a Transfer-Encoding header field in any response with a status code of 1xx (Informational) or 204 (No Content).

The server still seems to be sending back the header `transfer-encoding: chunked` which it should not. This can cause problems with many HTTP libraries as well as several servers. Visit [this stackoverflow question for more info](http://stackoverflow.com/questions/912863/is-an-http-application-that-sends-a-content-length-or-transfer-encoding-with-a-2).

**Comment by romikk** [comment]
Could someone update docs here?
https://influxdb.com/docs/v0.9/concepts/reading_and_writing_data.html
At the moment it says successful write would return HTTP 200 OK

**Comment by beckettsean** [comment]
@romikk Thanks for the note, I opened an issue on the website repo: https://github.com/influxdb/influxdb.com/issues/62

**Comment by beckettsean** [comment]
No longer sending a `transfer-encoding` value:

```
$  curl -iv -XPOST 'http://localhost:8086/write?db=mydb' --data-binary 'foo value=12';
*   Trying ::1...
* Connected to localhost (::1) port 8086 (#0)
> POST /write?db=mydb HTTP/1.1
> Host: localhost:8086
> User-Agent: curl/7.43.0
> Accept: */*
> Content-Length: 12
> Content-Type: application/x-www-form-urlencoded
> 
* upload completely sent off: 12 out of 12 bytes
< HTTP/1.1 204 No Content
HTTP/1.1 204 No Content
< Request-Id: 6162708c-5d8f-11e5-8771-000000000000
Request-Id: 6162708c-5d8f-11e5-8771-000000000000
< X-Influxdb-Version: 0.9.4.1
X-Influxdb-Version: 0.9.4.1
< Date: Thu, 17 Sep 2015 22:56:50 GMT
Date: Thu, 17 Sep 2015 22:56:50 GMT

< 
* Connection #0 to host localhost left intact
```

**Pull request merged**
