### PR TITLE
Count with fill(none) will drop 0 valued intervals

### LINKED ISSUE #5042: fill(none) does not apply to count()
I have this query
```
select count(value) from event where time > now() - 1d and time < now() group by time(1m) fill(none)
```
And the result has 1440 records even for those empty intervals
If I change the query to
```
select count(value),max(value) from event where time > now() - 1d and time < now() group by time(1m) fill(none)
```
It will leave empty intervals out

So basically count() alone is not taken into account by fill(none).
But I believe it should have.

### PR DESCRIPTION
**Pull request by nathanielc**
Fixes #5042 

Simple fix and tests for fill and count.

### CODE REVIEW

**Comment by nathanielc** [comment]
@corylanou  or @otoolep look good?

**Comment by otoolep** [comment]
+1. 

@beckettsean - this will need a documentation update. Let us knowi if you need more info.

**Comment by beckettsean** [comment]
@otoolep we have no `COUNT()` specific docs about `fill`, so I think this is fine. It's undocumented now, although I've opened a new issue to better document fill.

**Comment by beckettsean** [comment]
@otoolep we have no `COUNT()` specific docs about `fill`, so I think this is fine. It's undocumented now, although I've opened a new issue to better document fill.

**Pull request merged**
