### PR TITLE
Add skeleton of new cluster-level query service

### PR DESCRIPTION
**Pull request by otoolep**

### CODE REVIEW

**Comment by otoolep** [comment]
This is the start of a layer that will service queries -- it operates at the level of a cluster. It will be the code that switches between querying shards that are local, and shards that will need calls to remote nodes.

https://github.com/influxdb/influxdb/issues/3009

**Comment by pauldix** [comment]
I'm not sure I understand why this is a service. The endpoints for getting a query from a coordinator node should be in the HTTP interface, maybe the regular handler?

The entire query engine should be contained in `tsdb`. I guess the only external part would be something on the `cluster` side that can return a struct that implements the `MapExecutor` or `Mapper` interface.

Basically, we need to run a `Map` task on each shard that needs to be hit in the query. The map task is something that is run through the  `Mapper` interface, which should look something like this:

```go
type Mapper interface {
  Begin(query *influxql.Statement) error
  NextChunk() (interface{}, error)
  Close()
}
```

**Comment by otoolep** [comment]
>The entire query engine should be contained in tsdb. I guess the only external part would be something on the cluster side that can return a struct that implements the MapExecutor or Mapper interface.

With the support for distributed queries, I understood that the `tsdb` package should only encapsulate data about local shards. It would expose a call that could return `Map` tasks for any local shards (this call would take, basically, the query and shard ID). It would be up to a higher-level layer -- the `Service` layer in this PR -- to call into the `tsdb` package for shards it knew were local, and call to another chunk of code to create `Map` jobs for shards that are remote. Again, the calling layer would know which were local and which were not (by calling into the `meta` package), not the `tsdb` package. 

If the logic to get at remote shards is also in the `tsdb` package it will have to know more about creating the network connection to those remote jobs, and how run the final "reduce" step. This can be done of course, but it seemed more logical to me to have this at level "higher" than the `tsdb` package.

**Comment by otoolep** [comment]
To be clear, the `Service` layer would expect `Map` objects from the `tsdb` store, and remote shards, to expose the same interface, making the `reduce` phase as simple as possible.

**Comment by otoolep** [comment]
```go
type Mapper interface {
  Begin(query *influxql.Statement) error
  NextChunk() (interface{}, error)
  Close()
}
```
This interface makes sense to me, but the logic to create an object for a remote shard, that implements this interface, I thought it would live *outside* of the `tsdb` package. That said, I guess it doesn't really matter too much -- it can be part of the `tsdb` package, it will just mean that the `query_executor.go` within the package will change.

**Comment by pauldix** [comment]
All the logic around how to run maps and combine their outputs through reduces should be encapsulated in `tsdb`. Even local queries run as map/reduce jobs, they just run maps against local shards.

This is all in `tsdb.QueryExecutor`, which already has a pointer to a `MetaStore` interface. We'll probably just need a new interface for `ShardCluster` or something like that, which knows how to create the connections to the remote server and start the map phase.

The thing that implements that should be in the `cluster` package.

So essentially all query execution logic is kept in `tsdb` with interfaces pulling in any of the distributed bits from either `meta` or `cluster`.

**Comment by otoolep** [comment]
OK, if we want to push more functionality into the `tsdb` package (via interfaces), I can see how that would work.

**Pull request closed without merging**
