### PR TITLE
make circle check go fmt and go vet

### PR DESCRIPTION
**Pull request by dgnorton**

### CODE REVIEW

**Comment by dgnorton** [comment]
@corylanou  lol  :)

pro tip: shell scripts don't like `func`

**Comment by otoolep** [comment]
We already do `go vet`:

https://github.com/influxdb/influxdb/blob/master/circle-test.sh#L53

Does it not work?

**Comment by otoolep** [comment]
Closed in error.

**Comment by corylanou** [comment]
I don't know about `go vet`, but I know for sure the `go fmt` isn't working.

**Comment by dgnorton** [comment]
@otoolep  thanks for pointing that out.  I'll remove the `go vet` check I added.

**Comment by otoolep** [comment]
Yes, please run `go fmt` -- that makes perfect sense to me. But `go vet` is working, I've had tests fail because it flagged issues.

So whatever, we do, let's make it consistent -- go with this new technique, and remove the existing call to `go vet` or use the `exit_if_fail` function there already.

**Comment by corylanou** [comment]
Awesome!!!!  :100:

**Comment by otoolep** [comment]
+1

**Pull request merged**
