### PR TITLE
Try enabling 'go vet'

### PR DESCRIPTION
**Pull request by otoolep**

### CODE REVIEW

**Comment by benbjohnson** [comment]
:+1:

**Comment by otoolep** [comment]
@benbjohnson do you know if we can fix these
```
ok  	github.com/influxdb/influxdb/influxql	0.016s
influxql/parser_test.go:52: influxql.Fields composite literal uses unkeyed fields
influxql/parser_test.go:63: influxql.Fields composite literal uses unkeyed fields
influxql/parser_test.go:74: influxql.Dimensions composite literal uses unkeyed fields
influxql/parser_test.go:78: influxql.SortFields composite literal uses unkeyed fields
influxql/parser_test.go:88: influxql.Fields composite literal uses unkeyed fields
influxql/parser_test.go:90: influxql.Measurements composite literal uses unkeyed fields
influxql/parser_test.go:103: influxql.Fields composite literal uses unkeyed fields
influxql/parser_test.go:105: influxql.Measurements composite literal uses unkeyed fields
influxql/parser_test.go:117: influxql.Fields composite literal uses unkeyed fields
influxql/parser_test.go:126: influxql.Fields composite literal uses unkeyed fields
influxql/parser_test.go:128: influxql.SortFields composite literal uses unkeyed fields
influxql/parser_test.go:171: influxql.SortFields composite literal uses unkeyed fields
influxql/parser_test.go:189: influxql.SortFields composite literal uses unkeyed fields
influxql/parser_test.go:208: influxql.SortFields composite literal uses unkeyed fields
influxql/parser_test.go:227: influxql.SortFields composite literal uses unkeyed fields
influxql/parser_test.go:246: influxql.SortFields composite literal uses unkeyed fields
influxql/parser_test.go:265: influxql.SortFields composite literal uses unkeyed fields
influxql/parser_test.go:293: influxql.Fields composite literal uses unkeyed fields
influxql/parser_test.go:307: influxql.Fields composite literal uses unkeyed fields
```
or is it a tooling issue? I haven't had time to check into it yet. We can disable these checks using `-composities=false`.

**Comment by benbjohnson** [comment]
@otoolep I think you can change it to use `[]*Field{}` instead of `Fields{}`:

So for the first one, instead of:

```
Fields: influxql.Field{
	&influxql.Field{Expr: &influxql.Wildcard{}},
},
```

you can write:

```
Fields: []*influxql.Field{
	{Expr: &influxql.Wildcard{}},
},
```

**Comment by otoolep** [comment]
All green, +1 from @benbjohnson -- merging now.

**Pull request merged**
