### PR TITLE
Removing unused code

### PR DESCRIPTION
**Pull request by corylanou**
This was unused code and it was preventing some of my local tooling from working.

### CODE REVIEW

**Comment by otoolep** [comment]
Any need to check with @benbjohnson ?

**Comment by otoolep** [comment]
I mean, obviously is is unused, perhaps we should confirm with @benbjohnson he knows it's unused.

**Comment by jwilder** [comment]
LGTM :+1:

**Comment by corylanou** [comment]
I checked with him before I made the PR.

**Comment by dgnorton** [comment]
+1

**Pull request merged**
