### PR TITLE
Remove min time from TSM blocks

### PR DESCRIPTION
**Pull request by jwilder**
This builds on #5011 and removes the min time stored as the first 8 bytes of each block.

MinTime is now in the index for each block so storing it in the block
header is redundant.  The encodings also store it in their header so
we are actually storing it 3 times.

Removing this is an incompatible change with the current tsm1 file format.

### CODE REVIEW

**Comment by jwilder** [comment]
@pauldix @otoolep

**Comment by otoolep** [comment]
+1 on https://github.com/influxdb/influxdb/commit/cf341eaa6ab86bb359043a6dc754641c7caf20ba

**Comment by pauldix** [comment]
lgtm, can we merge min in first and then this'll just collapse on top of it?

**Comment by otoolep** [comment]
It should @pauldix

**Pull request merged**
