### PR TITLE
Fix race condition on continuous queries

### PR DESCRIPTION
**Pull request by corylanou**
Need a `Lock` instead of an `RLock` as we are writing inside the loop.

### CODE REVIEW

**Comment by toddboom** [comment]
:+1: on green

**Comment by otoolep** [comment]
Are you talking about this change?

`c.intoRP = d.defaultRetentionPolicy`

Is this what we need to lock?

**Comment by corylanou** [comment]
@otoolep correct.

**Comment by otoolep** [comment]
OK, thanks.

That code actually seems problematic, though it is there now, and not actually being changed. Is `intoRP` meant to persist, so it is set next the time loop is set? If so, it won't persist past a reboot.

**Comment by corylanou** [comment]
No idea.  I didn't look that closely at it, just that it was a race condition.  @pauldix would know the answer.

**Comment by otoolep** [comment]
OK, makes sense if the race detector flagged. Definitely have a question about it for @pauldix

**Pull request merged**
