### PR TITLE
Set open file limit to 64K.

### PR DESCRIPTION
**Pull request by otoolep**
Fix issue #1413.

### CODE REVIEW

**Comment by pauldix** [comment]
Is there something the post install script needs to do to let the influxdb user have a file limit this high?

**Comment by otoolep** [comment]
Actually, because the current script runs `influxd` as root. Let me fix that, and then I will set the limit for the user.

**Comment by benbjohnson** [comment]
@otoolep are we hitting a file descriptor limit?

**Comment by pauldix** [comment]
@benbjohnson we will. Default is 256 and with multiple retention policies with many shards each, and many people making requests we'll hit it in no time.

I think it's better to up by default and let people lower it if they hate it. Any reason not to have it raised up?

**Comment by otoolep** [comment]
Yeah, I say raise it and just make open-file limits a non-issue.

**Comment by benbjohnson** [comment]
No reason not to bump it. Just curious if we were hitting a limit.

**Pull request closed without merging**
