### PR TITLE
Add LIST RETENTION POLICIES statement to InfluxQL

### PR DESCRIPTION
**Pull request by dgnorton**

### CODE REVIEW

**Comment by otoolep** [comment]
Cool.

I think we want to be able to list them on a particular database though, too. Is that possible?

**Comment by dgnorton** [comment]
Right!  No problem.

**Comment by otoolep** [comment]
Thanks -- makes sense to me, +1 on a green build. As long as you are happy the wider team will be happy with the syntax.

**Comment by benbjohnson** [comment]
:dancer:

**Pull request merged**
