### PR TITLE
BZ1 Engine

### PR DESCRIPTION
**Pull request by benbjohnson**
## Overview

This pull request adds the `bz1` storage engine. It also changes the storage engine, `v1` to `b1`. The abbreviation more appropriately conveys what kind of storage is being used:

* `b1` - bolt, version 1
* `bz1` - bolt, compessed, version 1

## Internals

The compressed storage engine works by writing whole series at a time and dividing the points within them into blocks. Those blocks are then compressed using [snappy](https://github.com/golang/snappy) and saved to BoltDB with the first timestamp in the block as the key.

To read data back out of the compressed format, a cursor seeks to the appropriate block, decodes the block, and reads forward until it finds its starting point. Calls to `Cursor.Next()` will continue reading points off the block until there are no more available. Then it will read the next block and decode it. Once all the points from all the blocks are read then the cursor returns a `nil` key and value.

## Caveats

The compressed format is meant for cold shards that can be frozen. Because of this, the compressed format doesn't support updates to existing series. A series must be written all at once. Updating a series will require that the data be read out, deleted, and then reinserted in a single batch.

## TODO

- [x] Implement `WritePoints()`
- [x] Implement `Cursor`
- [x] Implement metadata storage
- [x] Implement randomized testing
- [x] Implement benchmarks
- [x] Evaluate different parameters (block size, compression type)
- [ ] Allow updates to series
- [ ] Integrate the `bz1` engine into `tsdb`

### CODE REVIEW

**Comment by toddboom** [comment]
very large amounts of excitement. :boom:

**Comment by benbjohnson** [comment]
I added some synthetic benchmarks. I tried simulating the uncompressed format by using a block size of `0` and I was getting about `70b/pt`. I tested a range of block sizes (512b, 1KB, 2KB, 4KB, 8KB, 16KB, 32KB, 64KB) and found that 32KB seemed to be a good sweet spot. When inserting 10,000 points per series it was compressing it down to `5.4b/pt`. And that's including meta and branch pages. Woohoo!

Again, this is a synthetic benchmark but it's showing promise. :)

/cc @pauldix @toddboom

**Comment by pauldix** [comment]
Looks great so far. I think for this to be used, it'll have to support updates to previous blocks. People sometimes load historical data so we should support that. 

This logic for how to deal with it can be encapsulated in the WAL. Basically, buffer all those historical updates there, then when the flush happens, deal with resetting old compressed blocks there.

For cases where people are starting with fresh databases and starting with a historical backfill, this should perform well since there are no historical blocks to reset.

**Comment by benbjohnson** [comment]
I'd like to avoid the WAL entirely if possible. It's such a PITA. I'll change the engine to support updates but it probably won't be the fastest.

**Comment by benbjohnson** [comment]
I evaluated some different compression packages (snappy, gzip, lz4) with different block sizes. The tl;dr is that gzip gives a little better compression -- about 20% better than snappy -- but it's a heck of a lot slower. LZ4's compression is generally worse or equal to snappy and it's slower than snappy. In some cases with very small blocks the performance difference is 10x worse.

This is all in line with our initial compression tests so nothing new here. I wanted to verify that our assumptions were still correct before sticking with snappy.

**Comment by toddboom** [comment]
@benbjohnson is this at all interesting? http://blog.klauspost.com/optimized-gzipzip-packages-30-50-faster/

**Comment by benbjohnson** [comment]
@toddboom The gzip compression was _significantly_ slower. 50% faster would help but I think it would still be way too slow.

**Pull request closed without merging**
