### PR TITLE
Add stats for the WAL

### PR DESCRIPTION
**Pull request by otoolep**
```
> show stats

name: partition
tags: id=1, partition=/tmp/opt/influxdb/wal/graphite/default/2
idle_flush      points_flush    series_flush
----------      ------------    ------------
1               345600          1

name: partition
tags: id=1, partition=/tmp/opt/influxdb/wal/graphite/default/3
idle_flush      points_flush    series_flush
----------      ------------    ------------
1               604800          1

name: wal
tags: bind=/tmp/opt/influxdb/wal/_internal/monitor/1
auto_flush      points_write    points_write_req
----------      ------------    ----------------
7               78              8

name: wal
tags: bind=/tmp/opt/influxdb/wal/graphite/default/2
auto_flush      points_write    points_write_req
----------      ------------    ----------------
7               345600          70

name: wal
tags: bind=/tmp/opt/influxdb/wal/graphite/default/3
auto_flush      points_write    points_write_req
----------      ------------    ----------------
7               279400          56

name: wal
tags: bind=/tmp/opt/influxdb/wal/graphite/default/4
auto_flush
----------
7

### CODE REVIEW

**Comment by otoolep** [comment]
@corylanou @jwilder @benbjohnson

**Comment by dgnorton** [comment]
+1

**Comment by corylanou** [comment]
Is there any stats about time taken we want to log?  Other than that, +1.

**Comment by otoolep** [comment]
@corylanou -- that sounds like a good idea, but I don't know the WAL code well enough to measure times across the flush (it's done asynchronously) so don't want instrument that yet, in case the code suffers a regression.

Unless it's clear to you?

**Comment by otoolep** [comment]
Actually, I take that back -- it should be easy to record that. Doing so now, and will then merge.

**Comment by otoolep** [comment]
System now records cumulative time spending flushing.

**Comment by corylanou** [comment]
Beautiful! :100:

**Pull request merged**
