### PR TITLE
Remove go vet download as it's included in the latest go binaries

### PR DESCRIPTION
**Pull request by marcosnils**
Source: https://github.com/golang/tools/blob/master/README

### CODE REVIEW

**Comment by otoolep** [comment]
Build script has been fixed, please rebase so CI testing can re-run.

**Comment by otoolep** [comment]
Thanks @marcosnils -- anything that speeds up the build is great.

+1 once I see a green build.

**Comment by marcosnils** [comment]
@otoolep rebased. waiting for build to pass.

**Comment by marcosnils** [comment]
I'll close and re-open it

**Pull request closed without merging**
