### PR TITLE
Remove obsolete configuration options

### PR DESCRIPTION
**Pull request by otoolep**

### CODE REVIEW

**Comment by otoolep** [comment]
Green build, ready to merge. The `influxd` binary starts with this configuration, assuming write-permissions to the relevant directories.

**Comment by otoolep** [comment]
@corylanou since he was in this file last.

**Comment by corylanou** [comment]
I'm not 100% up to speed on our config yet, but if we removed something we needed, we can add it back.  Nothing jumps out at me as being out of place.

**Comment by otoolep** [comment]
Thanks @corylanou it's all obsolete right now, and can be re-instated at anytime.

**Pull request merged**
