### PR TITLE
Remove DUMP from CLI

### PR DESCRIPTION
**Pull request by beckettsean**
fixes https://github.com/influxdb/influxdb/issues/3235

### CODE REVIEW

**Comment by corylanou** [comment]
+1.  If there is a PR that references the updating of this function we should reference it here as well.

**Comment by beckettsean** [comment]
@corylanou I didn't see any issue about restoring DUMP. Gunnar is taking a pass at ripping out the function and will check that into this PR.

**Comment by gunnaraasen** [comment]
Updated the PR to completely remove all the dump code.

**Comment by beckettsean** [comment]
@corylanou can we get a +1 on Gunnar's changes?

**Comment by toddboom** [comment]
+1

**Pull request merged**
