### PR TITLE
Issue 3902

### PR DESCRIPTION
**Pull request by corylanou**

### CODE REVIEW

**Comment by otoolep** [comment]
+1

**Comment by dgnorton** [comment]
It would be better to enforce `time` checks earlier in the parser so that it works for all statements and returns better error messages (i.e., includes position).

- `parseVarRef` should error if the last segment of the identifier is `time`
- `parseCall` should branch to individual `parse<Name>` functions that validate parameters

**Comment by otoolep** [comment]
+1 to what @dgnorton said. :-)

**Comment by corylanou** [comment]
@dgnorton I agree, I think that some of this can be pulled out to smaller areas, but there are still areas of `validateDimensions` that have to be done here as they look at multiple parts of the statement.

I can pull out the ones that are appropriate for now.  I would suspect that a number of validations in the `validateAggregates` could be moved further up the chain as well, but that is outside the scope of this PR.

**Comment by corylanou** [comment]
After further conversations with @dgnorton it turned out that it wouldn't be so easy to change what I already have.  Can I get a +1?  /cc @otoolep

**Comment by otoolep** [comment]
+1

**Comment by otoolep** [comment]
Cherry-pick to 0.9.4 branch too, I believe.

**Pull request merged**
