### PR TITLE
Output consistency for usage in cli

### PR DESCRIPTION
**Pull request by endophage**
Making the formatting of the cli info consistent.

### CODE REVIEW

**Comment by otoolep** [comment]
Thanks @endophage -- have you signed the CLA?

**Comment by otoolep** [comment]
+1, once the CLA is signed.

**Comment by endophage** [comment]
Done. Also added signed-off by to commit, just to be completely comprehensive :-)

**Comment by otoolep** [comment]
Works for me. @corylanou ?

**Comment by corylanou** [comment]
+1.  thanks!

**Comment by otoolep** [comment]
Thanks @endophage

**Pull request merged**
