### PR TITLE
bump admin UI to version 0.9.3-rc1

### PR DESCRIPTION
**Pull request by jipperinbham**

### CODE REVIEW

**Comment by toddboom** [comment]
@jipperinbham we can probably just bump this straight to `v0.9.3`, and should have for the nightlies - we haven't previously made that much differentiation on the admin version string.

also, this needs a rebuild of the static assets after the files are changed. i'm happy to do it, but the details are here in case you were curious:
https://github.com/influxdb/influxdb/tree/master/shared/admin#building

**Comment by jipperinbham** [comment]
@toddboom thanks for the reminder on building the assets, I wasn't sure if that was done as part of the nightly builds

I've updated it to `v0.9.3

**Comment by toddboom** [comment]
@jipperinbham many thanks!

**Comment by toddboom** [comment]
cherry-picked to the `0.9.3` branch

**Pull request merged**
