### PR TITLE
Start cluster before broker.

### PR DESCRIPTION
**Pull request by benbjohnson**
## Overview

This commit fixes an issue where the second node joins but the first node cannot commit because it doesn't have the HTTP endpoint running yet. This is a side effect of streaming raft since we don't synchronize the quorum set with the heartbeats. We should cache the config per term in the future.

### CODE REVIEW

**Comment by otoolep** [comment]
Test failed due to these issues:
```
Transport.ReadFrom: error: not leader
[raft] 2015/04/15 17:23:18 readFromLeader: read from: //log0, id=2, term=1, index=98
[raft] 2015/04/15 17:23:18 ReadFrom
[raft] 2015/04/15 17:23:18 reading from stream
[raft] 2015/04/15 17:23:18 unable to init writer: not leader
Transport.ReadFrom: error: not leader
==================
WARNING: DATA RACE
Read by goroutine 22:
  github.com/influxdb/influxdb/raft.(*IndexFSM).Index()
      /home/ubuntu/.go_project/src/github.com/influxdb/influxdb/raft/internal_test.go:57 +0x36
  github.com/influxdb/influxdb/raft.(*Log).followerLoop()
      /home/ubuntu/.go_project/src/github.com/influxdb/influxdb/raft/log.go:892 +0x3a1
  github.com/influxdb/influxdb/raft.(*Log).stateLoop()
      /home/ubuntu/.go_project/src/github.com/influxdb/influxdb/raft/log.go:858 +0x16b

Previous write by goroutine 56:
  github.com/influxdb/influxdb/raft.(*IndexFSM).Apply()
      /home/ubuntu/.go_project/src/github.com/influxdb/influxdb/raft/internal_test.go:52 +0x48
  github.com/influxdb/influxdb/raft.(*Log).applyNextUnappliedEntry()
      /home/ubuntu/.go_project/src/github.com/influxdb/influxdb/raft/log.go:1448 +0x8ae
  github.com/influxdb/influxdb/raft.(*Log).applier()
      /home/ubuntu/.go_project/src/github.com/influxdb/influxdb/raft/log.go:1386 +0x18f
```

**Comment by benbjohnson** [comment]
Fixed:  d565076

**Comment by otoolep** [comment]
Seems sensible, +1 on green build. Can you update the CHANGELOG too?

**Comment by benbjohnson** [comment]
CHANGELOG added.

**Pull request merged**
