### PR TITLE
condense skipWhitespace code

### PR DESCRIPTION
**Pull request by oiooj**
go fmt #4251

### CODE REVIEW

**Comment by otoolep** [comment]
Can you please rebase? That way we remove the "merge commits".

`git pull --rebase influxdb/origin master`

**Comment by oiooj** [comment]
You taught me a lot of things, Thanks @otoolep

**Comment by otoolep** [comment]
Seems fine to me.

@jwilder? 

CLA has been signed.

**Comment by jwilder** [comment]
:+1:

**Comment by otoolep** [comment]
Thanks for the contribution @oiooj

**Pull request merged**
