### PR TITLE
Fixes #3403 - Added check for escaped single quote in string

### LINKED ISSUE #3403: Unable to query fields with single quotes via CLI or admin UI
```
> insert test value="foo'bar"
> select * from test
name: test
time				b	value
----				-	-----
2015-07-20T23:42:21.952904634Z		foo'bar

> select * from test where value = 'foo''bar'
ERR: error parsing query: found bar, expected SELECT, DELETE, SHOW, CREATE, DROP, GRANT, REVOKE, ALTER, SET at line 1, char 38
> select * from test where value = 'foo'bar'
ERR: error parsing query: found bar, expected SELECT, DELETE, SHOW, CREATE, DROP, GRANT, REVOKE, ALTER, SET at line 1, char 39
> select * from test where value = 'foo\'bar'
ERR: error parsing query: found \', expected identifier, string, number, bool at line 1, char 39
> select * from test where value = 'foo\\'bar'
ERR: error parsing query: found bar, expected SELECT, DELETE, SHOW, CREATE, DROP, GRANT, REVOKE, ALTER, SET at line 1, char 41
> select * from test where value =~ /foo.bar/
> 
```

https://groups.google.com/forum/#!topic/influxdb/tM5JysvWE2A

### PR DESCRIPTION
**Pull request by jhorwit2**
#3403 

```
> create database test;
> use test
Using database test
> insert test value="foo'bar"
> select * from test
name: test
----------
time				value
2015-07-21T00:15:43.034952116Z	foo'bar

> select * from test where value = 'foo'bar'
ERR: error parsing query: found bar, expected SELECT, DELETE, SHOW, CREATE, DROP, GRANT, REVOKE, ALTER, SET at line 1, char 39
> select * from test where value = 'foo''bar'
ERR: error parsing query: found bar, expected SELECT, DELETE, SHOW, CREATE, DROP, GRANT, REVOKE, ALTER, SET at line 1, char 38
> select * from test where value = 'foo\'bar'
name: test
----------
time				value
2015-07-21T00:15:43.034952116Z	foo'bar

> select * from test where value = 'foo'bar'
ERR: error parsing query: found bar, expected SELECT, DELETE, SHOW, CREATE, DROP, GRANT, REVOKE, ALTER, SET at line 1, char 39
> 
```

### CODE REVIEW

**Comment by otoolep** [comment]
@dgnorton @benbjohnson

**Comment by otoolep** [comment]
+1, seems sensible to me.

Thanks @jhorwit2

**Comment by otoolep** [comment]
Can you also update the 0.9.3 CHANGELOG and give yourself credit?

**Comment by jhorwit2** [comment]
Yup. I'll do that now.

**Comment by jhorwit2** [comment]
Whoops. let me fix that contribute message. added query twice

**Comment by jhorwit2** [comment]
:+1:

**Comment by jhorwit2** [comment]
This should be under bug fix right?

**Comment by otoolep** [comment]
Yeah, bug fix makes sense to me.

**Comment by jhorwit2** [comment]
@otoolep anyone idea when this will be merged? Keeping conflicts with contribute file up to date is tedious haha.

**Comment by dgnorton** [comment]
+1 Thanks @jhorwit2!

**Pull request merged**
