### PR TITLE
Reload shard map on restart

### PR DESCRIPTION
**Pull request by otoolep**

### CODE REVIEW

**Comment by otoolep** [comment]
Fixes https://github.com/influxdb/influxdb/issues/2012

@pauldix @benbjohnson

**Comment by otoolep** [comment]
The fact that this issue wasn't causing any real problems until I started using `s.shards` for stats, tells me `s.shards` is probably useless now, and we could just get the shards direct from the retention policies. Perhaps it's still a useful shortcut.

**Comment by toddboom** [comment]
This makes sense to me.

**Comment by benbjohnson** [comment]
:+1:

**Comment by otoolep** [comment]
Thanks @toddboom @benbjohnson

**Pull request merged**
