### PR TITLE
Handler errors should be formatted as JSON.

### LINKED ISSUE #3170: [0.9.1-rc1] Database not found error not in json
When writing into a non existing database, the error message is not in a JSON structure like other error messages.

curl -X POST 'http://192.168.1.1:8086/write?db=notexist' --data-binary @TEST_VALUES
database not found: "notexist"

curl -X POST 'http://192.168.1.1:8086/write?db=test&u=notexist&p=password' --data-binary @TEST_VALUES
{"error":"user not found"}

I think it is better to embedded all error messages in a JSON structure.

### PR DESCRIPTION
**Pull request by pires**
- [ ] CHANGELOG.md updated
- [x] Rebased/mergable
- [x] Tests pass
- [x] Sign [CLA](http://influxdb.com/community/cla.html)

Fixes #3170

### CODE REVIEW

**Comment by otoolep** [comment]
Thanks @pires

Now that I think about this, this may be considered a breaking change, we need to be careful about this.

@pires -- can you show us an example of the before-and-after for this change?

**Comment by pires** [comment]
@otoolep same error code but the only difference is that the error is JSON encoded as per issue request.

Is there any reasoning behind this not being the case before?

**Comment by pires** [comment]
Previous behavior:
```
$ curl -v -X POST 'http://192.168.99.100:8086/write?db=notexist'
*   Trying 192.168.99.100...
* Connected to 192.168.99.100 (192.168.99.100) port 8086 (#0)
> POST /write?db=notexist HTTP/1.1
> Host: 192.168.99.100:8086
> User-Agent: curl/7.43.0
> Accept: */*
>
< HTTP/1.1 404 Not Found
< Request-Id: a57fcaeb-95a7-11e5-8003-000000000000
< X-Influxdb-Version: 0.9.3
< Date: Sat, 28 Nov 2015 08:11:37 GMT
< Content-Length: 31
< Content-Type: text/plain; charset=utf-8
<
database not found: "notexist"
* Connection #0 to host 192.168.99.100 left intact
```

PR behavior:
```
$ curl -v -X POST 'http://localhost:8086/write?db=notexist'
*   Trying ::1...
* Connected to localhost (::1) port 8086 (#0)
> POST /write?db=notexist HTTP/1.1
> Host: localhost:8086
> User-Agent: curl/7.43.0
> Accept: */*
>
< HTTP/1.1 404 Not Found
< Content-Type: application/json
< Request-Id: 156d97ff-95a8-11e5-8001-000000000000
< X-Influxdb-Version: 0.9
< Date: Sat, 28 Nov 2015 08:14:45 GMT
< Content-Length: 45
<
{"error":"database not found: \"notexist\""}
* Connection #0 to host localhost left intact
```

**Comment by otoolep** [comment]
Agreed @pires -- it's the same error, just wrapped in JSON.

@pauldix -- I don't think we ever meant to send back non-JSON formatted errors, so this makes sense to me. But this is technically a breaking change. Need your call.

**Comment by pires** [comment]
@otoolep thank you. I think the question about breaking changes begs for more reviewing of the currently open issues, so to prevent anyone else spending time with stuff that in the end may get rejected. Agree?

**Comment by otoolep** [comment]
Yeah, makes sense @pires -- I'm on the fence about this one, since it's looks like a bug that it was never JSON-format.

**Comment by benbjohnson** [comment]
I'm personally ok with this breaking change. It seems like it should have been JSON to begin with.

**Comment by pires** [comment]
Any updates on this?

**Comment by pauldix** [comment]
Yep, should have been json to begin with. Thanks @pires!

**Pull request merged**
