### PR TITLE
fix issue #4816 some aggregate function work incorrectly in cluster mode

### PR DESCRIPTION
**Pull request by mengjinglei**
- [x] CHANGELOG.md updated
- [x] Rebased/mergable
- [x] Tests pass
- [x] Sign [CLA](http://influxdb.com/community/cla.html) (if not already signed)

### CODE REVIEW

**Comment by otoolep** [comment]
Is there any way unit test this?

**Comment by mengjinglei** [comment]
I noticed that there is no unit test case for `InitializeUnmarshaller` function in `tsdb/functions_test.go`, but I'd like to have a try.

**Comment by mengjinglei** [comment]
`Unmarshaller `  unmarshal bytes receive from remote node to interface that `reducer` can use, for `min` and `max` functions, the input  interface of `reducer` is expect to be  `minMaxMapOut`, but there is no specific unmarshaller for `min` and `max` functions, so the bytes are unmarshal by `default unmarshaller` whose output can not be recognize by the `reducer`

**Comment by mengjinglei** [comment]
@otoolep

**Comment by otoolep** [comment]
+1

@dgnorton -- can you please also review?

**Comment by otoolep** [comment]
CLA confirmed signed.

**Comment by dgnorton** [comment]
+1

**Comment by mengjinglei** [comment]
@otoolep

**Comment by otoolep** [comment]
Thanks @mengjinglei

**Pull request merged**
