### PR TITLE
fix tsm1 for Solaris #4787, passes unit tests now

### PR DESCRIPTION
**Pull request by fazalmajid**
Added a platform-specific mmap_solaris.go, based on BoltDB's bolt/bolt_unix_solaris.go: https://github.com/boltdb/bolt/pull/411

### CODE REVIEW

**Comment by fazalmajid** [comment]
This supersedes #4788, which was failing on Solaris and probably also broke Windows (even further than it already was).

**Comment by pauldix** [comment]
Great, thanks @fazalmajid! Can you sign the CLA? https://influxdb.com/community/cla.html

I'll get it merged in right after

**Comment by fazalmajid** [comment]
@pauldix Done, and thanks!

**Comment by pauldix** [comment]
Great, thanks!

**Comment by otoolep** [comment]
Cherry-picked to the 0.9.6. branch.

**Pull request merged**
