### PR TITLE
SHOW DATABASES returns series name "databases"

### PR DESCRIPTION
**Pull request by otoolep**

### CODE REVIEW

**Comment by otoolep** [comment]
Fix for issue #2101 2075.

**Comment by otoolep** [comment]
This change removes redundant tests that are now in the integration test suite.

**Comment by otoolep** [comment]
Green build.

**Comment by otoolep** [comment]
@pauldix

**Comment by otoolep** [comment]
@dgnorton

**Comment by dgnorton** [comment]
lgtm  :shipit:

**Comment by otoolep** [comment]
Thanks @dgnorton

**Pull request merged**
