### PR TITLE
Explicity name "initialization" section in config

### PR DESCRIPTION
**Pull request by otoolep**

### CODE REVIEW

**Comment by corylanou** [comment]
Looks sane.  Any future tests?

**Comment by otoolep** [comment]
Tests didn't need to change @corylanou which shows that `toml` file is not case-sensitive. This is cosmetic, but important for clarity.

**Comment by otoolep** [comment]
https://github.com/influxdb/influxdb/blob/master/cmd/influxd/config_test.go#L164

already testing with lower-case section name.

**Comment by corylanou** [comment]
Sounds good. Ship it.

**Comment by otoolep** [comment]
Thanks @corylanou -- green build, merging now.

**Pull request merged**
