### PR TITLE
Exit all queryAndWait goroutines when returning

### PR DESCRIPTION
**Pull request by jwilder**
The timeout goroutine would continue to run (until the timeout)
even after queryAndWait returned.  This causes thousands of extra
goroutines to linger around and makes the test stack traces very
difficult to read.

### CODE REVIEW

**Comment by corylanou** [comment]
+1. Good find!

**Comment by otoolep** [comment]
Do we need a wait group in there? Or we don't need to wait around until it closes, it's just enough to know that it will, right?

**Comment by otoolep** [comment]
+1 if no wait group needed (which I don't think there is). Great clean-up.

**Comment by otoolep** [comment]
Closed in error.

**Pull request merged**
