### PR TITLE
Doesn't display password in CLI on connection

### PR DESCRIPTION
**Pull request by apoydence**

### CODE REVIEW

**Comment by otoolep** [comment]
Thanks @apoydence -- this is a good idea. However, it would be better if your code was a *method* on the `Client` type. For example, `func (c *Client) DisplayURL()` -- that would be neater. Then call that method from here.

Can you do that? And perhaps add a unit test (it would go in https://github.com/influxdb/influxdb/blob/master/client/influxdb_test.go) to test the new method. Don't forget to sign the CLA too.

**Comment by apoydence** [comment]
I moved it to a method and added two unit tests.

**Comment by otoolep** [comment]
@apoydence -- 1 final change is required. Our coding style dictates that stuff like "URL" should always be capitalized, so can you change the function to `DisplayURL`?

https://github.com/golang/go/wiki/CodeReviewComments#initialisms

**Comment by otoolep** [comment]
@corylanou

**Comment by corylanou** [comment]
I intentionally didn't encode the username/password into the url I store in the client struct as I didn't want them to be able to echo out the credentials.  This raises a question about security in general on how the client handles authentication.  To be even more secure, we shouldn't use `url.UserPassword` at all.  We are currently passing the credentials from the client over clear text.  We should, instead, really pass them over the authorization header.

That being said, I would rather change the client library to send authentication over the headers per RFC 2617.  I don't want to expose the password from the cli ever, as this is a security risk.

**Comment by otoolep** [comment]
@corylanou -- does this mean you don't want to merge this, and would rather work the issue another way?

**Comment by corylanou** [comment]
@otoolep I think we need to merge it for now as it's blocking a client.  @benbjohnson is also aware of this discussion.  We probably need to address this post 0.9.0.

**Comment by corylanou** [comment]
@otoolep I would rather fix the issue I talked about in another PR, and then close this one.  I don't think we want to send out the password do we?

**Comment by otoolep** [comment]
No, we don't want to send it out. 

Thanks @apoydence -- we want to fix this in another way, we'll take a stab at it, or your contribution along the lines of @corylanou 's is more than welcome.

**Pull request closed without merging**
