### PR TITLE
Default data logging to on

### PR DESCRIPTION
**Pull request by otoolep**

### CODE REVIEW

**Comment by otoolep** [comment]
@jwilder @pauldix

**Comment by beckettsean** [comment]
@otoolep what does "data logging" entail?

**Comment by otoolep** [comment]
Low-level stuff within the tsm engine, like initializing tsm files, which files are being compacted, how long compaction is taking etc. It will expand as development continues.

**Comment by otoolep** [comment]
It's called "data" since we have the "data" part of the engine and the "WAL" part of the engine.

**Comment by jwilder** [comment]
:+1:

**Pull request merged**
