### PR TITLE
Fix reads of metadata file in WAL

### LINKED ISSUE #3730: [0.9.3-rc1] panic after a 4M+ "in the past" points import. Unable to restart
Hi,

I'm working in a game studio, and I am benchmarking influxDB in order to replace some of our tools (data and reporting stuffs).

The preliminary task i am blocked by consists of the import of 10M timestamped points : 1 day of events for 1 of our games : so it is the "data in the past" case.

The 0.9.2 stable is unable to import more than 500000 points because of some timeout occuring during WAL flush operation. I tried, without sucess, to tune the WAL flushing parameters.

The current work (#3569) seems in the good direction with the 0.9.3-rc1 : I was able to insert 4M+ points (batches of 1000 points with the python API).
Moreover, the time to handle the POST requests is very stable (250 - 300 ms on a standard macbook laptop running linux).

Anyway, after a while, influxdb crashed, and I was not able to restart it.

The config file is the default one of the 0.9.3-rc1

Here is the last trace on the log file.

	panic: runtime error: makeslice: len out of range

	goroutine 5005 [running]:
	github.com/influxdb/influxdb/tsdb/engine/wal.(*Log).readMetadataFile(0xc246e4a000, 0xc2ca74ae10, 0x24, 0x0, 0x0, 0x0, 0x0, 0x0)
		/tmp/tmp.qH0h0bgBIK/src/github.com/influxdb/influxdb/tsdb/engine/wal/wal.go:366 +0x36f
	github.com/influxdb/influxdb/tsdb/engine/wal.(*Log).flushMetadata(0xc246e4a000, 0x0, 0x0)
		/tmp/tmp.qH0h0bgBIK/src/github.com/influxdb/influxdb/tsdb/engine/wal/wal.go:624 +0x200
	github.com/influxdb/influxdb/tsdb/engine/wal.(*Log).autoflusher(0xc246e4a000, 0xc221cd9ec0)
		/tmp/tmp.qH0h0bgBIK/src/github.com/influxdb/influxdb/tsdb/engine/wal/wal.go:599 +0x312
	created by github.com/influxdb/influxdb/tsdb/engine/wal.(*Log).Open
		/tmp/tmp.qH0h0bgBIK/src/github.com/influxdb/influxdb/tsdb/engine/wal/wal.go:215 +0x4bc

	goroutine 1 [chan receive, 262 minutes]:
	main.(*Main).Run(0xc20806db00, 0xc20800a010, 0x4, 0x4, 0x0, 0x0)
		/tmp/tmp.qH0h0bgBIK/src/github.com/influxdb/influxdb/cmd/influxd/main.go:91 +0x777
	main.main()
		/tmp/tmp.qH0h0bgBIK/src/github.com/influxdb/influxdb/cmd/influxd/main.go:42 +0xdc

	goroutine 6 [syscall, 262 minutes]:
	os/signal.loop()
		/usr/local/go/src/os/signal/signal_unix.go:21 +0x1f
	created by os/signal.init·1
		/usr/local/go/src/os/signal/signal_unix.go:27 +0x35

	goroutine 17 [syscall, 262 minutes, locked to thread]:
	runtime.goexit()
		/usr/local/go/src/runtime/asm_amd64.s:2232 +0x1

	goroutine 8 [IO wait, 262 minutes]:
	net.(*pollDesc).Wait(0xc208010450, 0x72, 0x0, 0x0)
		/usr/local/go/src/net/fd_poll_runtime.go:84 +0x47
	net.(*pollDesc).WaitRead(0xc208010450, 0x0, 0x0)
		/usr/local/go/src/net/fd_poll_runtime.go:89 +0x43
	net.(*netFD).accept(0xc2080103f0, 0x0, 0x7fa8d625ee30, 0xc2080fa000)
		/usr/local/go/src/net/fd_unix.go:419 +0x40b
	net.(*TCPListener).AcceptTCP(0xc208039180, 0x0, 0x0, 0x0)
		/usr/local/go/src/net/tcpsock_posix.go:234 +0x4e
	net.(*TCPListener).Accept(0xc208039180, 0x0, 0x0, 0x0, 0x0)
		/usr/local/go/src/net/tcpsock_posix.go:244 +0x4c
	github.com/influxdb/influxdb/tcp.(*Mux).Serve(0xc2080de810, 0x7fa8d6261428, 0xc208039180, 0x0, 0x0)
		/tmp/tmp.qH0h0bgBIK/src/github.com/influxdb/influxdb/tcp/mux.go:45 +0x57
	created by github.com/influxdb/influxdb/cmd/influxd/run.func·003
		/tmp/tmp.qH0h0bgBIK/src/github.com/influxdb/influxdb/cmd/influxd/run/server.go:313 +0x8f2

	goroutine 9 [chan receive, 262 minutes]:
	github.com/influxdb/influxdb/tcp.(*listener).Accept(0xc208039188, 0x0, 0x0, 0x0, 0x0)
		/tmp/tmp.qH0h0bgBIK/src/github.com/influxdb/influxdb/tcp/mux.go:117 +0x80
	github.com/influxdb/influxdb/meta.(*raftLayer).Accept(0xc2080de960, 0x0, 0x0, 0x0, 0x0)
		/tmp/tmp.qH0h0bgBIK/src/github.com/influxdb/influxdb/meta/store.go:2058 +0x64
	github.com/hashicorp/raft.(*NetworkTransport).listen(0xc208010540)
		/tmp/tmp.qH0h0bgBIK/src/github.com/hashicorp/raft/net_transport.go:346 +0x50
	created by github.com/hashicorp/raft.NewNetworkTransport
		/tmp/tmp.qH0h0bgBIK/src/github.com/hashicorp/raft/net_transport.go:138 +0x2c4

	goroutine 10 [select]:
	github.com/hashicorp/raft.(*Raft).leaderLoop(0xc2080ba1c0)
		/tmp/tmp.qH0h0bgBIK/src/github.com/hashicorp/raft/raft.go:826 +0xc7c
	github.com/hashicorp/raft.(*Raft).runLeader(0xc2080ba1c0)
		/tmp/tmp.qH0h0bgBIK/src/github.com/hashicorp/raft/raft.go:798 +0x74e
	github.com/hashicorp/raft.(*Raft).run(0xc2080ba1c0)
		/tmp/tmp.qH0h0bgBIK/src/github.com/hashicorp/raft/raft.go:595 +0xc9
	github.com/hashicorp/raft.*Raft.(github.com/hashicorp/raft.run)·fm()
		/tmp/tmp.qH0h0bgBIK/src/github.com/hashicorp/raft/raft.go:245 +0x27
	github.com/hashicorp/raft.func·011()
		/tmp/tmp.qH0h0bgBIK/src/github.com/hashicorp/raft/state.go:152 +0x51
	created by github.com/hashicorp/raft.(*raftState).goFunc
		/tmp/tmp.qH0h0bgBIK/src/github.com/hashicorp/raft/state.go:153 +0xe3

	goroutine 11 [select, 9 minutes]:
	github.com/hashicorp/raft.(*Raft).runFSM(0xc2080ba1c0)
		/tmp/tmp.qH0h0bgBIK/src/github.com/hashicorp/raft/raft.go:502 +0x1043
	github.com/hashicorp/raft.*Raft.(github.com/hashicorp/raft.runFSM)·fm()
		/tmp/tmp.qH0h0bgBIK/src/github.com/hashicorp/raft/raft.go:246 +0x27
	github.com/hashicorp/raft.func·011()
		/tmp/tmp.qH0h0bgBIK/src/github.com/hashicorp/raft/state.go:152 +0x51
	created by github.com/hashicorp/raft.(*raftState).goFunc
		/tmp/tmp.qH0h0bgBIK/src/github.com/hashicorp/raft/state.go:153 +0xe3

	goroutine 12 [select]:
	github.com/hashicorp/raft.(*Raft).runSnapshots(0xc2080ba1c0)
		/tmp/tmp.qH0h0bgBIK/src/github.com/hashicorp/raft/raft.go:1613 +0x466
	github.com/hashicorp/raft.*Raft.(github.com/hashicorp/raft.runSnapshots)·fm()
		/tmp/tmp.qH0h0bgBIK/src/github.com/hashicorp/raft/raft.go:247 +0x27
	github.com/hashicorp/raft.func·011()
		/tmp/tmp.qH0h0bgBIK/src/github.com/hashicorp/raft/state.go:152 +0x51
	created by github.com/hashicorp/raft.(*raftState).goFunc
		/tmp/tmp.qH0h0bgBIK/src/github.com/hashicorp/raft/state.go:153 +0xe3

	goroutine 13 [select, 262 minutes]:
	github.com/influxdb/influxdb/meta.(*localRaft).logLeaderChanges(0xc208072d20)
		/tmp/tmp.qH0h0bgBIK/src/github.com/influxdb/influxdb/meta/state.go:187 +0x46e
	created by github.com/influxdb/influxdb/meta.(*localRaft).open
		/tmp/tmp.qH0h0bgBIK/src/github.com/influxdb/influxdb/meta/state.go:177 +0x130c

	goroutine 14 [chan receive, 262 minutes]:
	github.com/influxdb/influxdb/tcp.(*listener).Accept(0xc208039190, 0x0, 0x0, 0x0, 0x0)
		/tmp/tmp.qH0h0bgBIK/src/github.com/influxdb/influxdb/tcp/mux.go:117 +0x80
	github.com/influxdb/influxdb/meta.(*Store).serveExecListener(0xc20800c140)
		/tmp/tmp.qH0h0bgBIK/src/github.com/influxdb/influxdb/meta/store.go:619 +0x8f
	created by github.com/influxdb/influxdb/meta.(*Store).Open
		/tmp/tmp.qH0h0bgBIK/src/github.com/influxdb/influxdb/meta/store.go:239 +0x391

	goroutine 15 [chan receive, 262 minutes]:
	github.com/influxdb/influxdb/tcp.(*listener).Accept(0xc208039198, 0x0, 0x0, 0x0, 0x0)
		/tmp/tmp.qH0h0bgBIK/src/github.com/influxdb/influxdb/tcp/mux.go:117 +0x80
	github.com/influxdb/influxdb/meta.(*Store).serveRPCListener(0xc20800c140)
		/tmp/tmp.qH0h0bgBIK/src/github.com/influxdb/influxdb/meta/store.go:723 +0xc9
	created by github.com/influxdb/influxdb/meta.(*Store).Open
		/tmp/tmp.qH0h0bgBIK/src/github.com/influxdb/influxdb/meta/store.go:242 +0x3db

	goroutine 18 [select, 262 minutes]:
	github.com/influxdb/influxdb/cmd/influxd/run.(*Server).monitorErrorChan(0xc2080aa0e0, 0xc208072480)
		/tmp/tmp.qH0h0bgBIK/src/github.com/influxdb/influxdb/cmd/influxd/run/server.go:442 +0x14a
	created by github.com/influxdb/influxdb/cmd/influxd/run.func·003
		/tmp/tmp.qH0h0bgBIK/src/github.com/influxdb/influxdb/cmd/influxd/run/server.go:319 +0xa63

	goroutine 19 [select]:
	github.com/influxdb/influxdb/services/hh.(*Service).retryWrites(0xc208047220)
		/tmp/tmp.qH0h0bgBIK/src/github.com/influxdb/influxdb/services/hh/service.go:103 +0x2e7
	created by github.com/influxdb/influxdb/services/hh.(*Service).Open
		/tmp/tmp.qH0h0bgBIK/src/github.com/influxdb/influxdb/services/hh/service.go:67 +0x20e

	goroutine 20 [select, 21 minutes]:
	github.com/influxdb/influxdb/services/hh.(*Service).expireWrites(0xc208047220)
		/tmp/tmp.qH0h0bgBIK/src/github.com/influxdb/influxdb/services/hh/service.go:121 +0x2a4
	created by github.com/influxdb/influxdb/services/hh.(*Service).Open
		/tmp/tmp.qH0h0bgBIK/src/github.com/influxdb/influxdb/services/hh/service.go:68 +0x228

	goroutine 21 [chan receive, 262 minutes]:
	github.com/influxdb/influxdb/tcp.(*listener).Accept(0xc2080391a0, 0x0, 0x0, 0x0, 0x0)
		/tmp/tmp.qH0h0bgBIK/src/github.com/influxdb/influxdb/tcp/mux.go:117 +0x80
	github.com/influxdb/influxdb/cluster.(*Service).serve(0xc2080102a0)
		/tmp/tmp.qH0h0bgBIK/src/github.com/influxdb/influxdb/cluster/service.go:83 +0x102
	created by github.com/influxdb/influxdb/cluster.(*Service).Open
		/tmp/tmp.qH0h0bgBIK/src/github.com/influxdb/influxdb/cluster/service.go:60 +0x138

	goroutine 22 [select, 1 minutes]:
	github.com/influxdb/influxdb/services/precreator.(*Service).runPrecreation(0xc20800adc0)
		/tmp/tmp.qH0h0bgBIK/src/github.com/influxdb/influxdb/services/precreator/service.go:75 +0x407
	created by github.com/influxdb/influxdb/services/precreator.(*Service).Open
		/tmp/tmp.qH0h0bgBIK/src/github.com/influxdb/influxdb/services/precreator/service.go:53 +0x20a

	goroutine 23 [chan receive, 262 minutes]:
	github.com/influxdb/influxdb/tcp.(*listener).Accept(0xc2080391a8, 0x0, 0x0, 0x0, 0x0)
		/tmp/tmp.qH0h0bgBIK/src/github.com/influxdb/influxdb/tcp/mux.go:117 +0x80
	github.com/influxdb/influxdb/services/snapshotter.(*Service).serve(0xc20800aeb0)
		/tmp/tmp.qH0h0bgBIK/src/github.com/influxdb/influxdb/services/snapshotter/service.go:75 +0xad
	created by github.com/influxdb/influxdb/services/snapshotter.(*Service).Open
		/tmp/tmp.qH0h0bgBIK/src/github.com/influxdb/influxdb/services/snapshotter/service.go:48 +0x133

	goroutine 24 [IO wait, 262 minutes]:
	net.(*pollDesc).Wait(0xc208010b50, 0x72, 0x0, 0x0)
		/usr/local/go/src/net/fd_poll_runtime.go:84 +0x47
	net.(*pollDesc).WaitRead(0xc208010b50, 0x0, 0x0)
		/usr/local/go/src/net/fd_poll_runtime.go:89 +0x43
	net.(*netFD).accept(0xc208010af0, 0x0, 0x7fa8d625ee30, 0xc2080dde38)
		/usr/local/go/src/net/fd_unix.go:419 +0x40b
	net.(*TCPListener).AcceptTCP(0xc208039260, 0xf02120, 0x0, 0x0)
		/usr/local/go/src/net/tcpsock_posix.go:234 +0x4e
	net.(*TCPListener).Accept(0xc208039260, 0x0, 0x0, 0x0, 0x0)
		/usr/local/go/src/net/tcpsock_posix.go:244 +0x4c
	net/http.(*Server).Serve(0xc208073680, 0x7fa8d6261428, 0xc208039260, 0x0, 0x0)
		/usr/local/go/src/net/http/server.go:1728 +0x92
	net/http.Serve(0x7fa8d6261428, 0xc208039260, 0x7fa8d6262bf0, 0xc2080ddf10, 0x0, 0x0)
		/usr/local/go/src/net/http/server.go:1606 +0xa1
	github.com/influxdb/influxdb/services/admin.(*Service).serve(0xc20800af50)
		/tmp/tmp.qH0h0bgBIK/src/github.com/influxdb/influxdb/services/admin/service.go:107 +0x147
	created by github.com/influxdb/influxdb/services/admin.(*Service).Open
		/tmp/tmp.qH0h0bgBIK/src/github.com/influxdb/influxdb/services/admin/service.go:70 +0x472

	goroutine 25 [select]:
	github.com/influxdb/influxdb/services/continuous_querier.(*Service).backgroundLoop(0xc208010310)
		/tmp/tmp.qH0h0bgBIK/src/github.com/influxdb/influxdb/services/continuous_querier/service.go:157 +0x3e9
	created by github.com/influxdb/influxdb/services/continuous_querier.(*Service).Open
		/tmp/tmp.qH0h0bgBIK/src/github.com/influxdb/influxdb/services/continuous_querier/service.go:93 +0x2df

	goroutine 26 [IO wait, 9 minutes]:
	net.(*pollDesc).Wait(0xc208010bc0, 0x72, 0x0, 0x0)
		/usr/local/go/src/net/fd_poll_runtime.go:84 +0x47
	net.(*pollDesc).WaitRead(0xc208010bc0, 0x0, 0x0)
		/usr/local/go/src/net/fd_poll_runtime.go:89 +0x43
	net.(*netFD).accept(0xc208010b60, 0x0, 0x7fa8d625ee30, 0xc25b9491b0)
		/usr/local/go/src/net/fd_unix.go:419 +0x40b
	net.(*TCPListener).AcceptTCP(0xc208039268, 0xc2080eedc8, 0x0, 0x0)
		/usr/local/go/src/net/tcpsock_posix.go:234 +0x4e
	net.(*TCPListener).Accept(0xc208039268, 0x0, 0x0, 0x0, 0x0)
		/usr/local/go/src/net/tcpsock_posix.go:244 +0x4c
	net/http.(*Server).Serve(0xc20812a120, 0x7fa8d6261428, 0xc208039268, 0x0, 0x0)
		/usr/local/go/src/net/http/server.go:1728 +0x92
	net/http.Serve(0x7fa8d6261428, 0xc208039268, 0x7fa8d6262ba0, 0xc208010380, 0x0, 0x0)
		/usr/local/go/src/net/http/server.go:1606 +0xa1
	github.com/influxdb/influxdb/services/httpd.(*Service).serve(0xc20800b090)
		/tmp/tmp.qH0h0bgBIK/src/github.com/influxdb/influxdb/services/httpd/service.go:108 +0x79
	created by github.com/influxdb/influxdb/services/httpd.(*Service).Open
		/tmp/tmp.qH0h0bgBIK/src/github.com/influxdb/influxdb/services/httpd/service.go:76 +0x68b

	goroutine 27 [select, 1 minutes]:
	github.com/influxdb/influxdb/services/retention.(*Service).deleteShardGroups(0xc2080729c0)
		/tmp/tmp.qH0h0bgBIK/src/github.com/influxdb/influxdb/services/retention/service.go:69 +0x342
	created by github.com/influxdb/influxdb/services/retention.(*Service).Open
		/tmp/tmp.qH0h0bgBIK/src/github.com/influxdb/influxdb/services/retention/service.go:45 +0x138

	goroutine 28 [select, 1 minutes]:
	github.com/influxdb/influxdb/services/retention.(*Service).deleteShards(0xc2080729c0)
		/tmp/tmp.qH0h0bgBIK/src/github.com/influxdb/influxdb/services/retention/service.go:102 +0x71b
	created by github.com/influxdb/influxdb/services/retention.(*Service).Open
		/tmp/tmp.qH0h0bgBIK/src/github.com/influxdb/influxdb/services/retention/service.go:46 +0x152

	goroutine 29 [chan receive, 262 minutes]:
	github.com/influxdb/influxdb/cmd/influxd/run.(*Server).startServerReporting(0xc2080aa0e0)
		/tmp/tmp.qH0h0bgBIK/src/github.com/influxdb/influxdb/cmd/influxd/run/server.go:393 +0x1d7
	created by github.com/influxdb/influxdb/cmd/influxd/run.func·003
		/tmp/tmp.qH0h0bgBIK/src/github.com/influxdb/influxdb/cmd/influxd/run/server.go:342 +0xf0e

	goroutine 30 [select, 262 minutes]:
	github.com/influxdb/influxdb/cmd/influxd/run.(*Command).monitorServerErrors(0xc2080ac300)
		/tmp/tmp.qH0h0bgBIK/src/github.com/influxdb/influxdb/cmd/influxd/run/command.go:140 +0x2da
	created by github.com/influxdb/influxdb/cmd/influxd/run.(*Command).Run
		/tmp/tmp.qH0h0bgBIK/src/github.com/influxdb/influxdb/cmd/influxd/run/command.go:122 +0xdef

	goroutine 13520 [select]:
	github.com/influxdb/influxdb/tsdb/engine/wal.(*Log).autoflusher(0xc263a762a0, 0xc2689531a0)
		/tmp/tmp.qH0h0bgBIK/src/github.com/influxdb/influxdb/tsdb/engine/wal/wal.go:587 +0x458
	created by github.com/influxdb/influxdb/tsdb/engine/wal.(*Log).Open
		/tmp/tmp.qH0h0bgBIK/src/github.com/influxdb/influxdb/tsdb/engine/wal/wal.go:215 +0x4bc

	goroutine 1647 [IO wait, 41 minutes]:
	net.(*pollDesc).Wait(0xc244fd8ca0, 0x72, 0x0, 0x0)
		/usr/local/go/src/net/fd_poll_runtime.go:84 +0x47
	net.(*pollDesc).WaitRead(0xc244fd8ca0, 0x0, 0x0)
		/usr/local/go/src/net/fd_poll_runtime.go:89 +0x43
	net.(*netFD).Read(0xc244fd8c40, 0xc20d54d000, 0x1000, 0x1000, 0x0, 0x7fa8d625ee30, 0xc2775c34c8)
		/usr/local/go/src/net/fd_unix.go:242 +0x40f
	net.(*conn).Read(0xc243405ef0, 0xc20d54d000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
		/usr/local/go/src/net/net.go:121 +0xdc
	net/http.(*liveSwitchReader).Read(0xc241b28a48, 0xc20d54d000, 0x1000, 0x1000, 0xc20800aff0, 0x0, 0x0)
		/usr/local/go/src/net/http/server.go:214 +0xab
	io.(*LimitedReader).Read(0xc2258c20c0, 0xc20d54d000, 0x1000, 0x1000, 0xc27a0dd940, 0x0, 0x0)
		/usr/local/go/src/io/io.go:408 +0xce
	bufio.(*Reader).fill(0xc21e2790e0)
		/usr/local/go/src/bufio/bufio.go:97 +0x1ce
	bufio.(*Reader).ReadSlice(0xc21e2790e0, 0xa, 0x0, 0x0, 0x0, 0x0, 0x0)
		/usr/local/go/src/bufio/bufio.go:295 +0x257
	bufio.(*Reader).ReadLine(0xc21e2790e0, 0x0, 0x0, 0x0, 0xc224cced00, 0x0, 0x0)
		/usr/local/go/src/bufio/bufio.go:324 +0x62
	net/textproto.(*Reader).readLineSlice(0xc24f395f50, 0x0, 0x0, 0x0, 0x0, 0x0)
		/usr/local/go/src/net/textproto/reader.go:55 +0x9e
	net/textproto.(*Reader).ReadLine(0xc24f395f50, 0x0, 0x0, 0x0, 0x0)
		/usr/local/go/src/net/textproto/reader.go:36 +0x4f
	net/http.ReadRequest(0xc21e2790e0, 0xc27cccd5f0, 0x0, 0x0)
		/usr/local/go/src/net/http/request.go:598 +0xcb
	net/http.(*conn).readRequest(0xc241b28a00, 0x0, 0x0, 0x0)
		/usr/local/go/src/net/http/server.go:586 +0x26f
	net/http.(*conn).serve(0xc241b28a00)
		/usr/local/go/src/net/http/server.go:1162 +0x69e
	created by net/http.(*Server).Serve
		/usr/local/go/src/net/http/server.go:1751 +0x35e

	goroutine 1380 [IO wait, 39 minutes]:
	net.(*pollDesc).Wait(0xc23d8b3d40, 0x72, 0x0, 0x0)
		/usr/local/go/src/net/fd_poll_runtime.go:84 +0x47
	net.(*pollDesc).WaitRead(0xc23d8b3d40, 0x0, 0x0)
		/usr/local/go/src/net/fd_poll_runtime.go:89 +0x43
	net.(*netFD).Read(0xc23d8b3ce0, 0xc22578e000, 0x1000, 0x1000, 0x0, 0x7fa8d625ee30, 0xc20f21a588)
		/usr/local/go/src/net/fd_unix.go:242 +0x40f
	net.(*conn).Read(0xc20812c350, 0xc22578e000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
		/usr/local/go/src/net/net.go:121 +0xdc
	net/http.(*liveSwitchReader).Read(0xc23810fbc8, 0xc22578e000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
		/usr/local/go/src/net/http/server.go:214 +0xab
	io.(*LimitedReader).Read(0xc21e807c20, 0xc22578e000, 0x1000, 0x1000, 0xc2f6575940, 0x0, 0x0)
		/usr/local/go/src/io/io.go:408 +0xce
	bufio.(*Reader).fill(0xc23c5494a0)
		/usr/local/go/src/bufio/bufio.go:97 +0x1ce
	bufio.(*Reader).ReadSlice(0xc23c5494a0, 0xa, 0x0, 0x0, 0x0, 0x0, 0x0)
		/usr/local/go/src/bufio/bufio.go:295 +0x257
	bufio.(*Reader).ReadLine(0xc23c5494a0, 0x0, 0x0, 0x0, 0xc204889100, 0x0, 0x0)
		/usr/local/go/src/bufio/bufio.go:324 +0x62
	net/textproto.(*Reader).readLineSlice(0xc23f76e840, 0x0, 0x0, 0x0, 0x0, 0x0)
		/usr/local/go/src/net/textproto/reader.go:55 +0x9e
	net/textproto.(*Reader).ReadLine(0xc23f76e840, 0x0, 0x0, 0x0, 0x0)
		/usr/local/go/src/net/textproto/reader.go:36 +0x4f
	net/http.ReadRequest(0xc23c5494a0, 0xc29a8a36c0, 0x0, 0x0)
		/usr/local/go/src/net/http/request.go:598 +0xcb
	net/http.(*conn).readRequest(0xc23810fb80, 0x0, 0x0, 0x0)
		/usr/local/go/src/net/http/server.go:586 +0x26f
	net/http.(*conn).serve(0xc23810fb80)
		/usr/local/go/src/net/http/server.go:1162 +0x69e
	created by net/http.(*Server).Serve
		/usr/local/go/src/net/http/server.go:1751 +0x35e

### PR DESCRIPTION
**Pull request by pauldix**
/cc @benbjohnson 

@bobuss, I think this will fix #3730

### CODE REVIEW

**Comment by benbjohnson** [comment]
:+1:

**Comment by pauldix** [comment]
cherry picked into 0.9.3

**Comment by kenzodeluxe** [comment]
@pauldix Ran into the same issue with 0.9.3rc1 last night. Would this be available in the latest nightly?

**Comment by bobuss** [comment]
awesome ! I 'm going to test it ASAP

**Pull request merged**
