### PR TITLE
Don't set client to nil when closing broker

### PR DESCRIPTION
**Pull request by jwilder**
Fixes 2352

### CODE REVIEW

**Comment by otoolep** [comment]
This kind of makes sense. Really, isn't the `broker` type missing an `Open` call, which should be called before the `broker` type is used? This seems to be just changing how `Close` works, when what is missing the `Open`? Or am I missing something?

**Comment by otoolep** [comment]
To be clear, in `Open` the client would be set to non-nil, it seems to me. This seems a fix to allow a broker object to be re-used after `Close()` has been called, but that would indicate a broken API. Make sense?

**Comment by jwilder** [comment]
The `client` is already created and set when the broker is created here: https://github.com/influxdb/influxdb/blob/master/broker.go#L47  

This nil pointer is in the `http.Client` here: https://github.com/golang/go/blob/release-branch.go1.4/src/net/http/client.go#L304

Since we're using the `DefaultTransport` and `http.Client` are supposed to be reused, setting it to nil doesn't make sense.

**Comment by otoolep** [comment]
OK, very good -- thanks @jwilder . That was the context I was missing.

+1

**Pull request merged**
