### PR TITLE
Skip cluster tests until fixed

### PR DESCRIPTION
**Pull request by otoolep**

### CODE REVIEW

**Comment by otoolep** [comment]
@dgnorton @corylanou

**Comment by pauldix** [comment]
Don't the meta tests need to be skipped too?

**Comment by otoolep** [comment]
Yeah, I was wondering about those.

**Comment by otoolep** [comment]
TestCluster_OpenRaft is another culprit which would fall in the meta test category, so yeah, skipping those might make sense.

**Comment by otoolep** [comment]
(I think OpenRaft has been issue, not fully sure).

**Comment by otoolep** [comment]
I would be nervous about skipping those just yet @pauldix -- they are pretty important and the failure rate after this merge may be back to tolerable.

OK if I merge this skip, and we deal with those separately?

**Comment by otoolep** [comment]
In other words I'd rather deal with a tolerably low-failure rate (which we don't have right now) in the meta package if if prevents us from checking in a real bug in that code.

**Comment by corylanou** [comment]
We may need a different approach to these tests.  I'll discuss it in todays meeting.  For now, +1 to get the tests stable until we can re-address.

**Pull request merged**
