### PR TITLE
Do not allow wildcards with fields in select statements

### PR DESCRIPTION
**Pull request by corylanou**
The following queries should not be valid:

```sql
select *, foo from bar
select foo, * from bar
select *, * from bar
```

### CODE REVIEW

**Comment by DanielMorsing** [comment]
I think there is a place for this. Consider `select *, foo * 20 from bar`, where the users wants to see all the fields and some derived value from it.

**Comment by corylanou** [comment]
@DanielMorsing yes, I agree, there are several good reasons.  We are putting this in here because we don't currently support it.  Once the query engine has support for it, we will remove this restriction.

**Comment by DanielMorsing** [comment]
+1 if a TODO is added that states that this is temporary in validateWildcard

**Comment by corylanou** [comment]
@DanielMorsing I opened an issue, which is more likely to get noticed than a `TODO` in the code.

https://github.com/influxdb/influxdb/issues/3582

**Pull request merged**
