### PR TITLE
Fix directory path for build command

### PR DESCRIPTION
**Pull request by mnuessler**

### CODE REVIEW

**Comment by otoolep** [comment]
Thanks for the path @mnuessler. Did the existing directions not work for you?

The build break is a race condition we're tracking down in our code.

**Comment by mnuessler** [comment]
Hi @otoolep, ok I signed the CLA now. Yes, just now I tried building InfluxDB and noticed that the path in the directions for "Build and Test" seems to be wrong. I had to cd into `$GOPATH/src/github.com/influxdb/influxdb` for the build command to work. Further down in the instructions, where the command for running the tests is described, the path is correct again.

**Comment by otoolep** [comment]
Strange, because the build directions work for me as-is. I do want to fix it, but could you show me the output when you walk through the existing steps? I'd like to see the errors you are getting.

**Comment by mnuessler** [comment]
The output I got was:
```
$ cd $GOPATH/src/github.com/influxdb
$ go get -u -f ./...
package github.com/influxdb/...: cannot expand ... in "github.com/influxdb/..."
```
But it seems that the problem was related to my environment. Under $GOPATH/src/github.com/influxdb I had a symlink to the Git repo that I cloned to a different location. If I follow the instructions exactly and do
```
cd $GOPATH/src/github.com/influxdb
git clone git@github.com:influxdb/influxdb
```
then the build works fine as is.

I guess the PR can be closed. Anyway, thanks for your help!

**Pull request closed without merging**
