### PR TITLE
Remove obsolete config flags from tsdb

### PR DESCRIPTION
**Pull request by otoolep**
These flags are obsolete, and holdovers from the recent refactoring for our new design. These features are now controlled as services, and the configuration is controlled there.

### CODE REVIEW

**Comment by otoolep** [comment]
@corylanou

**Comment by otoolep** [comment]
Spotted while working this PR: https://github.com/influxdb/influxdb/pull/3203

**Comment by corylanou** [comment]
Where do those defaults get set now?  Clearly no through TSDB, but they should be somewhere right?

**Comment by otoolep** [comment]
@corylanou -- they get set in `services/retention` and `services/precreator`.

**Comment by otoolep** [comment]
And `meta/config.go`.

**Comment by corylanou** [comment]
Sounds good.  +1

**Pull request merged**
