### PR TITLE
Fix install path in CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by iakshay**
- [ ] CHANGELOG.md updated
- [x] Rebased/mergable
- [x] Tests pass
- [x] Sign [CLA](http://influxdb.com/community/cla.html) (if not already signed)

### CODE REVIEW

**Comment by otoolep** [comment]
Thanks @iakshay 

Actually, the existing instructions work fine. Any reason why you think it should be changed?

**Comment by iakshay** [comment]
I tried running `go get -u -f -t ./...` inside `$GOPATH/src/github.com/influxdb` and got an error, moving into influxdb project fixed the issue.

**Comment by otoolep** [comment]
Can I see the error?

**Comment by iakshay** [comment]
```bash
➜  influxdb  go get -u -f -t ./...
package _/Users/akshay/Projects/gocode/src/github.com/influxdb/enterprise-client/v1: unrecognized import path "_/Users/akshay/Projects/gocode/src/github.com/influxdb/enterprise-client/v1"
package _/Users/akshay/Projects/gocode/src/github.com/influxdb/influxdb: unrecognized import path "_/Users/akshay/Projects/gocode/src/github.com/influxdb/influxdb"
package _/Users/akshay/Projects/gocode/src/github.com/influxdb/influxdb/client: unrecognized import path "_/Users/akshay/Projects/gocode/src/github.com/influxdb/influxdb/client"
package _/Users/akshay/Projects/gocode/src/github.com/influxdb/influxdb/client/v2: unrecognized import path "_/Users/akshay/Projects/gocode/src/github.com/influxdb/influxdb/client/v2"
package _/Users/akshay/Projects/gocode/src/github.com/influxdb/influxdb/cluster: unrecognized import path "_/Users/akshay/Projects/gocode/src/github.com/influxdb/influxdb/cluster"
package _/Users/akshay/Projects/gocode/src/github.com/influxdb/influxdb/cluster/internal: unrecognized import path "_/Users/akshay/Projects/gocode/src/github.com/influxdb/influxdb/cluster/internal"
package _/Users/akshay/Projects/gocode/src/github.com/influxdb/influxdb/cmd/influx: unrecognized import path "_/Users/akshay/Projects/gocode/src/github.com/influxdb/influxdb/cmd/influx"
package _/Users/akshay/Projects/gocode/src/github.com/influxdb/influxdb/cmd/influx/cli: unrecognized import path "_/Users/akshay/Projects/gocode/src/github.com/influxdb/influxdb/cmd/influx/cli"
package _/Users/akshay/Projects/gocode/src/github.com/influxdb/influxdb/cmd/influx_inspect: unrecognized import path "_/Users/akshay/Projects/gocode/src/github.com/influxdb/influxdb/cmd/influx_inspect"
package _/Users/akshay/Projects/gocode/src/github.com/influxdb/influxdb/cmd/influx_stress: unrecognized import path "_/Users/akshay/Projects/gocode/src/github.com/influxdb/influxdb/cmd/influx_stress"
package _/Users/akshay/Projects/gocode/src/github.com/influxdb/influxdb/cmd/influxd: unrecognized import path "_/Users/akshay/Projects/gocode/src/github.com/influxdb/influxdb/cmd/influxd"
package _/Users/akshay/Projects/gocode/src/github.com/influxdb/influxdb/cmd/influxd/backup: unrecognized import path "_/Users/akshay/Projects/gocode/src/github.com/influxdb/influxdb/cmd/influxd/backup"
package _/Users/akshay/Projects/gocode/src/github.com/influxdb/influxdb/cmd/influxd/help: unrecognized import path "_/Users/akshay/Projects/gocode/src/github.com/influxdb/influxdb/cmd/influxd/help"
package _/Users/akshay/Projects/gocode/src/github.com/influxdb/influxdb/cmd/influxd/restore: unrecognized import path "_/Users/akshay/Projects/gocode/src/github.com/influxdb/influxdb/cmd/influxd/restore"
package _/Users/akshay/Projects/gocode/src/github.com/influxdb/influxdb/cmd/influxd/run: unrecognized import path "_/Users/akshay/Projects/gocode/src/github.com/influxdb/influxdb/cmd/influxd/run"
package _/Users/akshay/Projects/gocode/src/github.com/influxdb/influxdb/importer/v8: unrecognized import path "_/Users/akshay/Projects/gocode/src/github.com/influxdb/influxdb/importer/v8"
package _/Users/akshay/Projects/gocode/src/github.com/influxdb/influxdb/influxql: unrecognized import path "_/Users/akshay/Projects/gocode/src/github.com/influxdb/influxdb/influxql"
package _/Users/akshay/Projects/gocode/src/github.com/influxdb/influxdb/meta: unrecognized import path "_/Users/akshay/Projects/gocode/src/github.com/influxdb/influxdb/meta"
package _/Users/akshay/Projects/gocode/src/github.com/influxdb/influxdb/meta/internal: unrecognized import path "_/Users/akshay/Projects/gocode/src/github.com/influxdb/influxdb/meta/internal"
package _/Users/akshay/Projects/gocode/src/github.com/influxdb/influxdb/models: unrecognized import path "_/Users/akshay/Projects/gocode/src/github.com/influxdb/influxdb/models"
package _/Users/akshay/Projects/gocode/src/github.com/influxdb/influxdb/monitor: unrecognized import path "_/Users/akshay/Projects/gocode/src/github.com/influxdb/influxdb/monitor"
package _/Users/akshay/Projects/gocode/src/github.com/influxdb/influxdb/pkg/escape: unrecognized import path "_/Users/akshay/Projects/gocode/src/github.com/influxdb/influxdb/pkg/escape"
package _/Users/akshay/Projects/gocode/src/github.com/influxdb/influxdb/pkg/slices: unrecognized import path "_/Users/akshay/Projects/gocode/src/github.com/influxdb/influxdb/pkg/slices"
package _/Users/akshay/Projects/gocode/src/github.com/influxdb/influxdb/services/admin: unrecognized import path "_/Users/akshay/Projects/gocode/src/github.com/influxdb/influxdb/services/admin"
package _/Users/akshay/Projects/gocode/src/github.com/influxdb/influxdb/services/collectd: unrecognized import path "_/Users/akshay/Projects/gocode/src/github.com/influxdb/influxdb/services/collectd"
package _/Users/akshay/Projects/gocode/src/github.com/influxdb/influxdb/services/collectd/test_client: unrecognized import path "_/Users/akshay/Projects/gocode/src/github.com/influxdb/influxdb/services/collectd/test_client"
package _/Users/akshay/Projects/gocode/src/github.com/influxdb/influxdb/services/continuous_querier: unrecognized import path "_/Users/akshay/Projects/gocode/src/github.com/influxdb/influxdb/services/continuous_querier"
package _/Users/akshay/Projects/gocode/src/github.com/influxdb/influxdb/services/copier: unrecognized import path "_/Users/akshay/Projects/gocode/src/github.com/influxdb/influxdb/services/copier"
package _/Users/akshay/Projects/gocode/src/github.com/influxdb/influxdb/services/copier/internal: unrecognized import path "_/Users/akshay/Projects/gocode/src/github.com/influxdb/influxdb/services/copier/internal"
package _/Users/akshay/Projects/gocode/src/github.com/influxdb/influxdb/services/graphite: unrecognized import path "_/Users/akshay/Projects/gocode/src/github.com/influxdb/influxdb/services/graphite"
package _/Users/akshay/Projects/gocode/src/github.com/influxdb/influxdb/services/hh: unrecognized import path "_/Users/akshay/Projects/gocode/src/github.com/influxdb/influxdb/services/hh"
package _/Users/akshay/Projects/gocode/src/github.com/influxdb/influxdb/services/httpd: unrecognized import path "_/Users/akshay/Projects/gocode/src/github.com/influxdb/influxdb/services/httpd"
package _/Users/akshay/Projects/gocode/src/github.com/influxdb/influxdb/services/opentsdb: unrecognized import path "_/Users/akshay/Projects/gocode/src/github.com/influxdb/influxdb/services/opentsdb"
package _/Users/akshay/Projects/gocode/src/github.com/influxdb/influxdb/services/precreator: unrecognized import path "_/Users/akshay/Projects/gocode/src/github.com/influxdb/influxdb/services/precreator"
package _/Users/akshay/Projects/gocode/src/github.com/influxdb/influxdb/services/registration: unrecognized import path "_/Users/akshay/Projects/gocode/src/github.com/influxdb/influxdb/services/registration"
package _/Users/akshay/Projects/gocode/src/github.com/influxdb/influxdb/services/retention: unrecognized import path "_/Users/akshay/Projects/gocode/src/github.com/influxdb/influxdb/services/retention"
package _/Users/akshay/Projects/gocode/src/github.com/influxdb/influxdb/services/snapshotter: unrecognized import path "_/Users/akshay/Projects/gocode/src/github.com/influxdb/influxdb/services/snapshotter"
package _/Users/akshay/Projects/gocode/src/github.com/influxdb/influxdb/services/subscriber: unrecognized import path "_/Users/akshay/Projects/gocode/src/github.com/influxdb/influxdb/services/subscriber"
package _/Users/akshay/Projects/gocode/src/github.com/influxdb/influxdb/services/udp: unrecognized import path "_/Users/akshay/Projects/gocode/src/github.com/influxdb/influxdb/services/udp"
package _/Users/akshay/Projects/gocode/src/github.com/influxdb/influxdb/snapshot: unrecognized import path "_/Users/akshay/Projects/gocode/src/github.com/influxdb/influxdb/snapshot"
package _/Users/akshay/Projects/gocode/src/github.com/influxdb/influxdb/statik: unrecognized import path "_/Users/akshay/Projects/gocode/src/github.com/influxdb/influxdb/statik"
package _/Users/akshay/Projects/gocode/src/github.com/influxdb/influxdb/stress: unrecognized import path "_/Users/akshay/Projects/gocode/src/github.com/influxdb/influxdb/stress"
package _/Users/akshay/Projects/gocode/src/github.com/influxdb/influxdb/stress/stress_test_server: unrecognized import path "_/Users/akshay/Projects/gocode/src/github.com/influxdb/influxdb/stress/stress_test_server"
package _/Users/akshay/Projects/gocode/src/github.com/influxdb/influxdb/tcp: unrecognized import path "_/Users/akshay/Projects/gocode/src/github.com/influxdb/influxdb/tcp"
package _/Users/akshay/Projects/gocode/src/github.com/influxdb/influxdb/tests/urlgen: unrecognized import path "_/Users/akshay/Projects/gocode/src/github.com/influxdb/influxdb/tests/urlgen"
package _/Users/akshay/Projects/gocode/src/github.com/influxdb/influxdb/toml: unrecognized import path "_/Users/akshay/Projects/gocode/src/github.com/influxdb/influxdb/toml"
package _/Users/akshay/Projects/gocode/src/github.com/influxdb/influxdb/tsdb: unrecognized import path "_/Users/akshay/Projects/gocode/src/github.com/influxdb/influxdb/tsdb"
package _/Users/akshay/Projects/gocode/src/github.com/influxdb/influxdb/tsdb/engine: unrecognized import path "_/Users/akshay/Projects/gocode/src/github.com/influxdb/influxdb/tsdb/engine"
package _/Users/akshay/Projects/gocode/src/github.com/influxdb/influxdb/tsdb/engine/b1: unrecognized import path "_/Users/akshay/Projects/gocode/src/github.com/influxdb/influxdb/tsdb/engine/b1"
package _/Users/akshay/Projects/gocode/src/github.com/influxdb/influxdb/tsdb/engine/bz1: unrecognized import path "_/Users/akshay/Projects/gocode/src/github.com/influxdb/influxdb/tsdb/engine/bz1"
package _/Users/akshay/Projects/gocode/src/github.com/influxdb/influxdb/tsdb/engine/tsm1: unrecognized import path "_/Users/akshay/Projects/gocode/src/github.com/influxdb/influxdb/tsdb/engine/tsm1"
package _/Users/akshay/Projects/gocode/src/github.com/influxdb/influxdb/tsdb/engine/wal: unrecognized import path "_/Users/akshay/Projects/gocode/src/github.com/influxdb/influxdb/tsdb/engine/wal"
package _/Users/akshay/Projects/gocode/src/github.com/influxdb/influxdb/tsdb/internal: unrecognized import path "_/Users/akshay/Projects/gocode/src/github.com/influxdb/influxdb/tsdb/internal"
package _/Users/akshay/Projects/gocode/src/github.com/influxdb/influxdb/uuid: unrecognized import path "_/Users/akshay/Projects/gocode/src/github.com/influxdb/influxdb/uuid"

**Comment by iakshay** [comment]
I'm using zsh on OSX 10.10.5

**Comment by otoolep** [comment]
CLA signed. Docs only.

OK, it must be a distro issue. Since the updated instructions also work, I will merge. Thanks @iakshay

**Pull request merged**
