### PR TITLE
Fix spelling errors in comments and strings.

### PR DESCRIPTION
**Pull request by jbcrail**
I focused primarily on comments, but several strings were corrected.

### CODE REVIEW

**Comment by otoolep** [comment]
Thanks @jbcrail -- have you signed the CLA?

**Comment by otoolep** [comment]
Closed in error.

**Comment by jbcrail** [comment]
I signed it yesterday. I couldn't find a public link to it to confirm this.

**Comment by otoolep** [comment]
Great, thanks @jbcrail

**Comment by otoolep** [comment]
Verified cosmetic changes only, merging now.

Thanks again @jbcrail

**Pull request merged**
