### PR TITLE
Rewrite urlgen in Go

### PR DESCRIPTION
**Pull request by rothrock**
Issue: 1818

This is meant to replace the urlgen shell script.

### CODE REVIEW

**Comment by benbjohnson** [comment]
It's a lot cleaner if you use the `encoding/json` package and then you won't have an issue if we use characters that require escaping in the future. Also, it makes it clearer to name the arguments and use separate iterator variables (`i`, `j`, `k`):

https://gist.github.com/benbjohnson/173a8bdd60686f7853d8

Another request would be to move the generation to types so they can be tested.

**Comment by dgnorton** [comment]
Works like a champ for me!  :shipit:

**Comment by dgnorton** [comment]
@benbjohnson  should the time stamp be excluded?

**Comment by benbjohnson** [comment]
@dgnorton Excluded from the `Point` type? Doesn't it need to be there when writing the point?

**Comment by dgnorton** [comment]
@benbjohnson from the generated data being written.  Won't it use the current time if none is provided?  The reason I ask is that I left siege running for a while today and when I came back it was still hammering away, writing successfully, but I get nothing back from selects.  I thought maybe it was the same problem I had recently due to writing points in the past and they no longer show up after retention cleanup.  Dunno.  I also tried dropping the db, recreating it and the RP, and starting siege again...still get nothing back from selects...or show measurements / series.

**Comment by benbjohnson** [comment]
The reason I added a known timestamp was so we'd know the time range to query. I think I did it before RPs were dropping shards so maybe the old dates are being dropped now. Sure, we can drop the timestamp.

**Comment by dgnorton** [comment]
@rothrock The new version isn't generating the data correctly.  The points need to be contained by an outer struct so the generated JSON has `{"database" : "db", "retentionPolicy" : "raw", "points": ...`

**Comment by dgnorton** [comment]
@rothrock  in a quick test, this worked for me ... https://gist.github.com/dgnorton/b88cfc6b7f442721301b

**Comment by rothrock** [comment]
@dgnorton thanks for the help. Want to see if this works? I've added a date argument that defaults to now().

**Comment by dgnorton** [comment]
I think we also need two other features:

- Ability to increment the starting timestamp by some amount.
- Ability to exclude timestamps

The reason for these two features is that when I tested with it in it's current state it continually overwrites existing points because the timestamp doesn't change.  If I remove the timestamp, it generates new points.

@benbjohnson thoughts?

**Comment by dgnorton** [comment]
Sorry...scratch that.  I don't think I pulled in your changes the first time.  It's always creating new points now.  LGTM  :shipit:

**Pull request merged**
