### PR TITLE
Revert to Go 1.4.2

### PR DESCRIPTION
**Pull request by otoolep**
This is not passing 'go vet' under 1.4.2.

### CODE REVIEW

**Comment by otoolep** [comment]
@sparrc -- can you please pull down this branch and see if you can fix these errors under Go 1.4.2?

```
$ go tool vet ./
client/example_test.go:15: ExampleNewClient refers to unknown identifier: NewClient
client/example_test.go:35: ExampleClient_Ping refers to unknown identifier: Client
client/example_test.go:52: ExampleClient_Query refers to unknown identifier: Client
client/example_test.go:71: ExampleClient_Write refers to unknown identifier: Client
client/v2/example_test.go:15: ExampleClient refers to unknown identifier: Client
client/v2/example_test.go:28: ExampleClient_uDP refers to unknown identifier: Client
client/v2/example_test.go:60: ExampleClient_write refers to unknown identifier: Client
client/v2/example_test.go:92: ExampleBatchPoints refers to unknown identifier: BatchPoints
client/v2/example_test.go:114: ExampleBatchPoints_setters refers to unknown identifier: BatchPoints
client/v2/example_test.go:135: ExamplePoint refers to unknown identifier: Point
client/v2/example_test.go:149: ExamplePoint_withoutTime refers to unknown identifier: Point
client/v2/example_test.go:163: ExampleClient_write1000 refers to unknown identifier: Client
client/v2/example_test.go:214: ExampleClient_query refers to unknown identifier: Client
client/v2/example_test.go:233: ExampleClient_createDatabase refers to unknown identifier: Client
```

**Comment by otoolep** [comment]
cc @rossmcdonald

**Comment by otoolep** [comment]
Fixes https://github.com/influxdb/influxdb/issues/4754

**Comment by otoolep** [comment]
It appears that the Go vet failures are local to my machine. @sparrc is double-checking.

@sparrc -- if everything is OK for you, can you review and +1?

**Comment by sparrc** [comment]
+1, worked for me on linux on `1.4.2`

**Pull request merged**
