### PR TITLE
Ensure WAL cache gets sorted when needed.

### LINKED ISSUE #3792: resort flag for wal cache can be inadvertently cleared
https://github.com/influxdb/influxdb/blob/master/tsdb/engine/wal/wal.go#L1302

A worked example: If the cache contains timestamps [1,2,5], then you insert 4, followed by 6, you can end up clearing the resort flag for that cache entry. This will cause the cache cursor to return non-sorted values when iterated over.

@pauldix

### PR DESCRIPTION
**Pull request by pauldix**
Fixes #3792 

/cc @DanielMorsing

### CODE REVIEW

**Comment by DanielMorsing** [comment]
+1

**Comment by otoolep** [comment]
+1

**Comment by toddboom** [comment]
+1

**Comment by pauldix** [comment]
wow, ok fixed. Too much going on today. Will merge on green

**Comment by toddboom** [comment]
Cherry-picked to `0.9.3`

**Pull request merged**
