### PR TITLE
FIX #4279 CLI support multiline

### LINKED ISSUE #4279: CLI to support multi-line queries
In quite a few cases, the query can be longer than one line can fit, so we have to move cursors back and forth to check the whole query.

Possible ways:

1. Use a liner which wraps line automatically.
2. Parse query in CLI and show prompt accordingly, something like python interpreter.
3. check trailing backslash, and join them to form a single query, like bash.

1 would be simplest given such library exists (or extend https://github.com/peterh/liner to support it), 3 is also acceptable and trivial to implement.

How do you guys think?

### PR DESCRIPTION
**Pull request by flisky**

### CODE REVIEW

**Comment by otoolep** [comment]
Thanks @flisky -- have you signed the CLA?

Can you provide a reference for this call?

**Comment by flisky** [comment]
Yes, I have signed the CLA with github name flisky.

**Comment by otoolep** [comment]
Can you point me at a GoDoc reference for that call?

**Comment by otoolep** [comment]
CLA confirmed signed.

**Comment by flisky** [comment]
https://godoc.org/github.com/peterh/liner#State.SetMultiLineMode

**Comment by gunnaraasen** [comment]
@otoolep GoDoc reference is [here](https://godoc.org/github.com/peterh/liner#State.SetMultiLineMode). It's a recent addition to the `liner` package authored by @flisky. Seems like the test error is unrelated to this change.

**Comment by otoolep** [comment]
@corylanou

**Comment by otoolep** [comment]
If it works, great.

@flisky -- can you show an example session of your CLI in action, with this change in place?

**Comment by otoolep** [comment]
@gunnaraasen -- do you think you could clone the repo from @flisky and build his CLI? We'd like to see this in action before merging.

**Comment by flisky** [comment]
Here is a commandline [session](https://asciinema.org/a/cgj804v9ta9t1xcgcrk5w2rhu), and please let me know if anything I missed.

There are two problems I knew -
1. PR peterh/liner#60 to fix multiline in repl loop - waiting for merging.
2. WINCH signal is not handled perfectly, but I think it's acceptable.

**Comment by gunnaraasen** [comment]
Thanks for the video @flisky. I can also confirm multiline wrapping works as expected.

screen shot 2015-11-18 at 6 50 30 pm

(also found out Github has a neat trick where PR branches can be checkout out directly using `git fetch origin pull/4807/head:<NEW-BRANCH-NAME>`)

@otoolep I think this PR is ready to merge.

**Comment by otoolep** [comment]
Thanks @gunnaraasen

**Comment by flisky** [comment]
Thanks for the tip, @gunnaraasen, and thanks for the merging, @otoolep:)

**Comment by flisky** [comment]
Hi there, may I ask for a t-shirt? Thanks,

**Comment by otoolep** [comment]
Sure! Email me your address.

**Pull request merged**
