### PR TITLE
removed trailing spaces

### PR DESCRIPTION
**Pull request by aviau**
noticed those when packaging 0.9.3 for Debian.

### CODE REVIEW

**Comment by otoolep** [comment]
Thanks for the cleanup @aviau

**Comment by aviau** [comment]
@otoolep Did I open the PR against 0.9.3?

Will you pus that on master too?

**Comment by otoolep** [comment]
Yes, you did, and I didn't notice. Can you re-open against master, and I will revert on 0.9.3. That ship has sailed, and we don't merge to that branch unless it's a bug fix.

Thanks @aviau

**Comment by aviau** [comment]
>  Can you re-open against master, and I will revert on 0.9.3

I did. See #4024

**Pull request merged**
