### PR TITLE
Actually allow HTTP logging to be enabled

### PR DESCRIPTION
**Pull request by otoolep**

### CODE REVIEW

**Comment by otoolep** [comment]
HTTP access logging must be controlled at handler-construction time, since construction is when routing, and logging, are actually set.

**Comment by otoolep** [comment]
Currently failing on Circle, investigating.

**Comment by mark-rushakoff** [comment]
Confirmed HTTP logging visible again. :+1:

**Comment by otoolep** [comment]
Thanks @mark-rushakoff

**Pull request merged**
