### PR TITLE
Support chunked responses

### PR DESCRIPTION
**Pull request by otoolep**

### CODE REVIEW

**Comment by otoolep** [comment]
@pauldix

**Comment by otoolep** [comment]
@corylanou @benbjohnson

**Comment by otoolep** [comment]
@corylanou -- this is basically the same as before, and I am copying @benbjohnson  since he was copied previously.

**Comment by otoolep** [comment]
OK, there is 1 final failure here -- I need to deal with chunking correctly. I've fixed the incorrect splitting into separate rows, but the fix is not quite right.

**Comment by pauldix** [comment]
Looks good, what's the last thing?

**Comment by otoolep** [comment]
Didn't quite get chunking right. Kicked the build again, because of a known race in the Raft code (which I need to look into).

**Comment by otoolep** [comment]
I will merge on a green build.

**Pull request merged**
