### PR TITLE
fix raw math query panic

### PR DESCRIPTION
**Pull request by mengjinglei**
influxDB will panic when apply math query like:
`select value + value from cpu`
this pr fix this, in addition, this pr make `select value + value from cpu` return the correct value

### CODE REVIEW

**Comment by otoolep** [comment]
This looks good @mengjinglei -- thanks.

Can you sign the CLA? https://influxdb.com/community/cla.html Once you do that we can get this merged.

**Comment by otoolep** [comment]
@dgnorton @corylanou

**Comment by corylanou** [comment]
+1.  Great test coverage.

**Comment by otoolep** [comment]
Waiting for CLA to be signed before merging.

**Comment by otoolep** [comment]
CLA has already been signed.

**Comment by mengjinglei** [comment]
sorry for the late reply, this pr only fix math query without aggregate functions like
`select value + value from cpu`
 but can not handle math query with aggregate functions like
`select mean(value) + max(value) from cpu` or `select min(value) + temperature from cpu`
I'm still working on this and will send a pr ASAP, thanks for your updating

**Comment by otoolep** [comment]
Great, thanks again @mengjinglei

**Pull request merged**
