### PR TITLE
Fix queries that have only time in their where clause

### PR DESCRIPTION
**Pull request by pauldix**
Needs fixing. Failing test case in `server_test.go` at `TestServer_ExecuteQuery` test

### CODE REVIEW

**Comment by otoolep** [comment]
Took this on today, at the request of @toddboom, digging into it.

**Comment by otoolep** [comment]
cc @pauldix @benbjohnson 

This final failure appears to be due to the aggregators adding a zero-time value, when no results should be returned.

We should be getting:
```
{
    "rows": [
        {
            "name": "cpu",
            "tags": {
                "region": "us-east"
            },
            "columns": [
                "time",
                "sum"
            ],
            "values": [
                [
                    "2000-01-01T00:00:10Z",
                    30
                ]
            ]
        }
    ]
}
```
but we get:
```
{
    "rows": [
        {
            "name": "cpu",
            "tags": {
                "region": "us-east"
            },
            "columns": [
                "time",
                "sum"
            ],
            "values": [
                [
                    "2000-01-01T00:00:10Z",
                    30
                ]
            ]
        },
        {
            "name": "cpu",
            "tags": {
                "region": "us-west"
            },
            "columns": [
                "time",
                "sum"
            ],
            "values": [
                [
                    "1970-01-01T00:00:00Z",
                    0
                ]
            ]
        }
    ]
}
```
Note the extra 1970 value.

I think the code needs to be able to differentiate between a the first value, which is not valid, and no values available. An idea could be to add `EOF()` to the iterators. Not sure though.

For example (not production code):
```
$ git diff
diff --git a/influxql/engine.go b/influxql/engine.go
index a183063..b48999e 100644
--- a/influxql/engine.go
+++ b/influxql/engine.go
@@ -40,6 +40,9 @@ type Iterator interface {
 
        // Next returns the next value from the iterator.
        Next() (key int64, value interface{})
+
+       // EOF returns whether the iterator is out of data.
+       EOF() bool
 }
 
 // Planner represents an object for creating execution plans.
@@ -475,6 +478,9 @@ func MapCount(itr Iterator, e *Emitter, tmin int64) {
 
 // MapSum computes the summation of values in an iterator.
 func MapSum(itr Iterator, e *Emitter, tmin int64) {
+       if itr.EOF() {
+               return
+       }
        n := float64(0)
        for k, v := itr.Next(); k != 0; k, v = itr.Next() {
                n += v.(float64)
diff --git a/tx.go b/tx.go
index 4d015b0..e108224 100644
--- a/tx.go
+++ b/tx.go
@@ -242,6 +242,10 @@ func (i *shardIterator) Next() (key int64, value interface{}) {
        return key, value
 }
 
+func (i *shardIterator) EOF() bool {
+       return false
+}
+
 type keyValue struct {
        key   int64
        value interface{}
```

**Comment by pauldix** [comment]
The fix was actually much easier than all that. See c6e7a7f9ea98a2885891bb38b2167023e4164acf.

I think this one is good to go. @otoolep, @benbjohnson

**Comment by otoolep** [comment]
Nice. +1.

**Comment by toddboom** [comment]
Yeah, this looks good to me also. :shipit:

**Pull request merged**
