### PR TITLE
Compaction concurrency

### PR DESCRIPTION
**Pull request by jwilder**
This PR changes how compactions run so that multiple compactions can run concurrently.  It also fixes several bugs that were discovered during this refactor.

Previously, the compaction planning was based on sizes of files and a single planning step.  The sizes were somewhat arbitrary and worked well for lower numbers of series <100k.  In the larger number of series, compactions could pile up and get bogged down compacting larger files causing lots of smaller files to pile up.  The single planner also could get backlogged causing files to pile.  Also, this size based strategy sometimes created files that would get isolated between larger files and never compacted further depending on the shape of the data and how it was compacted.

This PR switches the compactions to dedicated level based compactions.  It works as follows:
* Each level has a dedicated goroutine that compacts a given level.  It runs a planning step for that level and then kicks off multiple goroutines to compact that level concurrently.
* Cache snapshot compactions run continuously writing out level 1 files
* Level 1 files are compacted in multiple groups of 2 concurrently using a fast compaction (explained later).  These compactions create level 2 files.
* Level 2 files are compacted in multiple groups of 3 concurrently using a fast compaction method.  These produce level 3 files.
* Level 3 files are compacted in multiple groups of 4 concurrently using an optimal compaction method.  These produce level 4 files.
* Level 4 files are compacted in multiple groups of 4 concurrently using an optimal compaction method.  These are compacted back into new level 4 files until they hit the max size at which point they are skipped.

The fast compaction method basically combines multiple TSM files, but does not decode and re-chunk blocks for the same key unless there is an overlap in the points.  The optimal compaction method will decode and re-chunk to produce the fewest number of blocks containing 1000 points each.  My first attempt was to always run the optimal compaction for all levels, but it can get backed up causing many TSM files to accumulate.  Level 1 and 2 use the fast compaction to try to combine all the files produced (rather quickly) from the snapshot compactions so that they don't grow too fast an impact query performance.  When they get to a larger size in level 3 & 4, the optimal compaction increases the compression ratio by combining more files at once.  This takes more time though so we only want to do it when we know we are going to produce full blocks.

This strategy was worked out over multiple tests of varying sizes of series (up to 2.5M) and seems to work well in those tests.  Unfortunately, the code could be simpler and I plan to clean it up in subsequent PR as I am short on time.

Other changes in this PR are:

* Removed `MADV_RANDOM` and added `MMAP_POPULATE` to mmap calls for unix system.   The `MADV_RANDOM` caused some IOPS storms when running large compactions across many files.  Removing it dropped IOPS from 1-2k down to 4.  It appears that `MADV_RANDOM` disables the kernels readahead buffer which seems to cause lots of small IOPS reads for many of the mmap access.
* Fixed a bug in `KeyCursor` where blocks would be returned more than once.  If you were running a count type query, the count would appear to go up and then drop down after a compaction ran (removing the duplicate blocks).
* Fixed file rollover when writing TSM files.  The index was not included in the size, only the data blocks.  This caused files to be larger than the max which was confusing.  The data blocks were always in the first 2GB part of the file though.
* Fixed a bug in the compaction code where blocks would sometimes have overlapping min and max points.  This could cause the wrong result for queries.
* Added tombstone compaction into the planning steps.

### CODE REVIEW

**Comment by jwilder** [comment]
@otoolep @pauldix 

@toddboom This PR should be merged before any long term tests start.

**Comment by sebito91** [comment]
Massive +1 from us, thank you guys very much.

On Wednesday, December 23, 2015, Jason Wilder <notifications@github.com>
wrote:

> @otoolep <https://github.com/otoolep> @pauldix
> <https://github.com/pauldix>
>
> @toddboom <https://github.com/toddboom> This PR should be merged before
> any long term tests start.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/influxdb/influxdb/pull/5221#issuecomment-167022652>.
>


-- 

Sebastian Borza
---------------
PGP: EDC2 BF61 4B91 14F2 AAB4  06C9 3744 7F3F E411 0D3E

**Comment by pauldix** [comment]
Lot here, but I think it's good to go. Would like to see a later PR to see if we can clean up the many goroutines per shard thing, but looks great.

:shipit:

**Comment by daviesalex** [comment]
FWIW, we have been running this version for nearly a week now. The system appears stable under load (when built with Go 1.4.2, see #5217), which was not previously possible. Furthermore, a restart with >1TB of data on disk has succeeded (this never happened before). No memory leaks or other problems have appeared that we can tell. We have left a small number of Grafana dashboards refreshing against it.

This is a huge improvement on the original tsm1. Big +1 from us.

**Pull request merged**
