### PR TITLE
Fix up logging

### PR DESCRIPTION
**Pull request by otoolep**

### CODE REVIEW

**Comment by jwilder** [comment]
:+1:

**Comment by corylanou** [comment]
+1

**Comment by otoolep** [comment]
```
$ ./influxd 2>err

 8888888           .d888 888                   8888888b.  888888b.
   888            d88P"  888                   888  "Y88b 888  "88b
   888            888    888                   888    888 888  .88P
   888   88888b.  888888 888 888  888 888  888 888    888 8888888K.
   888   888 "88b 888    888 888  888  Y8bd8P' 888    888 888  "Y88b
   888   888  888 888    888 888  888   X88K   888    888 888    888
   888   888  888 888    888 Y88b 888 .d8""8b. 888  .d88P 888   d88P
 8888888 888  888 888    888  "Y88888 888  888 8888888P"  8888888P"

^C~/repos/influxdb/src/github.com/influxdb/influxdb/cmd/influxd (fix_up_logging)$ cat err
[srvr] 2015/03/25 18:13:46 No config provided, using default settings
[srvr] 2015/03/25 18:13:46 influxdb started, version 0.9, commit unknown
[srvr] 2015/03/25 18:13:46 Broker directory missing. Need to create a broker.
[srvr] 2015/03/25 18:13:46 Data directory missing. Need to create data directory.
[srvr] 2015/03/25 18:13:46 broker opened at /home/philip/.influxdb/broker
[raft] marx:8086 2015/03/25 18:13:46 log pending: waiting for initialization or join
[raft] marx:8086 2015/03/25 18:13:46 log state change: stopped => leader
[raft] marx:8086 2015/03/25 18:13:46 log state change: leader => leader
[raft] marx:8086 2015/03/25 18:13:46 log initialize: promoted to 'leader' with cluster ID 1152189104239438750, log ID 1, term 1
[srvr] 2015/03/25 18:13:46 broker listening on :8086
[srvr] 2015/03/25 18:13:46 data server opened at /home/philip/.influxdb/data
[messaging] 2015/03/25 18:13:46 connected to broker: http://marx:8086/messaging/messages?index=0&streaming=true&topicID=0
[srvr] 2015/03/25 18:13:46 broker enforcing retention policies with check interval of 10m0s
[srvr] 2015/03/25 18:13:46 shard group pre-create with check interval of 45m0s
[srvr] 2015/03/25 18:13:46 data node #1 listening on :8086
[srvr] 2015/03/25 18:13:46 snapshot endpoint listening on 127.0.0.1:8087
[srvr] 2015/03/25 18:13:46 starting admin server on :8083
[srvr] 2015/03/25 18:13:46 Sending anonymous usage statistics to m.influxdb.com
```

**Comment by corylanou** [comment]
+1

**Comment by otoolep** [comment]
Merging this now since @pauldix has blessed this change in principle, and @corylanou has re-reviewed.

**Pull request merged**
