### PR TITLE
make SHOW queries work with FROM /<regex>/

### LINKED ISSUE #2644: SHOW queries should work with from regex
these queries should work:

```sql
show tag keys from /foo.*/ where host = 'asdf'

-- or this
show tag values from /foo.*/ with key = host
```

This should help address comments in grafana/grafana#1525

### PR DESCRIPTION
**Pull request by dgnorton**

### CODE REVIEW

**Comment by pauldix** [comment]
looks good, +1

**Comment by pauldix** [comment]
oh, update the changelog

**Comment by dgnorton** [comment]
@pauldix changelog updated

**Comment by toddboom** [comment]
+1

**Comment by toddboom** [comment]
@david this one needs a rebase after the `name` => `measurement` change got merged in. rebase and you're good to merge!

**Pull request merged**
