### PR TITLE
ServerID and ClusterID need to be strings when being sent to Enterprise.

### PR DESCRIPTION
**Pull request by markbates**
This is currently throwing errors when Enterprise tries to write this into the Enterprise InfluxDB database:

```
write failed: field type conflict: input field "cluster_id" on measurement "usage" is type float64, already exists as type string
```

This is because other products use strings for their ClusterID and ServerIDs.

### CODE REVIEW

**Comment by otoolep** [comment]
+1

**Comment by otoolep** [comment]
Are these values indexed as tags, or written as fields, when stored by Enterprise?

**Comment by otoolep** [comment]
Perhaps it doesn't matter?

**Comment by markbates** [comment]
Enterprise is just writing them as they're given straight into another InfluxDB. We add a few additional tags, but apart from that the data remains unchanged.

**Pull request merged**
