### PR TITLE
Move to Go 1.5.2

### PR DESCRIPTION
**Pull request by otoolep**

### CODE REVIEW

**Comment by otoolep** [comment]
Fixes https://github.com/influxdb/influxdb/issues/4760

**Comment by otoolep** [comment]
@rossmcdonald -- can you add the required change to this branch such that `build.py` uses Go 1.5.2?

**Comment by nathanielc** [comment]
@otoolep Should I update the docker envs to go1.5.2? Do we want to leave any testing on go1.4.2 in parallel?

**Comment by otoolep** [comment]
@nathanielc -- if we merge this, I don't see any point running 1.4.2 until we know for a fact we need to rollback. Yeah, I would change your stuff.

**Comment by rossmcdonald** [comment]
@otoolep The `build.py` script defaults to whatever is on the user's path, so there shouldn't need to be any changes there.

**Comment by nathanielc** [comment]
@rossmcdonald @otoolep OK I'll update the docker envs to use go 1.5.2 and hopefully we can get these both merged today.

**Comment by dgnorton** [comment]
+1

**Comment by otoolep** [comment]
+1 from @pauldix and @toddboom 

Any objections @jwilder @benbjohnson ?

**Comment by benbjohnson** [comment]
+1. Is it worth setting up a CI run against Go tip?

**Comment by otoolep** [comment]
Sure @benbjohnson -- @nathanielc has expressed an interest in doing something like that, though it would eat up another container.

**Comment by dgnorton** [comment]
@benbjohnson what's the advantage of a CI run against Go tip?

**Comment by otoolep** [comment]
OK, I think we have a decision -- moving to Go 1.5.2.

**Comment by otoolep** [comment]
@jwilder -- do let us know if you have any objections.

**Comment by benbjohnson** [comment]
@dgnorton If we see a lot of consecutive broken builds against tip then we can report the issue and get it fixed before it goes into the next Go release. I don't think we should worry about it too much but it would be good to know how influx performs against the upcoming release.

**Comment by mark-rushakoff** [comment]
+1 for a container testing against Go tip.

@benbjohnson said it best. Benchmarks would be very interesting, and if anything breaks due to changes in Go, we find out as early as possible.

The build against Go tip should be considered highly experimental and should not mean the InfluxDB build is failing, if *only* the Go tip build fails.

**Pull request merged**
