### PR TITLE
Display Enterprise message if no token set

### PR DESCRIPTION
**Pull request by otoolep**

### CODE REVIEW

**Comment by otoolep** [comment]
Example output:
```
$ influx 
Visit https://enterprise.influxdata.com to register for updates, InfluxDB server management, and monitoring.
Connected to http://localhost:8086 version 0.9
InfluxDB shell 0.9
```

**Comment by otoolep** [comment]
@pauldix @corylanou

**Comment by pauldix** [comment]
The `show diagnostics for registration` is already wired up?

**Comment by otoolep** [comment]
Yes, it is already wired up.

**Comment by pauldix** [comment]
+1

**Comment by bwhaley** [comment]
The enterprise message is shown for every query using the `-execute` flag. E.g. 

```
for i in $(influx -database graphitedb -execute 'show measurements'| egrep ^cas); do influx -database graphitedb -execute "drop measurement \"${i}\""; done
Visit https://enterprise.influxdata.com to register for updates, InfluxDB server management, and monitoring.
Visit https://enterprise.influxdata.com to register for updates, InfluxDB server management, and monitoring.
Visit https://enterprise.influxdata.com to register for updates, InfluxDB server management, and monitoring.
Visit https://enterprise.influxdata.com to register for updates, InfluxDB server management, and monitoring.
Visit https://enterprise.influxdata.com to register for updates, InfluxDB server management, and monitoring.
Visit https://enterprise.influxdata.com to register for updates, InfluxDB server management, and monitoring.
Visit https://enterprise.influxdata.com to register for updates, InfluxDB server management, and monitoring.
Visit https://enterprise.influxdata.com to register for updates, InfluxDB server management, and monitoring.
Visit https://enterprise.influxdata.com to register for updates, InfluxDB server management, and monitoring.
```

Seems like the message shouldn't be shown when using `-execute`

**Comment by otoolep** [comment]
Thanks @bwhaley -- I agree.

**Pull request merged**
