### PR TITLE
Fix error when alter retention policy

### PR DESCRIPTION
**Pull request by kylezh**
+ fix error when execute ALTER RETENTION POLICY bar ON foo DURATION 1h
+ add test to verify the fix

Signed-off-by: Kai Zhang <zhangk1985@gmail.com>

### CODE REVIEW

**Comment by otoolep** [comment]
Let me know when you have signed the CLA @kylezh

**Comment by kylezh** [comment]
@otoolep  I have signed the CLA with this github account but a different email address. Is that ok?

**Comment by otoolep** [comment]
Looks good @dgnorton ? CLA has been signed.

**Comment by dgnorton** [comment]
lgtm :shipit:

@kylezh thanks!

**Comment by otoolep** [comment]
Thanks @dgnorton.

**Comment by otoolep** [comment]
Thanks @kylezh

**Comment by otoolep** [comment]
Changelog updated. https://github.com/influxdb/influxdb/commit/db09b20d199c973a209e181c9e2f890969bd0b57#diff-4ac32a78649ca5bdd8e0ba38b7006a1e

**Pull request merged**
