### PR TITLE
SHOW SHARDS now includes database name and retention policy

### LINKED ISSUE #4660: SHOW SHARDS should include database and retention policy
`SHOW SHARDS` should be enhanced to show the associated database and retention policy, so it looks something like so:

```
> SHOW SHARDS
name: db
--------
id      database retention_policy    start_time              end_time                expiry_time             owners
1       mydb     default             1972-07-31T00:00:00Z    1972-08-07T00:00:00Z    1972-08-07T00:00:00Z    1
.
.
```
This should not be that difficult, as the information is all contained in the `meta` store, which every node has access to. It is https://github.com/influxdb/influxdb/blob/master/meta/statement_executor.go#L355 that needs updating. (`executeShowShardsStatement`).

### PR DESCRIPTION
**Pull request by pires**
- [ ] CHANGELOG.md updated
- [x] Rebased/mergable
- [x] Tests pass
- [x] Sign [CLA](http://influxdb.com/community/cla.html)

Fixes #4660

### CODE REVIEW

**Comment by otoolep** [comment]
Looks great @pires -- thank you.

@corylanou

**Comment by otoolep** [comment]
+1, will merge on second +1.

**Comment by corylanou** [comment]
Awesome!!!! +1

**Comment by pires** [comment]
Ahah you guys are awesome!

**Pull request merged**
