### PR TITLE
Update collectd plugin to write values under the field "value"

### PR DESCRIPTION
**Pull request by josh-padnick**
This is a fix for #2412.  I'm a golang newb, so I'll describe my testing procedure to make sure it's sufficient.

1. Forked repo
2. Used `go get x` to install each dependency
3. Ran `go test` and received `PASS`
4. Made fix
5. Ran `go test` and received `PASS`

Simple change, but this was holding us up.  Thanks.

### CODE REVIEW

**Comment by corylanou** [comment]
I would think that this test should be failing now:

https://github.com/josh-padnick/influxdb/blob/master/collectd/collectd_test.go#L186

The fact it was passing, and that this change didn't make it fail means the test likely needs to be fixed as well.

I'm not sure what tools the bug is referencing that expects it to always be `value` but I'm open to it.  It feels like this should probably be a configuration option though, unless this is 100% always a true case regardless of tools being used.

I would expect the following to be the norm unless in the config someone were to specify it differently.  However, I'm not a collectd expert, so I could be wrong. @otoolep @jwilder do either of you know?

```go
fields[data.Values[i].Name] = data.Values[i].Value
```

Let me know if you want to take another pass at this or need any help.

This does appear to be a bug.  Good catch and thanks for your efforts!

**Comment by josh-padnick** [comment]
@corylanou I've updated the test to include a case that now fails.  See latest commit.  This isn't yet ready for merging, though, because this test is failing now.

Regarding what's motivating this change in the first place, for our team, it came down to what Grafana is expecting, which I assume will be the overwhelmingly popular choice for dashboard.  Grafana assumes that every metric name's value is stored in a field called `value`, rather than a field like `disk_read`.  This means that you have to manually edit the query to get it working.

Certainly, Grafana could change its behavior, but since a measured named `disk_read` that has a field named `disk_read` seems redundant, I'm inclined to change the collectd plugin, not Grafana.

I'm not sure how to proceed from here, and am happy to pass this PR on to @kimor79 or someone else w/ more experience w/ the InfluxDB code base.

**Comment by otoolep** [comment]
Thanks @josh-padnick -- this is definitely an issue in the code. It should be using `value`. I'll take a look at this.

**Comment by otoolep** [comment]
Closing in favour of https://github.com/influxdb/influxdb/pull/2460

**Pull request closed without merging**
